### ISSUE TITLE
Add property for setting ProcessManager explicitly

### ISSUE THREAD

**Issue by alexey-atiskov** [sbraconnier/jodconverter#100]
On low-level CPU PC running UNIX there is a possibility to get incorrect pid (PID_NOT_FOUND) while using UnixProcessManager.
There is field processManager in LocalOfficeManager.Builder class but is not filled from JodConverterLocalProperties.

**Comment by alexey-atiskov** [comment]
I am preparing pull request for this

**Comment by sbraconnier** [comment]
Great! Thanks! 

It would be great to have a ProcessManager bean, something like:

```java
  @Bean
  @ConditionalOnMissingBean
  public ProcessManager processManager() {
    ...
  }
```

And then the `localOfficeManager` bean function would change to:

```java
  @Bean(name = "localOfficeManager", initMethod = "start", destroyMethod = "stop")
  @ConditionalOnMissingBean(name = "localOfficeManager")
  public OfficeManager localOfficeManager(final ProcessManager processManager) {

    return createOfficeManager(processManager);
  }
```

**Comment by alexey-atiskov** [comment]
> Great! Thanks!
> 
> It would be great to have a ProcessManager bean, something like:
> 
> ```java
>   @Bean
>   @ConditionalOnMissingBean
>   public ProcessManager processManager() {
>     ...
>   }
> ```
> 
> And then the `localOfficeManager` bean function would change to:
> 
> ```java
>   @Bean(name = "localOfficeManager", initMethod = "start", destroyMethod = "stop")
>   @ConditionalOnMissingBean(name = "localOfficeManager")
>   public OfficeManager localOfficeManager(final ProcessManager processManager) {
> 
>     return createOfficeManager(processManager);
>   }
> ```

Nice advice! Both ways were implemented.

**Comment by sbraconnier** [comment]
See #104. Thanks a lot for this PR!!!
