### ISSUE TITLE
How to set the print mode of office word as landscape

### ISSUE THREAD

**Issue by africancu** [sbraconnier/jodconverter#103]
How to set the print mode of office word as horizontal

**Comment by sbraconnier** [comment]
Could you please provide more information.

What is the source and target format (docx to pdf, odt to docx, something else...)? Is the source document orientation already is Landscape or if it is Portrait ? Are you using LibreOffice or OpenOffice and which version ? Thanks.

**Comment by sbraconnier** [comment]
Closing this one. Fell free to reopen if required.
