### ISSUE TITLE
Getting the slide thumbnails when exporting a ppt

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#108]
Hi,

we were using the old fork of XWiki for jodconverter and moving on to use your own, but we now have an issue when trying to convert presentation documents.
Basically when exporting a presentation in HTML in LibreOffice we obtain the html but also some pictures corresponding to the slides. We are using this behaviour to actually display the slides.
We were just using this line:
```
this.converter.convert(storage.getInputFile(), storage.getOutputFile());
```
with a file ".html" as output file.

Now we moved on this fork, I converted my old statement to that:

```
this.converter.convert(storage.getInputFile())
                .to(storage.getOutputFile())
                .execute();
```

but now I only get the html file in the output dir and no more the thumbnails of the slides. Any idea how to fix that?

**Comment by sbraconnier** [comment]
Could you please send me a sample I could work with while investigating this issue ?? It would be greatly appreciated.

**Comment by surli** [comment]
Forget it, while testing a small project to show you my issue I got the answer: I wasn't using the right properties for the export. Thanks anyway for maintaining this project :)
