### ISSUE TITLE
auto detection

### ISSUE THREAD

**Issue by zidekuls** [sbraconnier/jodconverter#114]
hello,can jodconverter detect the officehome automatelly either on window or linux?and please provide some sample code..

**Comment by sbraconnier** [comment]
Yes it can, if installed at the known default location. But it can be configured.

See [this wiki page](https://github.com/sbraconnier/jodconverter/wiki/Java-Library) for an example and [this one](https://github.com/sbraconnier/jodconverter/wiki/Configuration) for the configuration.
