### ISSUE TITLE
ExternalOfficeManager can't convert streams

### ISSUE THREAD

**Issue by buxxi** [sbraconnier/jodconverter#116]
When using the **ExternalOfficeManager** it throws an exception when trying to convert from an **InputStream** to an **OutputStream**.
> An office manager must implements the TemporaryFileMaker interface in order to be able to convert to OutputStream.

I can't really see why the **ExternalOfficeManager** couldn't implement that interface too as **AbstractOfficeManagerPool** does, since it is only doing local connections. 

Maybe there could be another method on the **ExternalOfficeManagerBuilder** for providing what **TemporaryFileMaker** to use instead of relying on casting to another interface?
```java
new ExternalOfficeManagerBuilder().setTemporaryFileMaker(customImplementation).build();
```

I've wrapped the **ExternalOfficeManager** and implemented **TemporaryFileMaker** on it and it seems to be working fine as a workaround.

**Comment by sbraconnier** [comment]
The next release will have a ExternalOfficeManager similar to the LocalOfficeManager. Streams will be supported. Thanks!
