### ISSUE TITLE
Create a PageSelectorFilter for Draw document (odg)

### ISSUE THREAD

**Issue by leonBeis** [sbraconnier/jodconverter#120]
While using 
```java
 LocalConverter  
                .builder()
                .filterChain(selectorFilter)
                .build()
                .convert(inputFile)
                .to(outputFile)
                .execute();
```
to convert a fodg file to a corresponding png file, I get an error when I try to apply a page filter even though the fodg file has more than 1 pages in length. 
Error is: 

> Could not apply filter org.jodconverter.filter.text.PageSelectorFilter.
org.jodconverter.office.OfficeException: Could not apply filter org.jodconverter.filter.text.PageSelectorFilter. at org.jodconverter.filter.AbstractFilterChain.doFilter(AbstractFilterChain.java:111) at org.jodconverter.filter.AbstractFilterChain.doFilter(AbstractFilterChain.java:90) at org.jodconverter.filter.DefaultFilterChain.doFilter(DefaultFilterChain.java:84) at org.jodconverter.task.LocalConversionTask.modifyDocument(LocalConversionTask.java:150) at org.jodconverter.task.LocalConversionTask.execute(LocalConversionTask.java:103)

Is the filter operation not supported for such formats or how to work around this, if thats possible?

**Comment by sbraconnier** [comment]
Hi there,

This is expected. Since the `PageSelectorFilter` is located in the `text` package, it means that it only works with text documents, and your file is a draw document.

I don't have time right now to write a new filter that would work with draw documents (I never worked with draw documents through the UNO api so I'll take some research), but I'll try to look at it next week.

**Comment by leonBeis** [comment]
Yes I noticed its in the text package but I didnt find any other filter for this case. Looking forward to it.

**Comment by sbraconnier** [comment]
Sorry for the insane delay. In the next release, a `PageSelectorFilter `in the `org.jodconverter.filter.draw` package will be available.
