### ISSUE TITLE
class ExternalOfficeManager is not Public

### ISSUE THREAD

**Issue by mondaka** [sbraconnier/jodconverter#121]
It is impossible to use that class without modifiying the library code. 

The ExternalOfficeManagerBuilder says: 
@deprecated Use {@link ExternalOfficeManager#builder()} instead.

But I cant use the method of a package private class.

**Comment by sbraconnier** [comment]
You are totally right!

**Comment by sepe81** [comment]
@sbraconnier Would it be possible to release a new patch version including this change? Otherwise `ExternalOfficeManager` is not usable with version https://github.com/sbraconnier/jodconverter/releases/tag/v4.2.2

**Comment by sbraconnier** [comment]
I've uploaded a 4.2.3-SNAPSHOT version, which is available in the [oss snapshot maven repository](https://oss.sonatype.org/content/repositories/snapshots/)
