### ISSUE TITLE
Is it possible to convert password protected Office file ?

### ISSUE THREAD

**Issue by hornet76** [sbraconnier/jodconverter#122]
Hello,

I have to convert a .doc file to PDF but this file is password protected.

Is there a way to provide password to the converter ?

I tried to use a loadProperty for input document format with no success.

Thanks for your help.

Regards,
Christophe

**Comment by sbraconnier** [comment]
Hi, sorry for the delay.

Are you able to open the document with LibreOffice without JodConverter ?

**Comment by hornet76** [comment]
Hi,

I finally found a solution by using custom load properties with this code:

```
Map<String, Object> loadProperties = new HashMap<String, Object>();
loadProperties.put("Hidden", true);
loadProperties.put("ReadOnly", true);
loadProperties.put("Password", "mypass");
DocumentFormat docFormat = DefaultDocumentFormatRegistry.DOC;
DocumentFormat pdfFormat = DefaultDocumentFormatRegistry.PDF; 
...
LocalConversionTask conversionTask = new LocalConversionTask(specSource, specTarget, loadProperties, filterChain, pdfFormat.getStoreProperties(DocumentFamily.TEXT));
officeManager.execute(conversionTask);
```

I'd prefer use your JodConverter but I did not found how to pass these loadProperties.

Thanks for your great job.

Bye,
Christophe
