### ISSUE TITLE
Great, finally... your the official successor

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#123]
![image](https://user-images.githubusercontent.com/136934/50384344-004e5100-06c4-11e9-8948-beaa26e27005.png)

i was fighting on your end and even before for having an official successor and now finally it's done.

I am glad he picked your fork, obviously the superior of all of the ones. Thank you for the hard work!

**Comment by sbraconnier** [comment]
And thanks to you for you kind words :)
