### ISSUE TITLE
HTML conversion: image URL encoding

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#125]
Hi,

it seems that the generated URLs for images when performing a conversion are only partially encoded.
For example, if you execute this script with a file "test.odt" containing a picture:

```java
File inputFile = new File("src/main/resources/odt/test.odt");
        File outputFile = new File("/tmp/jodtest/accent_é_+.html");

        LocalOfficeManager.Builder config = LocalOfficeManager.builder();
        LocalOfficeManager officeManager = config.build();
        officeManager.start();
        LocalConverter localConverter = LocalConverter.builder()
            .officeManager(officeManager)
            .build();
        localConverter.convert(inputFile)
            .to(outputFile)
            .execute();
        officeManager.stop();
```

You will obtain the following HTML for the embedded picture:
```
<img src="accent%C3%A9_+_html_7948573de0f15b63.png" name="Image1" align="left" width="665" height="252" border="0"/>
```

So the `é` is properly encoded but not the `+`: it's not a problem when you only need to display the page, but it's one when you process the produced DOM as a `+` is decoded as a space.
So for example if you execute this:
```
URLDecoder.decode("file:///tmp/jodtest/accent%C3%A9_+_html_7948573de0f15b63.png", "UTF8")
```

you will obtain:
> file:///tmp/jodtest/accenté_ _html_7948573de0f15b63.png

TBH I don't really know if it's problem that needs to be solved on jodconverter side or in libreoffice itself, but I guess that even if it's libreoffice side there's something to do in jodconverter, at least providing a filter to convert those URL, WDYT?

**Comment by sbraconnier** [comment]
Hmm I see. This is a LibreOffice problem indeed but as you said it would be nice to have a special filter for this in JODConverter. Could you please provide a sample project I would be able to work with that reproduces this problem ? Thanks a lot!

**Comment by surli** [comment]
You can find the snippet above in action there: https://github.com/surli/testjodconverter

**Comment by sbraconnier** [comment]
Thank! I'll see what I can do.

**Comment by sbraconnier** [comment]
After several tries, I wasn't able to create a filter that can do the job. I'm not sure it can be done with the UNO API. If it still exists, this problem should probably be fixed by the LibreOffice team.
