### ISSUE TITLE
Cannot start converter in Docker

### ISSUE THREAD

**Issue by Slava96** [sbraconnier/jodconverter#126]
I create a converter with Spring Boot, and have Docker image with jre8 and libreoffice 6 inside image.
When i try to start, I have Unsatisfaedlinkerror because program cannot see libjpipe.

My JAVA_OPTS to start is:
-Doffice.path=/usr/lib/libreoffice
-Djava.library.path=/usr/lib/libreoffice/program

**Comment by Slava96** [comment]
[logs.txt](https://github.com/sbraconnier/jodconverter/files/2840209/logs.txt)
[ODTtoPDFconverter.zip](https://github.com/sbraconnier/jodconverter/files/2840212/ODTtoPDFconverter.zip)

**Comment by sbraconnier** [comment]
Maybe you should take a look at this:
https://stackoverflow.com/questions/15503015/getting-started-with-uno-and-java-with-open-libreoffice

**Comment by sbraconnier** [comment]
I'm closing this one. Feel free to reopen it if you have more to ask.
