### ISSUE TITLE
Is there a version that supports JDK6

### ISSUE THREAD

**Issue by samz406** [sbraconnier/jodconverter#129]
Is there a version that supports JDK6？

**Comment by samz406** [comment]
I want a version to support JDK6

**Comment by sbraconnier** [comment]
Sorry, the current version has Java 8 as baseline and the first release (4.0.0) has 7 as baseline.

**Comment by samz406** [comment]
> Sorry, the current version has Java 8 as baseline and the first release (4.0.0) has 7 as baseline.

thank you
