### ISSUE TITLE
ExternalOfficeManager creates temporary files in the current directory

### ISSUE THREAD

**Issue by buxxi** [sbraconnier/jodconverter#130]
When trying out the fixes for #116 I got a problem with permission denied for the temporary files.
After a bit of debugging I found out that it tries to write the temporary files in the directory where the program was started from and not in /tmp as it should be.

https://github.com/sbraconnier/jodconverter/blob/bab3340d41fe6821ccc80b4526461124d6f0eccd/jodconverter-core/src/main/java/org/jodconverter/office/AbstractOfficeManager.java#L73-L75

It seems like tempDir is null here since no call to makeTempDir() is made.

**Comment by sbraconnier** [comment]
Thanks! It will be included in the next version.
