### ISSUE TITLE
StarOffice.ServiceManager started but its pid could not be found linux headless mode

### ISSUE THREAD

**Issue by andron3000** [sbraconnier/jodconverter#131]
> A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' started but its pid could not be found

This issue is reproducible on linux machine without gui(headless mode). I've also noticed a bunch of zombie process(soffice.bin). Thanks in advance.

**Comment by andron3000** [comment]
```
@Configuration
public class LibreOfficeConfig {

    @Value("${libre.office.path}")
    private String officeHomeDirectory;

    @Bean
    public OfficeManager officeManagerConfig() {
        return LocalOfficeManager.builder()
                .install()
                .officeHome(Paths.get(officeHomeDirectory).toFile())
                .install()
                .build();
    }
}

public class LibreOfficeConversionServiceImpl implements DocumentConversionChain {
    private void startOfficeManager() {
        if (!officeManager.isRunning()) {
            try {
                officeManager.start();
            } catch (OfficeException e) {
                throw new RedactionServiceException(e.getMessage(), e);
            }
        }
    }
}
```

**Comment by sbraconnier** [comment]
Could you please set the loglevel to TRACE and put back here the log file ?? Doing that will display the output of the commands that are executed to retrieve the process ids.

**Comment by andron3000** [comment]
Here: 
[log.txt](https://github.com/sbraconnier/jodconverter/files/2891282/log.txt)

**Comment by sbraconnier** [comment]
You have the same problem as describe [here](https://github.com/sbraconnier/jodconverter/issues/127#issuecomment-463275515).

The It seems to be the `/bin/ps` command is not found. You must ensure that it is available in your Docker container.

**Comment by andron3000** [comment]
Thank you a lot.
