### ISSUE TITLE
Add all supported extensions to PDF conversion support.

### ISSUE THREAD

**Issue by andron3000** [sbraconnier/jodconverter#132]
Hi,

Can I convert the Microsoft Visio document (vsd / vsdx) to pdf using the existing library?

After analyzing **DefaultDocumentFormatRegistry** class, it's seems like these formats are not supported.

Thanks.

**Comment by sbraconnier** [comment]
Are you able to do it with LibreOffice without JODConverter ?

**Comment by andron3000** [comment]
Yes, this is definitely possible (I double checked to be sure):

`libreoffice --headless --convert-to pdf test.vsdx`

`soffice --headless --convert-to pdf test.vsdx`

Please, consider attachment:

![result](https://user-images.githubusercontent.com/18425328/53291057-017c2700-37b6-11e9-87cf-c7053221f623.png)

**Comment by andron3000** [comment]
@sbraconnier, could you add such things to jodconverter? Thanks.

**Comment by andron3000** [comment]
The same with **EPS** image format. I've found workaround using SimpleDocumentFormatRegistry class, but it's quite awkward.

**Comment by sbraconnier** [comment]
@andron3000 Did you actually try using the JODConverter library ? It seems to work out of the box, but I may be wrong.

**Comment by sbraconnier** [comment]
You don't need to add anything to the registry to convert "to pdf".

**Comment by andron3000** [comment]
@sbraconnier , I spent a lot of time on it, but didn't find out of box solution.

![image](https://user-images.githubusercontent.com/18425328/53437201-a50f4680-3a05-11e9-915e-fe94e0ec3e52.png)

How it's possible to specify input document format(vsd/vsdx/eps), if it even not described in any library class.

**Comment by sbraconnier** [comment]
Ah! I didn't know you were using an input stream as source, thus requiring a input format. In this particular case, the input format seems to be required, but it is not necessary. I will open an issue for this. As a workaround, use any other existing format. The input format is not used to detect the file format. This is done by LibreOffice, so any format will do:

```java
    localConverter.
        // Your visio stream
        .convert(inputStream)
        // Will create a temp file with a ".doc" extension, but LibreOffice will still detect a visio document.
        .as(DefaultDocumentFormatRegistry.DOC) 
        .to(outputStream)
        .as(DefaultDocumentFormatRegistry.PDF)
        .execute();
```

**Comment by andron3000** [comment]
Thanks

**Comment by AdrienNguyenWorldline** [comment]
Hi we have similar request. Id did manage to use command line to to convert an ODT (Miscrosoft Office Document Template) to PDF.

But for the same reason DefaultDocumentFormatRegistry does not find an entry for a a file with .odt as extension.

**Comment by sbraconnier** [comment]
The input format requirement has been removed. This change will be available in the next release.  You will be able to do:

```
    localConverter.
        .convert(inputStream)
        .to(outputStream)
        .as(DefaultDocumentFormatRegistry.PDF)
        .execute();
```

The current version already support this if you are working with a file as input (not stream).

**Comment by AdrienNguyenWorldline** [comment]
@sbraconnier Any roadmap for a release date ? considering last release was november 2018

**Comment by sbraconnier** [comment]
I was supposed to release a version last week but some new issues were opened. I will release a version as soon as possible. It is on my todos list.
