### ISSUE TITLE
unidentifiable code when chinese txt convert pdf  

### ISSUE THREAD

**Issue by samz406** [sbraconnier/jodconverter#133]
Hi,i want to txt convert pdf, the txt document is chinese like char 你好 ，when i use windows 10 convert, it's ok,but i use centeros convert have unidentifiable Chinese code, Do are you some advise? my openoffice is 4.1.6,jodconvert is 4.1.0.

**Comment by ValentinBouffard** [comment]
Do you have a chinese font in your openoffice on your centeros ?

**Comment by samz406** [comment]
> Do you have a chinese font in your openoffice on your centeros ?
  I add two fonts , simhei.ttf and simsun.ttc .it's not work. however i convert doc,ppt, it's ok。
txt convert pdf result  like this.
![qq 20190301105115](https://user-images.githubusercontent.com/3055810/53613133-0b67b500-3c10-11e9-8d4f-a5b21578398d.png)

**Comment by ValentinBouffard** [comment]
Did you check that your .txt is encoded in UTF-8 and not in ansi ?

**Comment by samz406** [comment]
maybe GB2312 encoded. I my computer os is windows 10  chinese version.  openoffice version is Apache_OpenOffice_4.1.6_Win_x86_install_zh-CN.

I upload txt file and java code 
url:  https://pan.baidu.com/s/1rC07g2pdDJDbxOoZZQL4QA   
password: qsu7

you can download it，please try again

**Comment by ValentinBouffard** [comment]
If you have a git repo it will be easier. I had the same issue a year ago, I bet my hand that this is related to your env not to your code.

**Comment by samz406** [comment]
that's means   the txt document  must be utf-8 encode. when use openoffice convert it ?

**Comment by ValentinBouffard** [comment]
Did it works ?

**Comment by samz406** [comment]
you are  right. if  txt document encode  is gb2312 ，it is unidentifiable code. I manual create txt doc is gb2312 encode in os of chinese language.

**Comment by ValentinBouffard** [comment]
I think, you can close your request if it is working now.
