### ISSUE TITLE
Add support for "XHTML" LibreOffice filters

### ISSUE THREAD

**Issue by linux-warrior** [sbraconnier/jodconverter#134]
In certain use cases "XHTML" filters, which are mentioned in [OpenOffice Wiki](https://wiki.openoffice.org/wiki/Framework/Article/Filter/FilterList_OOo_3_0), can produce better results than their "HTML" counterparts, so it may be beneficial to give JODConverter users another option.

**Comment by sbraconnier** [comment]
Thanks a lot!!! Wee appreciated. You PR has been merged.

**Comment by linux-warrior** [comment]
Thanks. Could you possibly upload a new release, containing the recent changes in `master` branch, to Maven Central Repository?

**Comment by sbraconnier** [comment]
I'll try to do it next week! I want to fix #132 , then I'll upload a new release.
