### ISSUE TITLE
about Multi process execute

### ISSUE THREAD

**Issue by samz406** [sbraconnier/jodconverter#136]
hey ! I have a question for you.
I find the multiple conversion [FAQ](https://github.com/sbraconnier/jodconverter/wiki/FAQ#is-it-possible-to-execute-multiple-conversions-at-the-time).So i think it can be process multi covnersion,
I use jodconverter in web project, OfficeManager be created(4 ports) when web project started.
the conversion code as follow
``` java
 LocalConverter.builder()
                        .officeManager(officeManager)
                        .build()
                        .convert(inputFile)
                        .to(file)
                        .execute(); 

```
**first** ,  GET  big file(20M) to convert pdf,  log as follow

```

2019-03-06 17:04:15,439 pool-2-thread-1 DEBUG org.jodconverter.office.OfficeProcessManager - Task 'Start' executed successfully
2019-03-06 17:04:30,607 pool-2-thread-1 DEBUG org.jodconverter.office.AbstractOfficeManagerPoolEntry - Waiting for task to complete...
2019-03-06 17:04:30,611 OfficeManagerPoolEntry-4 INFO  org.jodconverter.task.LocalConversionTask - Executing local conversion task...
```

**and then** ,I also  GET little file(0.4M) convert to pdf.

but  2  mins later, that's the first convert process finish. then  convert little file.
I don't know how to create  asynchronous process, can you help me ?

**Comment by sbraconnier** [comment]
Hmm... ok. I would need more information to help you. How are you testing this ? If you have a WEB app starting 4 Office instances, then 2 clients would be able to send conversion request simultaneously. The same would be true for a single client, using 2 threads. But 1 client, using a single thread, would not.

Could you explain in details how you test this ?

**Comment by samz406** [comment]
In this way.I want to simultaneously  two convert process ,code as follow.
```java
public class Demo {


    private static OfficeManager officeManager;

    private static int OPEN_OFFICE_PORT[] = {8100, 8102, 8103, 8104};


    public static void office2Pdf(File inputFile, File pdfFile) {

        try {
            LocalConverter.builder()
                    .officeManager(officeManager)
                    .build()
                    .convert(inputFile)
                    .to(pdfFile)
                    .execute();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void startService() {
        try {

            officeManager = LocalOfficeManager.builder()
                    .portNumbers(OPEN_OFFICE_PORT)
                    .taskExecutionTimeout(1000 * 60 * 5L)
                    .taskQueueTimeout(1000 * 60 * 60 * 24L)
                    .officeHome("D:\\Program Files (x86)\\OpenOffice 4")
                    .build();
            officeManager.start();
        } catch (Exception e) {
            OfficeUtils.stopQuietly(officeManager);
        }
    }

    public static void main(String[] args) {
        startService();
        //I want to simultaneously  two convert process,
        office2Pdf(new File("D:\\file1.txt"), new File("D:\\file1.pdf"));
        office2Pdf(new File("D:\\file2.txt"), new File("D:\\file2.pdf"));

        OfficeUtils.stopQuietly(officeManager);
    }

}
```

but it's synchronous process,  can you give me  some advice change it?

**Comment by samz406** [comment]
I found something  when i read source code ,

```JAVA
** A thread pool executor that can be suspended. Only 1 thread is allowed in the pool and */
class SuspendableThreadPoolExecutor extends ThreadPoolExecutor {

  private boolean available;
  private final ReentrantLock suspendLock = new ReentrantLock();
  private final Condition availableCondition = suspendLock.newCondition();

  /* default */ SuspendableThreadPoolExecutor(final ThreadFactory threadFactory) {
    super(1, 1, 0L, TimeUnit.MILLISECONDS, new LinkedBlockingQueue<Runnable>(), threadFactory);
  }
```

The ThreadPoolExecutor  default max thread is 1,so it can not be synchronous , Is  that right ?

**Comment by sbraconnier** [comment]
The way jodconverter works is similar to a database connection pool. When you start a manager using 4 ports, it will launch 4 office processes waiting for conversion tasks, the same way a database connection pool would open 4 database connections if configured to do so. What it means is that an office manager accessed in a multi-thread way would be able to serve 4 threads at the time, the others would wait for an office instance to be returned to the pool.

In your case, you are not using jodconverter in a multi-thread way, you are using a single thread. The `execute()` function if blocking. So it will wait for the conversion process to complete before returning.

The `SuspendableThreadPoolExecutor`  is used to be able to suspend an office thread while there is an office restart in process, after an office crash or the maximum number of conversions is reached for a process.

For your particular case (which should be improved to better exceptions and threads management), try changing your `office2Pdf` function like this, which will start a new thread for each conversion:

```java
  public static void office2Pdf(File inputFile, File pdfFile) {

    new Thread(
            () -> {
              try {
                LocalConverter.builder()
                    .officeManager(officeManager)
                    .build()
                    .convert(inputFile)
                    .to(pdfFile)
                    .execute();
              } catch (Exception e) {
                e.printStackTrace();
              }
            })
        .start();
  }
```

**Comment by samz406** [comment]
OK ，thank you! i got it
