### ISSUE TITLE
lost images while converting to pdf

### ISSUE THREAD

**Issue by renwuxun** [sbraconnier/jodconverter#138]
@sbraconnier [lostimage.docx](https://github.com/sbraconnier/jodconverter/files/2982403/lostimage.docx)

**Comment by sbraconnier** [comment]
Which version(s) are you using ??

I tried using JODConverter 4.2.2 and LibreOffice 6.2.1.2 and it worked. No images lost.

**Comment by renwuxun** [comment]
@sbraconnier
 i tried jodconverter-2.2.2/4.2.2 + OpenOffice-4.1.2, but no LibreOffice, maybe it the problem of OpenOffice.
i will try again with LibreOffice.
thx!

**Comment by sbraconnier** [comment]
So. Did it work with LibreOffice ?

**Comment by renwuxun** [comment]
@sbraconnier It work well with LibreOffice, maybe i need some options while OpenOffice.

**Comment by sbraconnier** [comment]
Well maybe. But it could be a bug with OpenOffice. I'll close this one since it works with LibreOffice.
