### ISSUE TITLE
When a line break occurs in the conversion excel document, how should it be invoked?

### ISSUE THREAD

**Issue by gggscfaii** [sbraconnier/jodconverter#140]
When a line break occurs in the conversion excel document, how should it be invoked?

now code:
                Map<String, Object> proerties = Maps.newHashMap();
                proerties.put("PaperFormat", PaperFormat.USER);
                proerties.put("PaperSize", new Size(190000, 60000));
            LocalConverter.builder().storeProperties(proerties).build().convert(inputFile).to(outputFile).execute();

![image](https://user-images.githubusercontent.com/10670841/55426217-cfc95d80-55b6-11e9-8230-3fc5acbc3ee5.png)

![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by sbraconnier** [comment]
I'm not sure I follow... What are you expecting exactly ??? Are you able to do properly do what you want without JODConverter ? What are the steps you are doing when you do it manually with LibreOffice?

**Comment by cwm-peace** [comment]
I convert Excel by executing the jodconverter-cli command on CentOS. After converting the pdf format, I find that there will be line breaks. My service is openoffice. Please should I adjust my Excel file or should I add a configuration file for conversion when executing the command?
