### ISSUE TITLE
version 4.2.2 convert docx to pdf failed, but version 3.0-beta-4 work well, why?

### ISSUE THREAD

**Issue by yuweiming2016** [sbraconnier/jodconverter#142]
version 4.2.2 convert docx to pdf failed, but version 3.0-beta-4 work well. why?
[1111.docx](https://github.com/sbraconnier/jodconverter/files/3037668/1111.docx)
[1111.pdf](https://github.com/sbraconnier/jodconverter/files/3037674/1111.pdf)

my convertion  code as follow：
JodConverter.convert(inputStream)
            .as(DefaultDocumentFormatRegistry.DOC)
            .to(outFile).as(DefaultDocumentFormatRegistry.PDF).execute();

@sbraconnier

**Comment by sbraconnier** [comment]
Well ? Did it work finally ?
