### ISSUE TITLE
OpenOffice launched while I call the code.

### ISSUE THREAD

**Issue by sunnyqijoinhand** [sbraconnier/jodconverter#143]
```java
try {
  officeManager =
      LocalOfficeManager.builder()
          .maxTasksPerProcess(100)
          .processRetryInterval(1000)
          .processTimeout(5 * 60 * 1000)
          .officeHome(office_home)
          .portNumbers(8101)
          .build();
  officeManager.start();
  IsLocalOfficeManager = true;
  System.out.println(
      "[JOD_ConverterService] Connected to Local OfficeManager. Port:" + String.valueOf(8101));

  // log.info("JOD_ConverterService - Connected to Local OfficeManager.");
  return true;
} catch (Exception ex) {
  System.out.println(
      "JOD_ConverterService - Initialize OfficeManager  - FAILED - " + ex.getMessage());
  // log.error("JOD_ConverterService - Initialize OfficeManager - FAILED - " +
  // ex.getMessage());
  return false;
}
```

**Comment by sunnyqijoinhand** [comment]
![Snip20190416_1](https://user-images.githubusercontent.com/49417816/56191361-cc29e200-605e-11e9-9ddb-0f001a8acf55.png)
![Snip20190416_2](https://user-images.githubusercontent.com/49417816/56191362-ccc27880-605e-11e9-8ee2-27fa576f15d9.png)

**Comment by sunnyqijoinhand** [comment]
BTW,  if I use LibreOffice, the code runs correctly. No LibreOffice window launched. I think something wrong with OpenOffice 4.1.6 as  --nofirststartwizard not be added to command line.

**Comment by sbraconnier** [comment]
Which version of jodconverter are you using ?? On which OS? I just tried on Windows with the same OpenOffice as you, and it didn't shown any wizard. Could you try again with the log level set to TRACE and put back here the result. Thanks.

**Comment by sunnyqijoinhand** [comment]
I found the reason. 
ENV:
Windows 2012 Standard Server 64bit
Jodconverter 4.2.2
OpenOffice 4.1.6

ISSUE:
1. Install Apache OpenOffice to D:\LibreOffice directory. <--- this is my fault. BUT this is the reason why issue comes.
2. Run the code.
3. OpenOffice Registration Wizard launched.

TRACE LOG:
[log] 2019-04-17 09:25:32,590 [Thread-17] INFO   - Run JOD_OfficeToPDF
[log] 2019-04-17 09:25:32,660 [Thread-17] TRACE  - Command Output: TASKKILL [/S system [/U username [/P [password]]]]
         { [/FI filter] [/PID processid | /IM imagename] } [/T] [/F]
[log] 2019-04-17 09:25:32,661 [Thread-17] INFO   - Submitting task 'Start' and waiting...
[log] 2019-04-17 09:25:32,662 [OfficeProcessThread-1] TRACE  - Finding PID using
Command to get current running processes: [cmd, /c, wmic process where(name like 'soffice%') get commandline,processid]
Regex used to match current running process lines: ^\s*(?<CommanLine>.*?)\s+(?<Pid>\d+)\s*$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
[log] 2019-04-17 09:25:32,782 [OfficeProcessThread-1] TRACE  - Command Output: CommandLine                                                                                                                                                     ProcessId  
"D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard                                               1352       
"D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"  6072       
[log] 2019-04-17 09:25:32,782 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: CommandLine                                                                                                                                                     ProcessId  
[log] 2019-04-17 09:25:32,783 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: "D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard                                               1352       
[log] 2019-04-17 09:25:32,783 [OfficeProcessThread-1] TRACE  - Line matches!
pid: 1352; Command line: "D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard
Checking if this command line matches the office command line regex
[log] 2019-04-17 09:25:32,783 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: "D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"  6072       
[log] 2019-04-17 09:25:32,783 [OfficeProcessThread-1] TRACE  - Line matches!
pid: 6072; Command line: "D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"
Checking if this command line matches the office command line regex
[log] 2019-04-17 09:25:32,784 [OfficeProcessThread-1] WARN   - Profile dir 'C:\Users\ADMINI~1\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1' already exists; deleting
[log] 2019-04-17 09:25:32,784 [OfficeProcessThread-1] DEBUG  - Deleting instance profile directory 'C:\Users\ADMINI~1\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1'
[log] 2019-04-17 09:25:32,894 [OfficeProcessThread-1] INFO   - soffice info (from exec path): Product: LibreOffice - Version: ??? - useLongOptionNameGnuStyle: true
[log] 2019-04-17 09:25:32,894 [OfficeProcessThread-1] INFO   - Starting process with acceptString 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir 'C:\Users\ADMINI~1\AppData\Local\Temp\.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1'
[log] 2019-04-17 09:25:32,901 [OfficeProcessThread-1] TRACE  - Finding PID using
Command to get current running processes: [cmd, /c, wmic process where(name like 'soffice%') get commandline,processid]
Regex used to match current running process lines: ^\s*(?<CommanLine>.*?)\s+(?<Pid>\d+)\s*$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
[log] 2019-04-17 09:25:33,030 [OfficeProcessThread-1] TRACE  - Command Output: CommandLine                                                                                                                                                                                                                                                                                                                                                                                                            ProcessId  
"D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard                                                                                                                                                                                                                                                                                                      1352       
"D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"                                                                                                                                                                                                                                                         6072       
"D:\LibreOffice\program\soffice.exe" --accept=socket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///C:/Users/ADMINI~1/AppData/Local/Temp/.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1                                                      1348       
"D:\LibreOffice\program\soffice.exe" "--accept=socket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager" "--headless" "--invisible" "--nocrashreport" "--nodefault" "--nofirststartwizard" "--nolockcheck" "--nologo" "--norestore" "-env:UserInstallation=file:///C:/Users/ADMINI~1/AppData/Local/Temp/.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1" "-env:OOO_CWD=2D:\\IBM\\Domino"  3156       
[log] 2019-04-17 09:25:33,030 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: CommandLine                                                                                                                                                                                                                                                                                                                                                                                                            ProcessId  
[log] 2019-04-17 09:25:33,033 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: "D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard                                                                                                                                                                                                                                                                                                      1352       
[log] 2019-04-17 09:25:33,033 [OfficeProcessThread-1] TRACE  - Line matches!
pid: 1352; Command line: "D:\LibreOffice\program\soffice.exe" -headless -accept="socket,host=127.0.0.1,port=8100;urp;" -nofirststartwizard
Checking if this command line matches the office command line regex
[log] 2019-04-17 09:25:33,033 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: "D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"                                                                                                                                                                                                                                                         6072       
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] TRACE  - Line matches!
pid: 6072; Command line: "D:\LibreOffice\program\soffice.exe" "-headless" "-accept=socket,host=127.0.0.1,port=8100;urp;" "-nofirststartwizard" "-env:OOO_CWD=2D:\\LibreOffice\\program"
Checking if this command line matches the office command line regex
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] TRACE  - Checking if process line matches the process line regex
Process line: "D:\LibreOffice\program\soffice.exe" --accept=socket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///C:/Users/ADMINI~1/AppData/Local/Temp/.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1                                                      1348       
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] TRACE  - Line matches!
pid: 1348; Command line: "D:\LibreOffice\program\soffice.exe" --accept=socket,host=127.0.0.1,port=8101,tcpNoDelay=1;urp;StarOffice.ServiceManager --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore -env:UserInstallation=file:///C:/Users/ADMINI~1/AppData/Local/Temp/.jodconverter_socket_host-127.0.0.1_port-8101_tcpNoDelay-1
Checking if this command line matches the office command line regex
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] DEBUG  - Command line matches! Returning pid: 1348
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] INFO   - Started process; pid = 1348
[log] 2019-04-17 09:25:33,034 [OfficeProcessThread-1] DEBUG  - Connecting with connectString 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'
[log] 2019-04-17 09:25:34,038 [OfficeProcessThread-1] TRACE  - The Office process has not yet terminated.
[log] 2019-04-17 09:25:35,038 [OfficeProcessThread-1] DEBUG  - Connecting with connectString 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'
[log] 2019-04-17 09:25:36,041 [OfficeProcessThread-1] TRACE  - The Office process has not yet terminated.
[log] 2019-04-17 09:25:37,041 [OfficeProcessThread-1] DEBUG  - Connecting with connectString 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'
[log] 2019-04-17 09:25:38,044 [OfficeProcessThread-1] TRACE  - The Office process has not yet terminated.
[log] 2019-04-17 09:25:39,044 [OfficeProcessThread-1] DEBUG  - Connecting with connectString 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'
[log] 2019-04-17 09:25:40,048 [Thread-17] DEBUG  - ExecutionException catched in submitAndWait
java.util.concurrent.ExecutionException: org.jodconverter.office.OfficeException: Office process died with exit code 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:133)
	at java.util.concurrent.FutureTask.get(FutureTask.java:203)
	at org.jodconverter.office.OfficeProcessManager.submitAndWait(OfficeProcessManager.java:299)
	at org.jodconverter.office.OfficeProcessManager.startAndWait(OfficeProcessManager.java:254)
	at org.jodconverter.office.OfficeProcessManagerPoolEntry.doStart(OfficeProcessManagerPoolEntry.java:168)
	at org.jodconverter.office.AbstractOfficeManagerPoolEntry.start(AbstractOfficeManagerPoolEntry.java:144)
	at org.jodconverter.office.AbstractOfficeManagerPool.doStart(AbstractOfficeManagerPool.java:188)
	at org.jodconverter.office.AbstractOfficeManagerPool.start(AbstractOfficeManagerPool.java:113)
	at org.jodconverter.office.LocalOfficeManager.start(LocalOfficeManager.java:38)
	at JOD_ConverterService.connectToOfficeManager(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at lotus.domino.JavaConnectInvoker.invoke(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at lotus.domino.JavaConnectLoader.invoke(Unknown Source)
Caused by: org.jodconverter.office.OfficeException: Office process died with exit code 0
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:87)
	at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
	at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
	at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
	at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:261)
	at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:256)
	at java.util.concurrent.FutureTask.run(FutureTask.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(Thread.java:811)
Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'; java.net.ConnectException: Connection refused: connect
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:170)
	at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:61)
	... 10 more
Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused: connect
	at com.sun.star.lib.connections.socket.socketConnector.connect(socketConnector.java:144)
	at com.sun.star.comp.connections.Connector.connect(Connector.java:119)
	at org.jodconverter.office.OfficeConnection.connect(OfficeConnection.java:106)
	... 11 more

=====================
If I install Apache OpenOffice to D:\LibreOffice , jodconvert consider the product is LibreOffice!!!
If I install Apache OpenOffice to D:\OpenOffice,  everything is ok.

**Comment by sbraconnier** [comment]
Aaahh!! Ok :) Glad you found your problem!! I'm closing this.
