### ISSUE TITLE
How to change the Paper Format before export PDF?

### ISSUE THREAD

**Issue by Dawnki** [sbraconnier/jodconverter#144]
Hi,

I want to change Paper Format(width,height or Orientation) before convert XLS to PDF. How to do it? 

Libreoffice version: 6.1.5
Jodconverter version: 4.2.2

I try it，but it doesn't work:

Map<String, Object> properties = new HashMap<>();
properties.put("PaperFormat", PaperFormat.USER);
properties.put("PaperSize", new Size(60000, 60000));
properties.put("PaperOrientation", PaperOrientation.LANDSPACE);
LocalConverter.builder().storeProperties(properties).build().convert(input).to(output).execute();

**Comment by Dawnki** [comment]
oh, I solve it by using filter!

**Comment by sbraconnier** [comment]
Glad to hear that!! Would you mind sharing your findings? It may be useful for other jodconverter users!

**Comment by Dawnki** [comment]
@sbraconnier  Sure!

MyFilter.java
```java
class MyFilter implements Filter {
    @Override
    public void doFilter(OfficeContext context, XComponent document, FilterChain chain) throws Exception {
        XPrintable xPrintable = UnoRuntime.queryInterface(XPrintable.class, document);
        PropertyValue[] props = new PropertyValue[2];

        PropertyValue p1 = new PropertyValue();
        p1.Name = "PaperFormat";
        p1.Value = PaperFormat.USER;
        props[0] = p1;

        PropertyValue p2 = new PropertyValue();
        p2.Name = "PaperSize";
        p2.Value = new Size(90000, 120000);  // width,height
        props[1] = p2;

//        PropertyValue p3 = new PropertyValue();
//        p3.Name = "PaperOrientation";
//        p3.Value = PaperOrientation.LANDSCAPE; // LANDSCAPE or PORTRAIT
//        props[0] = p3;

        xPrintable.setPrinter(props);
        chain.doFilter(context, document);
    }
}
```

Main
```java
MyFilter filter = new MyFilter();
LocalConverter
     .builder()
     .filterChain(filter)
     .build()
     .convert(input)
     .to(output)
     .execute();
```

Note: But this way just can change the sheet 1 's PaperFormat. if the xls document have many sheets, we need to select other page(XDrawPages)

**Comment by Dawnki** [comment]
issue #103 #140  , may be can try this way

**Comment by NABEEL-AHMED-JAMIL** [comment]
Hi All,
I have a question, i have different excel which have different width how i check the size and apply size in filter?
