### ISSUE TITLE
org.jodconverter.office.OfficeException: Task did not complete within timeout

### ISSUE THREAD

**Issue by legolas** [sbraconnier/jodconverter#146]
Hello, first I'd like to thank you guys for doing a great job developing the JodConverter.
I am using this as part of a conversion process to convert an [EAD](https://en.wikipedia.org/wiki/Encoded_Archival_Description) to a PDF.
Each ead is first converted to odt using xslt then the resulting odt is converted to pdf using JodConverter. This process is implemented using spring-boot-batch.
While running a batch of around 400 EAD I see the `org.jodconverter.office.OfficeException` for four EAD's failing to generate the pdf. I have configure the processTimeout to 10 minutes and added 5 ports but that does not help:
```
officeManager = LocalOfficeManager
        .builder()
        .portNumbers(2002, 2003, 2004, 2005, 2006)
        .processTimeout(TEN_MINUTES)
        .build()
        .install();
```
Is there something else I can do to prevent this timeout?

**Comment by sbraconnier** [comment]
Hello there. Changing the process timeout won't help since it involves the launch and kill of an office process. But maybe you could play with [taskExecutionTimeout](https://github.com/sbraconnier/jodconverter/wiki/Configuration#watchtaskexecutiontimeout) and [maxTasksPerProcess](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234maxtasksperprocess)

**Comment by legolas** [comment]
Thank you for your response. I have altered the configuration to:
```
officeManager = LocalOfficeManager
        .builder()
        .portNumbers(2002, 2003, 2004, 2005, 2006)
        .taskExecutionTimeout(TEN_MINUTES)
        .build()
        .install();
```
but to no avail, executing the job still throws:
```
13:04:41.273 [main]            ERROR n.n.gaf.batch.pdf.PdfGenerator - Error generating pdf of /var/data/files/gaf/ead/NL-HaNA/4.WCA/4.WCA.odt.
org.jodconverter.office.OfficeException: Task did not complete within timeout
	at org.jodconverter.office.AbstractOfficeManagerPoolEntry.execute(AbstractOfficeManagerPoolEntry.java:93)
	at org.jodconverter.office.AbstractOfficeManagerPool.execute(AbstractOfficeManagerPool.java:84)
	at org.jodconverter.office.LocalOfficeManager.execute(LocalOfficeManager.java:38)
	at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:189)
	at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57)
```

**Comment by sbraconnier** [comment]
Try setting the [maxTasksPerProcess](https://github.com/sbraconnier/jodconverter/wiki/Configuration#1234maxtasksperprocess) to 50. It it doesn't work, try with 25.

Also, can you tell if the failures occurred for the same documents ??

**Comment by legolas** [comment]
Thanks Simon, adding the `maxTasksPerProcess(50)` did the job.
the exception indeed occurred with the same EAD's.

**Comment by legolas** [comment]
Sorry, closed this issue a tad too soon, we still experience the timeout.
We still experience these timeouts, here's the last tested configuration:
```
        officeManager = LocalOfficeManager
                .builder()
                .portNumbers(2002, 2003, 2004, 2005)
                .taskExecutionTimeout(20*60*1000) // 20 minutes
                .maxTasksPerProcess(1) // Yes a single task
                .build()
                .install();
```
The conversion code:
```
         JodConverter
                .convert(inputPath.toFile())
                .to(outputPath.toFile())
                .execute();
```
Usually the exception occurs with the same EAD's, but once in a while I see other's passing by.
The ODT's created are pretty huge in the lines of 469 to 2404 pages.

**Comment by legolas** [comment]
It seemed the configuration was not picked up. A co-worker found this was in the wrong order.
We've changed it to:
```
officeManager = LocalOfficeManager
    .builder()
    .install()
    .portNumbers(AVAILABLE_PORTS)
    .taskExecutionTimeout(ONE_HOUR)
    .maxTasksPerProcess(MAXIMUM_TASKS_PER_PROCESS)
    .build();
```
Now my configuration is taken.

**Comment by sbraconnier** [comment]
Yes indeed. Your co-worker was right! Look at #80 for a full explanation.
