### ISSUE TITLE
jodconverter.org domain has expired

### ISSUE THREAD

**Issue by yhorndt** [sbraconnier/jodconverter#150]
Hi I don't know if you maintain the website, but as this is the repo where the link has been posted:

The http://www.jodconverter.org/ domain has expired:
This domain name expired on 2019-04-25 19:04:55
Click here to renew it.

**Comment by sbraconnier** [comment]
Thanks to you!! I don't understand, my account says it will expired on 2021-04-25. I'll look into this.

**Comment by is-simon** [comment]
I paid my bills :). Not cheap! I should add a "donation" option.

**Comment by sbraconnier** [comment]
I paid my bills :). Not cheap! I should add a "donation" option.
