### ISSUE TITLE
Converting to png

### ISSUE THREAD

**Issue by jDekx** [sbraconnier/jodconverter#153]
Hi. 
Found this link [Getting Started](https://github.com/sbraconnier/jodconverter/wiki/Getting-Started)
which tells that a Spreadsheet can be converted to a png format, among other input formats, but on a [Supported Formats](https://github.com/sbraconnier/jodconverter/wiki/Supported-Formats) page there is no information about outputting to a 'png', or any other image formats.

Is is possible to convert to an image format, such as png? 
Thanks.

**Comment by sbraconnier** [comment]
Sorry for the delay. Yes it is possible . I will update the wiki. Thanks.

[Here](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/document/DefaultDocumentFormatRegistry.java)'s the list of all supported formats.
