### ISSUE TITLE
Page selection on PDF only selects page 1

### ISSUE THREAD

**Issue by eangelcom** [sbraconnier/jodconverter#157]
I'm using jodconverter 4.2.2 on LibreOffice Vr 6.2.4.2 (x64) for Windows 10, and page selection only selects page 1 for any format that is not doc or docx:

`	
	

         public static void main(String[] args) {
		try {

			convert("/tmp/portable", "pdf");

		} catch (Exception e) {
			e.printStackTrace();
		}

	}
	
	private static void convert(String path, String ext) throws OfficeException {
		final LocalOfficeManager officeManager = LocalOfficeManager
				.builder().officeHome("/Program Files/LibreOffice")
				.install().build();
		try {
			
			officeManager.start();
			
			convertPage(path, ext, "1");
			convertPage(path, ext, "2");
			convertPage(path, ext, "3");
			
		} finally {
			OfficeUtils.stopQuietly(officeManager);
		}
				
	}
	
	private static void convertPage(String path, String ext, String pageRange) throws OfficeException {
		String fileName = path + "." + ext;
		
		final File inputFile = new File(fileName);

		final File outputFile = new File(path + pageRange+ ".png");
		
		Map<String, Object> filterData = new HashMap<>();
		filterData.put("PageRange", pageRange+"-"+pageRange);
		Map<String, Object> customProperties = new HashMap<>();
		customProperties.put("FilterData", filterData);
		
		LocalConverter.builder()
			.storeProperties(customProperties)
			.build()
			.convert(inputFile)
			.to(outputFile)
			.execute();		
	}
`
I tried PageRange as "2", "2-2", "1-2" and 2 (int), but the result is always page 1 instead of page 2.

**Comment by is-simon** [comment]
The PageRange property is specific to the pdf format, so it will only work when converting a file to pdf format. 

The library provides a [PageSelectorFilter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/filter/text/PageSelectorFilter.java) to select a page from a Text document. What exactly are the document formats you are working with ?

**Comment by sbraconnier** [comment]
The PageRange property is specific to the pdf format, so it will only work when converting a file to pdf format.

The library provides a PageSelectorFilter to select a page from a Text document. What exactly are the document formats you are working with ?

**Comment by eangelcom** [comment]
pdf

**Comment by demianortiz** [comment]
Actually we're trying to convert the first **3** slides/sheets/pages from PDF/PPT & XLS files to PNG without success... We're only getting one image of the first page using the PageSelectorFilter... Any clues?

**Comment by demianortiz** [comment]
@sbraconnier do we have any way to extract more than one PNG slide from PPT and PDF files when they have more than 1 page / slide?

**Comment by sbraconnier** [comment]
You can now use the PagesSelectorFilter to do that (from the `org.jodconverter.filter` package).

**Comment by eangelcom** [comment]
Hi, Simon. Thank you for your answer.

It still doesn't work for me.

Now I'm using 4.2.4 version and PagesSelectorFilter but it's still working only for doc type files.

This is my code. The first three pages are correctly generated for a doc in three different png files, but for a xls the first page is repeated three times.

`
           
		
		

          private static void previews() throws OfficeException {
               final File inputFile = new File("/tmp/excel.xls");
		final File outputFile1 = new File("/tmp/preview1.png");
		final PagesSelectorFilter selectorFilter1 = new PagesSelectorFilter(1);		
		convert(inputFile, outputFile1, selectorFilter1);
		
		final File outputFile2 = new File("/tmp/preview2.png");
		final PagesSelectorFilter selectorFilter2 = new PagesSelectorFilter(1,2);		
		convert(inputFile, outputFile2, selectorFilter2);
		
		final File outputFile3 = new File("/tmp/preview3.png");
		final PagesSelectorFilter selectorFilter3 = new PagesSelectorFilter(1,2,3);		
		convert(inputFile, outputFile3, selectorFilter3);
		
	}

	private static void convert(File inputFile, File outputFile, PagesSelectorFilter selectorFilter) throws OfficeException {
		LocalConverter
		  .builder()
		  .filterChain(selectorFilter)
		  .build()
		  .convert(inputFile)
		  .to(outputFile)
		  .execute();		
	}`

**Comment by sbraconnier** [comment]
Could you please attach a xls document here I could work with ? Maybe my document is not complex enough cause it's working on my end.

Thanks

**Comment by eangelcom** [comment]
[excel.zip](https://github.com/sbraconnier/jodconverter/files/4119220/excel.zip)
Sure. Thanks.

**Comment by sbraconnier** [comment]
Hmmm... not sure I understand what you are trying to do... When you are using the `PagesSelectorFilter ` with a xls document, a "page" is actually a "sheet". Since you only have 1 sheet, I suppose I didn't properly understand your need.

Could you please try to manually create the pdf you are expecting, and put back here the output pdf. I may also help if you could enumerate here the steps required to create this pdf .

**Comment by eangelcom** [comment]
ok, maybe an Excel is not divided into pages, but I also tried pdf and ppt with the same result. I attached the files I tested.
 
My goal is to generate the first three pages of a document as a preview like this:
Input file: powerpoint.ppt
Output files: 
preview1.png (with the first slide)
preview2.png (with the second slide)
preview3.png (with the third slide)

[testedfiles.zip](https://github.com/sbraconnier/jodconverter/files/4119336/testedfiles.zip)

**Comment by eangelcom** [comment]
For docs files is working as I expected (see attached input and output files)
[workingtest.zip](https://github.com/sbraconnier/jodconverter/files/4119345/workingtest.zip)

**Comment by sbraconnier** [comment]
Let's continue here #188
