### ISSUE TITLE
Specification of FilterData for controlling PDF output

### ISSUE THREAD

**Issue by barryspearce** [sbraconnier/jodconverter#160]
I need to control how images are converted into the resultant PDF. I am struggling to find what options need to be set to do this.

Where is the specification for the FilterData options for all of the PDF creation options in libreoffice?

**Comment by NABEEL-AHMED-JAMIL** [comment]
@sbraconnier is there any filter who remove all comment in pdf?
this is sample file that i convert from jodconverter

[sae_reporting_form_en.xlsx](https://github.com/sbraconnier/jodconverter/files/3955788/sae_reporting_form_en.xlsx)

[sae_reporting_form_en.pdf](https://github.com/sbraconnier/jodconverter/files/3955782/sae_reporting_form_en.pdf)
