### ISSUE TITLE
unidentifiable Chinese code

### ISSUE THREAD

**Issue by ruanzy** [sbraconnier/jodconverter#164]
env：
ubantu os
libreoffice6.2
jodconverter-local-4.2.0.jar

docx -> pdf
docx:  就卡死的卡萨丁sassaf112312
pdf: *********** sassaf112312   
unidentifiable Chinese code
？

**Comment by sbraconnier** [comment]
What is the behavior when you do the conversion without JODConverter (manually with LibreOffice).

**Comment by ruanzy** [comment]
manually with LibreOffice it's Ok

**Comment by ruanzy** [comment]
if I start process it's Ok
/opt/libreoffice6.2/program/soffice --headless --accept="socket,host=0.0.0.0,port=8100;urp;" --nofirststartwizard &


but
java program start
OfficeManager manager = LocalOfficeManager.builder().portNumbers(port)
				.officeHome(home).install().build();

manager.start();
...
 it's unidentifiable Chinese code

**Comment by sbraconnier** [comment]
Could you try using the [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) property?

Look [here](https://github.com/sbraconnier/jodconverter/issues/41#issuecomment-359625798) for an example on how to set this property.

**Comment by sbraconnier** [comment]
Closing this one since I hadn't hear from you. Fell free to reopen if required.
