### ISSUE TITLE
Issue while converting \" from word to pdf on weblogic server.

### ISSUE THREAD

**Issue by vinayMarathe** [sbraconnier/jodconverter#167]
![jodconversionissue](https://user-images.githubusercontent.com/53393249/64059901-88d1a980-cbe2-11e9-85fe-571df9a5872d.PNG)

I have highlighted the text where  \" is getting converted to 'o' and 'a' and this scenario is not occuring for all the inverted commas present in the document.Only for some of them.

Really not sure if this is some encoding issue or a bug. As this same conversion was working fine on Apache Tomcat server.

**Comment by vinayMarathe** [comment]
If this is an encoding issue is there any way to resolve bcz i stuck really badly at this. 
I tried setting encoding to UTF-8 i build properties of my project but still did not work.

**Comment by vinayMarathe** [comment]
> ![jodconversionissue](https://user-images.githubusercontent.com/53393249/64059901-88d1a980-cbe2-11e9-85fe-571df9a5872d.PNG)
> 
> I have highlighted the text where " is getting converted to 'o' and 'a' and this scenario is not occuring for all the inverted commas present in the document.Only for some of them.
> 
> Really not sure if this is some encoding issue or a bug. As this same conversion was working fine on Apache Tomcat server.

**Comment by sbraconnier** [comment]
Is it possible for you to attach a sample document I could work with to investigate this problem ?

**Comment by sbraconnier** [comment]
Closing this one since a workaround was found. Probably a LO/OO issue.
