### ISSUE TITLE
What do I need on server side to use the OnlineConverter?

### ISSUE THREAD

**Issue by axelrose** [sbraconnier/jodconverter#168]
Currently on client side I just do
```
OnlineOfficeManager officeManager = OnlineOfficeManager.
    builder().
    poolSize(5).
    urlConnection("http://127.0.0.1:7777/").
    taskExecutionTimeout(120000).
    taskQueueTimeout(120000).
    build();

    OnlineConverter onlineConverter = OnlineConverter.make(officeManager);
    onlineConverter.convert(in).to(out).as(DefaultDocumentFormatRegistry.PDF).execute();
```

And on server side I launch
```
/Applications/LibreOffice.app/Contents/MacOS/soffice \
--accept=socket,host=127.0.0.1,port=7777,tcpNoDelay=1;urp; --nodefault --nofirststartwizard --nolockcheck --nologo --norestore --headless
```

From logging output I can see that my client posts data to http://127.0.0.1:7777/lool/convert-to/pdf?sFilterName=calc_pdf_Export 
This results just in a timeout after some minutes.

What do I miss? Do I need some server suite or just different parameters?

Thanks for your advice,
Axel.

**Comment by sbraconnier** [comment]
In fact, the online module is intended to be used with [LibreOffice Online](https://github.com/sbraconnier/jodconverter/wiki/LibreOffice-Online).

But you can check [this](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) sample project that emulates a LibreOffice Online server.

A docker image of this project exists [here](https://github.com/EugenMayer/docker-image-jodconverter), thanks to a jodconverter user contribution.
