### ISSUE TITLE
when convert docx to html, is there a way to set image's src.like "/temp_123.jpg",set the prefix "/path/tep_123.jpg"

### ISSUE THREAD

**Issue by nwz5d** [sbraconnier/jodconverter#169]
when convert docx to html, is there a way to set image's src.like "/temp_123.jpg",set the prefix "/path/tep_123.jpg"

**Comment by sbraconnier** [comment]
Hmm.. I don't thing so. But there is a way to embed the image, if it would do the job ??

**Comment by sbraconnier** [comment]
Closing this one since I hadn't hear from you. Fell free to reopen if required.
