### ISSUE TITLE
How do i convert a partucular word document(docx) page to html?

### ISSUE THREAD

**Issue by diwakarbhatt123** [sbraconnier/jodconverter#17]
I was using jodconvertor for converting my word documents into an HTML document. However, i have a requirement to convert a particular page from docx into HTML. Can we do that? If so, is there any code sample you could show or any unit test case you could point me to.

**Comment by sbraconnier** [comment]
Yes you can.

If you are looking for an example using the v4.0.0 version, here it is:

```java
File inputFile = new File("document.docx");
File outputFile = new File("document.html");

// Create an office manager using the default configuration.
// The default port is 2002.
OfficeManager officeManager = new DefaultOfficeManagerBuilder().build();
try {

    // Start an office process and connect to the started instance (on port 2002).
    officeManager.start();

    // Convert
    OfficeDocumentConverter converter = new OfficeDocumentConverter(officeManager);
    converter.convert(inputFile, outputFile);
} finally {
    // Stop the office process
    officeManager.stop();
}
```

Let me know if you want to use the trunk (version 4.1.0, you will have to build the project yourself), the core module has changed quite a bit.

**Comment by javydreamercsw** [comment]
You might need to extract the desired page first. I doubt the converter has that granularity. This might get you started:

https://stackoverflow.com/questions/38047893/apache-poi-split-word-document-docx-to-pages

**Comment by sbraconnier** [comment]
Oh, I get it now. I misunderstood the question. Thanks @javydreamercsw

Let me think about it. I may have an idea using a custom [filter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/filter/Filter.java).

**Comment by diwakarbhatt123** [comment]
Hi, thank you for your replies. @javydreamercsw I can't use apache poi as it does not work with some complex documents(containing WordArt, shapes & stuff). @sbraconnier were you able to get that working. Thanks.

**Comment by sbraconnier** [comment]
Well, yes!!

That one was not an easy one. Not sure the solution will work for you. Since you are converting to HTML, the only way I got this working is by selecting the desired page, copying the selection, then selecting the whole document,  and finally pasting the previously copied page.

It worked in my unit test, but my sample document has only 3 pages without any complex content.

If you are working with the master branch, I just committed a new [PageSelectorFilter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/filter/text/PageSelectorFilter.java). To use it, just do (supposing you have an office manager installed, and that you want to convert only the second page of your document):

```java
File inputFile = new File("document.docx");
File outputFile = new File("document.html");

JODConverter
  .convert(inputFile)
  .filterWith(new PageSelectorFilter((short) 2), RefreshFilter.REFRESH)
  .to(outputFile)
  .execute();
```
If you are working with the 4.0.0 release, copy the PageSelectorFilter in you project and use it this way:

```java
OfficeDocumentConverter converter = ...

File inputFile = new File("document.docx");
File outputFile = new File("document.html");

FilterChain filterChain = new DefaultFilterChain(new PageSelectorFilter((short) 2), RefreshFilter.INSTANCE);

// Convert
converter.convert(filterChain, inputFile, outputFile);
```

Hope this helps!

**Comment by sbraconnier** [comment]
Note that if your target document format was PDF, it would have been way easier:

```java
File inputFile = new File("document.docx");
File outputFile = new File("document.pdf");

Map<String, Object> filterData = new HashMap<>();
filterData.put("PageRange", "2");
Map<String, Object> customProperties = new HashMap<>();
customProperties.put("FilterData", filterData);

JODConverter
  .convert(inputFile)
  .to(outputFile)
  .storeWithProperties(customProperties)
  .execute();
```

**Comment by javydreamercsw** [comment]
Both examples above are worthy of being on readme and/or wiki.

**Comment by sbraconnier** [comment]
You are totally right @javydreamercsw. I plan to improve the documentation before releasing the 4.1.0 version.

**Comment by diwakarbhatt123** [comment]
@sbraconnier Really really thank you for implementing this.I've tested this on different documents and worked perfectly on all of them. Thank you again for this. Also, there's one more thing, I'm sorry if I'm nagging you too much about it. Just wanted to know if there's a way to identify the number of pages in a document file. Thanks.

**Comment by sbraconnier** [comment]
That one was easier :smile:

I committed a [PageCounterFilter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/filter/text/PageCounterFilter.java) that will count the number of pages of a document, according to its position in the filter chain.

Supposing a source document with 3 pages, both following examples would print 3, then 1.

4.1.0:
```java
File inputFile = new File("document.docx");
File outputFile = new File("document.html");

PageCounterFilter pageCounterFilter1 = new PageCounterFilter();
PageSelectorFilter pageSelectorFilter = new PageSelectorFilter((short) 2);
PageCounterFilter pageCounterFilter2 = new PageCounterFilter();

JODConverter
  .convert(inputFile)
  .filterWith(pageCounterFilter1, pageSelectorFilter, pageCounterFilter2, RefreshFilter.REFRESH)
  .to(outputFile)
  .execute();

System.out.println(pageCounterFilter1.getPageCount());
System.out.println(pageCounterFilter2.getPageCount());
```

4.0.0:
```java
OfficeDocumentConverter converter = ...

File inputFile = new File("document.docx");
File outputFile = new File("document.html");

PageCounterFilter pageCounterFilter1 = new PageCounterFilter();
PageSelectorFilter pageSelectorFilter = new PageSelectorFilter((short) 2);
PageCounterFilter pageCounterFilter2 = new PageCounterFilter();

FilterChain filterChain = new DefaultFilterChain(pageCounterFilter1, pageSelectorFilter, pageCounterFilter2, RefreshFilter.REFRESH);

converter.convert(filterChain, inputFile, outputFile);

System.out.println(pageCounterFilter1.getPageCount());
System.out.println(pageCounterFilter2.getPageCount());
```

Note that my previous version of [PageSelectorFilter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/java/org/jodconverter/filter/text/PageSelectorFilter.java) was broken. An important line of code was missing, the one calling the next filter in the chain. It is fixed now.

**Comment by sbraconnier** [comment]
No news good news! I'm closing this one...

**Comment by diwakarbhatt123** [comment]
Hey sorry was out for a while. Thank you very much for this. 😄
