### ISSUE TITLE
Set file encode in request. CSV to PDF/XLS conversion

### ISSUE THREAD

**Issue by t-dias** [sbraconnier/jodconverter#170]
Hello,
I'm trying to use the rest api to convert csv files to pdf but the encoding is wrong and the file returned contains some "unreadable" characters.
My file encoding is UTF-8.
File returned with ISO-8859-1.

It's possible to set the file encoding in the request?

Thanks

**Comment by sbraconnier** [comment]
Sorry for the delay. I was very buzy. Do you still need this ?? If so, please explain with more details your problem exactly. You said that you were using the "Rest API"? The one from Collabora Online ? Or the one provided in the sample projects ?

**Comment by ghaege** [comment]
This seems to be a general problem with all text files (.txt, .json, .csv, ..) LibreOffice-Converter 'cannot determine' the source encoding.
Although opening theses files in LibreOffice directly and convert them to pdf works as well for UTF encoded source files.

**Comment by sbraconnier** [comment]
@ghaege When not using a REST API, you can specify the source encoding like so (if your source file is utf16 encoded):

```java
final File input = new File("input.txt");
final File output = new File("output.pdf");

final DocumentFormat format =
    DocumentFormat.builder()
        .from(DefaultDocumentFormatRegistry.TXT)
        .loadProperty("FilterOptions", "utf16")
        .build();
JodConverter.convert(input).as(format).to(output).execute();
```

As for the original problem, I'll close the issue since I didn't have any feedback for a long time now. Feel free to re-open if needed.
