### ISSUE TITLE
Allow process restart to be asynchronous

### ISSUE THREAD

**Issue by ryanrupp** [sbraconnier/jodconverter#171]
Hi, thanks for the library. I was running some performance tests of a simple 2 page DOCX converting to a PDF and just running it through single threaded iterations. The conversion would take under 200ms until about 130-140 conversions and then the performance would degrade to 4-10x as slow. I don't know the history behind the max conversions setting (memory leak safeguard in office that causes it to get slow after time?) but I think I'm hitting the issue described here - https://github.com/sbraconnier/jodconverter/issues/124 - as once the process auto-restarts at 200 conversion (default setting) then it goes back to normal.

I want to change the max executions to something lower like 50 or 100 executions as suggested in the linked issue but my main concern there is that it looks like the restart when it hits max takes place lazily (so upon the next conversion actually being executed). So then this makes it so that those interval executions incur ~3-4 seconds overhead. Code here - https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/office/OfficeProcessManagerPoolEntry.java#L136

Feature request here is to allow this to optionally be done asynchronously after a conversion e.g. if max=50 and the pool entry is at 49 conversions and a conversion is done that makes it hit 50, then take that entry out of service immediately and restart it in another thread so callers never incur this cost.

**Comment by ryanrupp** [comment]
I could maybe submit a PR for this, I just logged the issue to make sure 1) this makes sense 2) there's not something already in place.

I was thinking the code would exist in `doExecute` still it would just happen as a post step and would need to have another thread/thread pool to submit the work then to to restart it.

**Comment by ryanrupp** [comment]
Hrm actually that issue I'm running into appears to:
1) Only happen on OSX, when I run things on Linux in containers I cannot reproduce, something going on with OSX LibreOffice
2) Doesn't necessarily appear to be associated with number of executions rather it's time oriented e.g. if I do my test with a 1 second sleep between conversions I can do about 23 conversions at 200ms per conversion until it starts suddenly taking 500-600ms. Can take this further and sleep for 5 seconds and see the slowdown after 5 iterations so something ~25 seconds in.

This still would be a nice feature though to improve responsiveness.

**Comment by sbraconnier** [comment]
Sorry for the delay. I was working on a project that took all my work and free time.

The way JODConverter deals with Office instances is based on ideas from another era!! It would be nice to rethink some ideas but it's not an easy task to do, and we still have to support old LibreOffice/OpenOffice versions.

I'm open to any suggestion/idea you may have. I'll let this issue open until I had time to work on this. But I doubt I'll have time to do something fir the next version. I plan to release a version in the next month.

**Comment by sbraconnier** [comment]
Closed by #200
