### ISSUE TITLE
An office manager must implements the TemporaryFileMaker interface in order to be able to convert InputStream

### ISSUE THREAD

**Issue by ragnar-lothbrok** [sbraconnier/jodconverter#174]
When I am trying to convert Xlsx to odt I am getting above error.

ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

        final DocumentConverter converter =
                LocalConverter.builder()
                        .officeManager(officeManager)
                        .build();

        final DocumentFormat sourceFormat = DefaultDocumentFormatRegistry.getFormatByExtension(
                FilenameUtils.getExtension(inputFileName));

        // Convert...
        converter.convert(inputFile)
                .as(sourceFormat)
                .to(outputStream)
                .as(targetFormat)
                .execute();

**Comment by sbraconnier** [comment]
Sorry for the delay. I was working on a project that took all my free time.

Which office manager are you using ??

Maybe related to #130, which is fixed. I'll release a new JODConverter version in the next month.
