### ISSUE TITLE
Converting (merging) multiple files into one - feature

### ISSUE THREAD

**Issue by BrooksEarl** [sbraconnier/jodconverter#175]
**Summary**
It could be optional merging feature woven into the conversion process. We need to provide list with files to merge and iterating over that list in LocalConversionTask#execute.
Unfortunately I don't see possibility to do it using online converter.

**Basic example**
It could be look like
`JodConverter
	.convert(sourceFile)
        .append(additionalFile, documentFormat)
        .to(target)
	.execute();`

If you are intereseted i can create pull request with my solution

**Comment by sbraconnier** [comment]
Sorry for the delay. I was working on a project that took all my free time.

Please take a look at #45 and see if it could be enough for you. If not, you are more than welcome to submit a PR for this with your idea!!

**Comment by NABEEL-AHMED-JAMIL** [comment]
Hi @BrooksEarl  and @sbraconnier i did with this way hope you like after all file converter with pdf
   type i get the list of pdf stream and marge and set into the ByteArrayOutputStream 
    

```
private void margeFile(List<InputStream> inputStreams, ByteArrayOutputStream outputStream) throws IOException {
        PDFMergerUtility ut = new PDFMergerUtility();
        ut.addSources(inputStreams);
        ut.setDestinationStream(outputStream);
        ut.mergeDocuments(MemoryUsageSetting.setupMainMemoryOnly());
    }

  <dependency>
	 <groupId>org.apache.pdfbox</groupId>
	<artifactId>pdfbox</artifactId>
	<version>2.0.1</version>
  </dependency>
```

**Comment by sbraconnier** [comment]
Thanks @NABEEL-AHMED-JAMIL  for your help!!
