### ISSUE TITLE
Issues in java11 project

### ISSUE THREAD

**Issue by solomax** [sbraconnier/jodconverter#178]
First of all thanks a lot this library is alive :)
We are using it since forever, and it works as expected :))

Recently I have started to add module-info to our master branch
This uncovers multiple issues
1) this library doesn't have Automatic-Module-Name in its manifest
2) multiple modules(jars) has same packages
     org.jodconverter
     org.jodconverter.office

Could you please fix it?

Unfortunately I'm not familiar with gradle, so I'm unable to provide PR for 1) above :((

**Comment by sbraconnier** [comment]
Hi there! Sorry for the delay.

Could you be more specific about the problem? I'm afraid I'm not sure I understand properly. The project build properly on Java 11 to 13. But I didn't use the jars as you did in real life.

Maybe you could provide some links so I could educate myself :). Thanks.

**Comment by solomax** [comment]
Hello @sbraconnier 
Thanks for reply :)

here is the dumb Java11 project https://github.com/solomax/java11-test (it does nothing actually) which fail to build :(

Steps to reproduce:

1. `git checkout ...`
2. `mvn clean install`

What need to be done:

1. add `Automatic-Module-Name` to manifest
2. ensure each jar (module) uses unique packages/classes

Please let me know if you have any questions or if I can help somehow :)

**Comment by sbraconnier** [comment]
Thanks!

I'm currently working on another issue I want to be fixed for the next release. One the release is done, I'll work on this one. It will probably be a major release since it will introduce breaking changes (package rename). But it will be for the better, I don't like the fact that multiple jars share some package names.

**Comment by solomax** [comment]
Great, thanks for the update
I can help with testing :)

**Comment by sbraconnier** [comment]
@solomax Is it possible for you to try the 4.3.0-SNAPSHOT version available in the OSS snapshots repository:

https://oss.sonatype.org/content/repositories/snapshots

Thanks a lot!

**Comment by solomax** [comment]
Hello @sbraconnier 
sorry for delay
just have checked the build with  `4.3.0-SNAPSHOT` 
everything related to jodconverter is green

Thanks a lot!
