### ISSUE TITLE
if inputFile has no content, then it throw exception  

### ISSUE THREAD

**Issue by ruanzy** [sbraconnier/jodconverter#179]
File inputFile = new File("document.doc");
File outputFile = new File("document.pdf");
final LocalOfficeManager officeManager = LocalOfficeManager.install(); 
    officeManager.start();
    JodConverter
             .convert(inputFile)
             .to(outputFile)
             .execute();

if inputFile has no content, then it throw exception  
libreoffice could not open document:tempfile

**Comment by sbraconnier** [comment]
Do you mean that the inputFile is empty ? Or you mean that it does not exist ?

**Comment by sbraconnier** [comment]
Since I have no news about this issue, I'll close it. Feel free to reopen it with more details.
