### ISSUE TITLE
Create a logo for the JODConverter project.

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#18]
I would like to create a logo for this project but have no talent for this kind of thing. Anybody wants to be in the credits section for this ??

**Comment by javydreamercsw** [comment]
I'm on the same boat. I usually got to Fiverr and can get a really good one cheap.

**Comment by sbraconnier** [comment]
Thanks for the tips, I'll take a look!

**Comment by javydreamercsw** [comment]
$5 can go a long way in there.

**Comment by sbraconnier** [comment]
I just ordered one this morning. We'll see what will come out of this!! Thanks again for the tip!
