### ISSUE TITLE
Unthrown MalformedInputException when looking for soffice PID

### ISSUE THREAD

**Issue by RHarryH** [sbraconnier/jodconverter#180]
`soffice.exe`, when run, creates instance of `soffice.bin` with additional parameter `-env:OOO_CWD` with path to the directory where application using jodconverter is located (working directory)

If this path contains language specific characters like `ą` then `run()` method from `StreamPumper` throws `java.nio.charset.MalformedInputException: Input length = 1` exception, which is not logged or rethrown because of empty catch.

I reproduced the issue by adding `TEST` environment variable with `bączek` word and calling `AbstractProcessManager.execute(String[] cmdarray)` method with following input `new String[]{"cmd","/c","echo %TEST%"}`.

Platfororm is Windows 10. I let the library to choose `ProcessManager`. Workaround is to define `PureJavaProcessManager` during `OfficeManager` building.

Another solution (which requires changes in code) is to use regular `InputStreamReader` instead of `Channels.newReader(Channels.newChannel(...))` or give the ability to change the charset (`ISO-8859-1` seems to fix the problem).

**Comment by sbraconnier** [comment]
Nice catch. I'll fix this in the next release.
