### ISSUE TITLE
regression: Upgrade to jodconverter-local 4.2.3 imply to also add a dependency to jodconverter-core

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#183]
I just upgraded jodconverter-local on XWiki to 4.2.3 and I got some builds issues because of class not found: after investigation it's because jodconverter-core is no longer retrieved. When adding explicitely the dependency it's working well. 

I guess it's related with https://github.com/sbraconnier/jodconverter/commit/a1a5809c1535183dcc1723db8317e68fec52cd9a#diff-442861bd065d1a83bdf0bf7cbf606f95R6

**Comment by sbraconnier** [comment]
It was not supposed to be. Maybe I misunderstood the gradle [api](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation) dependency. jodconverter-core is supposed to be exposed from jodconverter-local.

I'll fix that today.

**Comment by sbraconnier** [comment]
Could you please try the 4.2.4-SNAPSHOT please ??

I don't want to publish another faulty release!! Thank for reporting this by the way 👍

**Comment by surli** [comment]
> Could you please try the 4.2.4-SNAPSHOT please ??

I will try.

FTR our build is currently failing with: 
> Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find org.jodconverter:jodconverter-local:pom:4.2.3 in http://nexus.xwiki.org/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-releases has elapsed or updates are forced

our nexus is connected to central so we should have it, and locally I got the warning:
> [WARNING] The POM for org.jodconverter:jodconverter-local:jar:4.2.3 is missing, no dependency information available

Not sure what's wrong though, since I can see the pom in https://search.maven.org/remotecontent?filepath=org/jodconverter/jodconverter-local/4.2.3/jodconverter-local-4.2.3.pom

**Comment by sbraconnier** [comment]
Hmm... I use the deprecated 'maven' plugin to publish my artifacts. I got a "warning" about missing "repository id"  when I released the version. I never saw that before. Not sure why and what the consequences are...

Maybe I'll have to rework my publishing todos list to fix this!

**Comment by surli** [comment]
> > Could you please try the 4.2.4-SNAPSHOT please ??

> I will try.

So I just rebuilt locally jodconverter with `./gradlew install`, remove the dependency to jodconverter-core on XWiki and bump the jodconverter version to 4.2.4-SNAPSHOT and it appears to build properly on my machine. 
So at least the first regression seems fixed :)

**Comment by sbraconnier** [comment]
Great! Thanks!

I'll publish the version today. Sorry for that!

**Comment by surli** [comment]
No problem :)

**Comment by sbraconnier** [comment]
Fix by #09b2751299ea8440e27c41a2db422ffc194777fc

**Comment by sbraconnier** [comment]
Fixed by 09b2751299ea8440e27c41a2db422ffc194777fc
