### ISSUE TITLE
duplicate open office exe spun up for spring web app running on tomcat

### ISSUE THREAD

**Issue by jheidlage1222** [sbraconnier/jodconverter#187]
Not sure if this is a bug or I just missed something in the documentation but whenever I start my web app it creates two open office exes but I'm only expecting the one exe.

**Comment by sbraconnier** [comment]
Could you please provide more information. Are you on Windows ? What is your JodConverter configuration? Do you have a printscreen or something ?

Thanks.

**Comment by jheidlage1222** [comment]
![image](https://user-images.githubusercontent.com/23411611/73269754-65b81f80-41ab-11ea-9e0a-d351dd336d81.png)

Yes I'm on windows and this is my setup.  tempPort is 2002 and maxTasksPerProcess is 450.

**Comment by sbraconnier** [comment]
Could you please take a snapshot of your process manager that shows the command line arguments.

Example:
![Process explorer](https://user-images.githubusercontent.com/15372565/73280623-ce5bc800-41bc-11ea-9621-710249fe5607.PNG)

**Comment by jheidlage1222** [comment]
![image](https://user-images.githubusercontent.com/23411611/73281236-a6209900-41bd-11ea-9ffb-463e626d11d8.png)

**Comment by sbraconnier** [comment]
Hmm... And you said that tempPort is 2002 ??

You have 2 processes here listening on port 26789 and 36542... That doesn't ring a bell?? JODConverter does not randomly start office processes without being instructed to do so... And since these are not the default port, you must have manually set them.

**Comment by jheidlage1222** [comment]
Here's my source file, I forgot that I added in a little extra logic to try and find an open port before connecting.  
`
public class PDFConverterServiceImpl implements PDFConverterService {

	// private TalLogger logger = TalLoggerFactory.getLogger(this.getClass());
	private Logger logger = LoggerFactory.getLogger(PDFConverterServiceImpl.class);

	private static String RTF_FORMAT = ".rtf";
	private static List<String> supportedFormat = new ArrayList<String>();
	private static OfficeManager officeManager = null;
	private static LocalConverter converter = null;

	//private static final int officeMgrPort = 26789;
	//FIXME: These need to be moved to external props file.
	private static final int maxTasksPerProcess = 400;
	private static int[] officeMgrPorts = new int[] { 26789, 36542, 10245, 11232, 5000 };

	static {

		supportedFormat.add(RTF_FORMAT);

		try {
			System.out.println("###Office Mgr/Converter Starting up####");
			for (int tempPort : officeMgrPorts) {
				if (isTcpPortAvailable(tempPort)) {
					officeManager = LocalOfficeManager.builder().portNumbers(tempPort)
							.maxTasksPerProcess(maxTasksPerProcess).build();
					officeManager.start();
					converter = LocalConverter.make(officeManager);
					System.out.println("###Office Mgr/Converter Initialized####");
					break;
				}
				if(tempPort == officeMgrPorts[officeMgrPorts.length - 1]){
					throw new Exception("Could not find available port(s).");
				}
			}

		} catch (Exception e) {
			System.err.println(
					"#### JODCONVERTER OFFICE MANAGER FAILED TO START.  PLEASE CONTACT HELP DESK SUPPORT FOR ASSISTANCE ####");
			e.printStackTrace();
			System.exit(1);
		}
	}

	public boolean convertInToPDF(String srcFile, String destFile, int attempt) throws TalException {

		logger.info("Going to convert pdf of file " + srcFile + " in attempt " + attempt);
		// OfficeManager officeManager = null;

		try {
			logger.info("###Executing RTF to PDF conversion...");
			// TODO: Refactor to use a stream.
			converter.convert(new File(srcFile)).to(new File(destFile)).execute();
			logger.info("Pdf conversion to file " + srcFile + " is completed successfully in attempt " + attempt);

		} catch (Throwable ex) {
			// logger.error(ex, "###RUH ROH: Caught throwable during conversion####");
			logger.error("###JODCONVERTER ERROR###", ex);
			if (ex instanceof TalException) {
				throw (TalException) ex;
			}
			throw new TalException("Exception in PDFconversion of file " + srcFile + " :" + ex.getMessage());
		}
		return true;
	}

	public static void main(String args[]) throws TalException {
		PDFConverterServiceImpl serv11 = new PDFConverterServiceImpl();
		String folder = "C:\\correspondence\\letters\\";
		File fileFolder = new File(folder);
		File[] listOfFiles = fileFolder.listFiles();

		for (int i = 0; i < listOfFiles.length; i++) {
			String fileName = listOfFiles[i].getName();
			String filePath = folder + fileName;
			if (fileName.indexOf(".rtf") >= 0) {
				String destFile = folder + fileName.substring(0, fileName.indexOf(".")) + ".pdf";
				serv11.convertInToPDF(filePath, destFile, 1);
			}
		}
	}

	public static boolean isTcpPortAvailable(int port) {
		ServerSocket serverSocket = null;
		boolean isAvailable = false;
		// try (ServerSocket serverSocket = new ServerSocket()) {
		try {
			serverSocket = new ServerSocket();
			// setReuseAddress(false) is required only on OSX,
			// otherwise the code will not work correctly on that platform
			serverSocket.setReuseAddress(false);
			serverSocket.bind(new InetSocketAddress(InetAddress.getByName("localhost"), port), 1);
			isAvailable = true;
			// return true;
		} catch (Exception ex) {

			isAvailable = false;
		} finally {
			if (serverSocket != null && !serverSocket.isClosed()) {
				try {
					serverSocket.close();
				} catch (IOException e) {
					// If we hit this exception it means the port is taken (I think. Java 6 is
					// weird.)
				}
				serverSocket = null;
			}
		}
		return isAvailable;
	}

	@PreDestroy
	public void destroy() {
		
		try {
			logger.info("### Stopping Office Manager ###");
			officeManager.stop();
			officeManager = null;
			logger.info("### Office Manager stopped  ###");
		} catch (Exception e) {
			// TODO: handle exception
			// this.logger.error(e, "###Error stopping office manager###");
			this.logger.error("### Exception On PDFConverterServiceImpl OODC teardown failure ###", e);
		}
	}

}

`

**Comment by sbraconnier** [comment]
Ok then. Clearly the problem is not related to JODConverter itself. Have you tried using a breakpoint to check if the 'static' block is executed twice for some reason... Or maybe you killed a debugging session, leaving a running process behind... Have you tried to stop your application, manually kill all remaining office processes, and then restart the application ?

**Comment by jheidlage1222** [comment]
Yes I've tried that but no joy.  I also moved my init logic out of the static block and under a PreConstruct annotation function and I confirmed it's only being called once.

**Comment by sbraconnier** [comment]
Well... not sure if the code you pasted is what you have in production, but your destroy method is never called. So, the office process will never be closed. Just add:

`serv11.destroy();`

At the end of your main method. It will close the running office process.

**Comment by jheidlage1222** [comment]
Sorry, that main function is a duplicate, it's not what actually gets invoked.  My destroy method gets called by the JSF framework when the application is stopped and I've confirmed this from logs.

**Comment by sbraconnier** [comment]
Since I'm unable to reproduce the anomaly using the source code you provided, the problem must be somewhere else in your program/installation. Maybe you have 2 war in your tomcat webapp directory? 2 Tomcat instances maybe ??

In order to be able to help you, I'll need a sample project I could work with to reproduce the issue.

**Comment by sbraconnier** [comment]
Feel free to re-open if I didn't answer properly.
