### ISSUE TITLE
PagesSelectorFilter only works for doc files

### ISSUE THREAD

**Issue by eangelcom** [sbraconnier/jodconverter#188]
I'm using 4.2.4 version and PagesSelectorFilter but it doesn't work for not doc type files.

This is my code. The first three pages are correctly generated for a doc in three different png files, but for a xls the first page is repeated three times.

`

      private static void previews() throws OfficeException {
           final File inputFile = new File("/tmp/excel.xls");
	final File outputFile1 = new File("/tmp/preview1.png");
	final PagesSelectorFilter selectorFilter1 = new PagesSelectorFilter(1);		
	convert(inputFile, outputFile1, selectorFilter1);
	
	final File outputFile2 = new File("/tmp/preview2.png");
	final PagesSelectorFilter selectorFilter2 = new PagesSelectorFilter(1,2);		
	convert(inputFile, outputFile2, selectorFilter2);
	
	final File outputFile3 = new File("/tmp/preview3.png");
	final PagesSelectorFilter selectorFilter3 = new PagesSelectorFilter(1,2,3);		
	convert(inputFile, outputFile3, selectorFilter3);
	
}

private static void convert(File inputFile, File outputFile, PagesSelectorFilter selectorFilter) throws OfficeException {
	LocalConverter
	  .builder()
	  .filterChain(selectorFilter)
	  .build()
	  .convert(inputFile)
	  .to(outputFile)
	  .execute();		
}`

**Comment by sbraconnier** [comment]
I don't think that the problem is the input format. 

I tried to convert the samples you provided with #157 and it works as expected when converting to PDF format:

```java
      LocalConverter converter = LocalConverter
              .builder()
              .filterChain(new PagesSelectorFilter(1,2,3))
              .build();

      File source = new File("/tmp/portable.pdf");
      File target = new File("/tmp/portable.out.pdf");
      converter.convert(source).to(target).execute();

      source = new File("/tmp/powerpoint.ppt");
      target = new File("/tmp/powerpoint.out.pdf");
      converter.convert(source).to(target).execute();
```

But when trying to convert to PNG, only the first page is created, which is normal (a PNG is not paged).

Try this instead:

```java
      for (int i = 1; i <= 3; i++) {

        LocalConverter converter = LocalConverter
                .builder()
                .filterChain(new PagesSelectorFilter(i))
                .build();

        File source = new File("/tmp/portable.pdf");
        File target = new File("/tmp/portable-preview-" + i + ".png");
        converter.convert(source).to(target).execute();

        source = new File("/tmp/powerpoint.ppt");
        target = new File("/tmp/powerpoint-preview-" + i + ".png");
        converter.convert(source).to(target).execute();
      }
```

**Comment by eangelcom** [comment]
I just tried that and It looks like it worked. Thank you very much, Simon.

**Comment by sbraconnier** [comment]
Glad to hear that :)
