### ISSUE TITLE
Permission denied.  dconf will not work properly

### ISSUE THREAD

**Issue by eangelcom** [sbraconnier/jodconverter#189]
Hello.

I'm using jodconverter vr 4.2.4 and is working on Windows 10, but when I run it on Linux I'm getting this error: 

_o.jodconverter.office.VerboseProcess - (process:130320): dconf-CRITICAL **: unable to create directory '/usr/share/tomcat8/.cache/dconf': Permission denied.  dconf will not work properly._

That folder is only for root user and I'm running jodconverter from a web app in a Tomcat container.

Do I have, maybe, any misconfiguration?

Thanks.

**Comment by sbraconnier** [comment]
Could you please paste here the source code where you create the `LocalOfficeManager` please ?

**Comment by eangelcom** [comment]
`        officeManager =
                LocalOfficeManager.builder()
                        .processTimeout(PROCESS_TIMEOUT)
                        .taskExecutionTimeout(TASK_EXECUTION_TIMEOUT)
                        .install()
                        .build();`

**Comment by sbraconnier** [comment]
Try:

```java
officeManager =
                LocalOfficeManager.builder()
                        .runAsArgs("sudo")
                        .processTimeout(PROCESS_TIMEOUT)
                        .taskExecutionTimeout(TASK_EXECUTION_TIMEOUT)
                        .install()
                        .build();
```

**Comment by eangelcom** [comment]
Now it says:

ERROR o.jodconverter.office.VerboseProcess - sudo: no tty present and no askpass program specified

**Comment by sbraconnier** [comment]
Do you know the root password ?? Can you login as root on the server to edit  the sudoers file ?

**Comment by eangelcom** [comment]
No, I don't. I asked DevOps guys and we, developers, are not allowed to access that folder.

**Comment by eangelcom** [comment]
Additionally, I found that the problem is not Windows/Linux but Tomcat.  The same source code works outside Tomcat but not inside Tomcat no matter if OS is Windows or Linux.

**Comment by sbraconnier** [comment]
JODConverter depends on commons-io 2.6.

You must have at least commons-io 2.3+ in order to have the `IOUtils.toString(InputStream input, Charset encoding)` signature.

Check your classpath and remove or update your commons-io 2.2 (or older) dependency.

**Comment by eangelcom** [comment]
It worked with commons-io 2.5. Thank you very much.
