### ISSUE TITLE
Use ExternalOfficeManager with a pool of processes

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#191]
Hi,

just to know: is there anything that prevents ExternalOfficeManager to handle a pool of office process? The API of jodconverter doesn't allow it right now, but is it a matter of time to add it, or is there some technical constraint for that? 

Or maybe the goal is to discard ExternalOfficeManager to only provide OnlineOfficeManager at a point? 

I'm asking just to have an idea of the direction the API since I'm working on using the pool feature for internal process and we already manage external process (but not yet Online Office).

**Comment by sbraconnier** [comment]
Hmm... I don't see why it would not be possible.

May I ask how you manage external processes ??

**Comment by sbraconnier** [comment]
This will be included in the next version.

**Comment by surli** [comment]
> May I ask how you manage external processes ??

Sorry for not having answered this back then. We have some documentation for launching manually an office process on a machine, so that we can then attach to it: https://extensions.xwiki.org/xwiki/bin/view/Extension/Office%20Importer%20Application#HExternallymanaged28local29OpenOfficeserverprocess

Quite frankly I never used it myself, but I know our adminsys has set up some external instances of office for some of our instances.
