### ISSUE TITLE
Pdf/PPT to docx conversion

### ISSUE THREAD

**Issue by interviewBubble** [sbraconnier/jodconverter#193]
Is it possible to convert pdf and ppt files into docx using jod convertor?

i am able to convert doc to docx but i am not getting idea about pdf2docx.

**Comment by sbraconnier** [comment]
Hello there.

Are you able to do it using LibreOffice, without JODConverter ??  If yes, then you should be able to do it with JODConverter.

**Comment by is-simon** [comment]
Feel free to re-open if I didn't answer properly.

**Comment by sbraconnier** [comment]
Feel free to re-open if I didn't answer properly.

**Comment by jjlyt2** [comment]
PDF to doc or docx
soffice --infilter="writer_pdf_import" --convert-to doc NOW.pdf --outdir fff
JODConverter nable to convert PDF to doc
