### ISSUE TITLE
can't set templateProfileDir

### ISSUE THREAD

**Issue by Dream2Land** [sbraconnier/jodconverter#197]
when i set templateProfileDir with myself dir,it's reports could't found user profile.but default value is /tmp,which is not suitable

**Comment by sbraconnier** [comment]
Maybe you are mixing [workingDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_folderworkingdir) and [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) ??

**Comment by Larry-Arun** [comment]
I have the same quetions.
java.lang.IllegalStateException: templateProfileDir doesn't appear to contain a user profile: /tmp/libreoffice/templateprofile
        at org.artofsolving.jodconverter.office.DefaultOfficeManagerConfiguration.buildOfficeManager(DefaultOfficeManagerConfiguration.java:164)

**Comment by sbraconnier** [comment]
Closing this one. Feel free to re-open if needed.
