### ISSUE TITLE
JoDConverterBean: How to add filter

### ISSUE THREAD

**Issue by riteshbhambhani** [sbraconnier/jodconverter#201]
I want to convert a RTF to HTML and use the JodConverterBean for the same. It does take the port numbers but there is no setter for the filters. Is there a way I can add filters to it.

**Comment by sbraconnier** [comment]
Well, there is no way to do that right now. I'll fix this for the next release. In the meantime, you could create your own bean. It is really a tiny class, so it is not that much work to do so...

Take a look at [JodConverterBean.java](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-spring/src/main/java/org/jodconverter/spring/JodConverterBean.java)

**Comment by sbraconnier** [comment]
You will now be able to do:

```java
LocalConverter.builder()
    .officeManager(bean.getManager())
    .filterChain(...)
    .build()
    .convert(inputFileTxt)
    .to(outputFile)
    .execute();
```
