### ISSUE TITLE
I have an issue when I try to convert MS 97-2003 .DOC file to PDF

### ISSUE THREAD

**Issue by dnikolov9005** [sbraconnier/jodconverter#202]
Apache_OpenOffice-SDK_4.1.7_Win_x86_install_en-US.exe
LibreOffice_6.4.3_Win_x64_sdk
commons-io-2.6.jar
commons-lang3-3.4.jar
gson-2.8.5.jar
jodconverter-core-4.2.2.jar
jodconverter-local-4.2.2.jar
juh-5.2.0.jar
jurt-5.2.0.jar
ridl-5.2.0.jar
slf4j-api-2.0.0-alpha1.jar
unoil-5.2.0.jar

and the stack trace:

> 
> Exception in thread "main" java.lang.VerifyError: Stack map does not match the one at exception handler 103
> Exception Details:
>   Location:
>     org/jodconverter/task/AbstractLocalOfficeTask.loadDocument(Lorg/jodconverter/office/LocalOfficeContext;Ljava/io/File;)Lcom/sun/star/lang/XComponent; @103: astore_3
>   Reason:
>     Type 'com/sun/star/lang/IllegalArgumentException' (current frame, stack[0]) is not assignable to 'com/sun/star/uno/Exception' (stack map, stack[0])
>   Current Frame:
>     bci: @0
>     flags: { }
>     locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
>     stack: { 'com/sun/star/lang/IllegalArgumentException' }
>   Stackmap Frame:
>     bci: @103
>     flags: { }
>     locals: { 'org/jodconverter/task/AbstractLocalOfficeTask', 'org/jodconverter/office/LocalOfficeContext', 'java/io/File' }
>     stack: { 'com/sun/star/uno/Exception' }
>   Bytecode:
>     0x0000000: 2bb9 0010 0100 2cb8 0011 1212 032a b600
>     0x0000010: 13b8 0014 b900 1505 004e 2dbb 0016 59b7
>     0x0000020: 0017 1219 b600 1a2c b600 1bb6 001a b600
>     0x0000030: 1c03 bd00 1db8 001e 572d b04e bb00 2059
>     0x0000040: bb00 1659 b700 1712 19b6 001a 2cb6 001b
>     0x0000050: b600 1a12 21b6 001a 2db4 0022 b600 23b6
>     0x0000060: 001c 2db7 0024 bf4e bb00 2059 bb00 1659
>     0x0000070: b700 1712 19b6 001a 2cb6 001b b600 1ab6
>     0x0000080: 001c 2db7 0024 bf                      
>   Exception Handler Table:
>     bci [0, 58] => handler: 59
>     bci [0, 58] => handler: 103
>     bci [0, 58] => handler: 103
>   Stackmap Table:
>     same_locals_1_stack_item_frame(@59,Object[#88])
>     same_locals_1_stack_item_frame(@103,Object[#89])
> 
> 	at org.jodconverter.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:187)
> 	at org.jodconverter.job.AbstractConversionJob.execute(AbstractConversionJob.java:57)
> 
 Could you give me an advice please ?

**Comment by is-simon** [comment]
He there. 

Would it be possible for you to share a minimal project I could work with to investigate this issue ?? You could create a github project with all the necessary configuration required to reproduce the problem. Without that it will be very hard (impossible) for me to help.

**Comment by sbraconnier** [comment]
He there.

Would it be possible for you to share a minimal project I could work with to investigate this issue ?? You could create a github project with all the necessary configuration required to reproduce the problem. Without that it will be very hard (impossible) for me to help.

**Comment by sbraconnier** [comment]
Any reason why you use LO libraries instead of OO libraries ?

**Comment by dnikolov9005** [comment]
Hello,
thank you very much for your response!
I am doing analyze for my project and this is only a test demo for me to check how it works the JODConvertor and LOO,AOO
I have just a simple class 

public static void main(String[] args) {
		File inputFile = new File(input);
		File outputFile = new File(output);

		// Create an office manager using the default configuration.
		// The default port is 2002. Note that when an office manager
		// is installed, it will be the one used by default when
		// a converter is created.
		final LocalOfficeManager officeManager = LocalOfficeManager.install();
		try {

			// Start an office process and connect to the started instance (on port 2002).
			officeManager.start();

			// Convert
			JodConverter
					.convert(inputFile)
					.to(outputFile)
					.execute();
		} catch (OfficeException e) {
			e.printStackTrace();
		} finally {
			// Stop the office process
			OfficeUtils.stopQuietly(officeManager);
		}
	}

All my dependencies are on my previous comment. If this is not enough for you to help me I would provide you a minimal project here for you, with pleasure!

Thanks

**Comment by dnikolov9005** [comment]
"Any reason why you use LO libraries instead of OO libraries ?"

- Not at all. After a quick research I just decided to use these libraries based on the data I have read about

**Comment by dnikolov9005** [comment]
Hello,
just to let you know that I have managed with JOD and LibreOffice but the problem is in my .doc file :)

Thank you for your quick response.

I wish you all the best

**Comment by sbraconnier** [comment]
Ok!! Thanks for letting me know!! I was unable to reproduce the problem so I'm glad you were able to resolve it by youself!!

Regards!
