### ISSUE TITLE
Attaching OfficeManager to already running Process

### ISSUE THREAD

**Issue by riteshbhambhani** [sbraconnier/jodconverter#203]
Hi,

I have a Java application which starts the OfficeManager on few ports. I want other Java applications to use these processes that have already started. Is there a way to attach a new LocalOfficeManager to the already running process.

I tried to use the ExternalOfficeManager but it can only take a single port and can attach it to the Office process running on that port. This question is to see if I am missing something.

**Comment by sbraconnier** [comment]
It is not possible at the moment, but I'm working on it. It will be in the next release.

**Comment by sbraconnier** [comment]
You can now (in the next release) use the ExternalOfficeManager to connect to multiple ports (it uses a connection pool):

```java
final OfficeManager manager =
    ExternalOfficeManager.builder()
        .portNumbers(2002,2003)
        .build();
```
