### ISSUE TITLE
Converting HTML image

### ISSUE THREAD

**Issue by choepeter** [sbraconnier/jodconverter#205]
When trying to convert an html file that has an image embedded with width and height set with absolute value, the image gets truncated if the image is bigger than the width of the page.  Is there a configuration setting to tell conversion to scale the image automatically?

**Comment by sbraconnier** [comment]
Are you able to do it with LibreOffice (or OpenOffice) without JODConverter (using the export option)? If yes, then you should be able to do it with JODConverter using a specific [Filter](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters).

**Comment by sbraconnier** [comment]
@choepeter Did you succeed ??

**Comment by sbraconnier** [comment]
Closing this one. Feel free to re-open if needed.
