### ISSUE TITLE
How to disable AutoCalculate?

### ISSUE THREAD

**Issue by miztaka** [sbraconnier/jodconverter#207]
In a server application, when you convert libreoffice calc file to pdf, cell is auto calculated and some vulnerable formulas (such as =WEBSERVICE) are executed.

I want to turn AutoCalculate off before conversion, so server can convert all of calc files uploaded by user safely.
How can I do this?

Any help would be appreciated.

Thanks for great library!

**Comment by sbraconnier** [comment]
Are you able to do it with LibreOffice (or OpenOffice) without JODConverter (using the export option)? If yes, then you should be able to do it with JODConverter using a specific [Filter](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters).

**Comment by miztaka** [comment]
Thanks, worked with Filter!
FYI code is like this:

```
  @Override
  public void doFilter(OfficeContext context, XComponent document, FilterChain chain)
      throws Exception {
    Lo.qiOptional(XCalculatable.class, document).ifPresent((x) -> {
      x.enableAutomaticCalculation(false);
    });
    chain.doFilter(context, document);
  }
```
