### ISSUE TITLE
How to convert html to docx/odt? 

### ISSUE THREAD

**Issue by woozI43** [sbraconnier/jodconverter#209]

**Comment by sbraconnier** [comment]
Are you asking how JodConverter works ?? Or if you already know how it works, but were unable to convert html to docx/odt ?

**Comment by woozI43** [comment]
Im a beginner I don't actually know how it works

**Comment by sbraconnier** [comment]
Ok!! Then maybe you could take a look at the [wiki](https://github.com/sbraconnier/jodconverter/wiki) and see if it helps you. Don't hesitate to ask any question if you are unable to achieve your goal. But try to add more details when asking a question. Thanks!

**Comment by woozI43** [comment]
Ok thanks.
