### ISSUE TITLE
Is there going to be a new release soon?

### ISSUE THREAD

**Issue by benelot** [sbraconnier/jodconverter#21]
Hello,

I see that you revived JODConverter from the dead and built a pretty descent library out of it. Thanks for your work! Now since the last release, you did a larger refactoring into local and remote part. Is there going to be a new release soon?

**Comment by sbraconnier** [comment]
Hi,

It should be in a weak, maybe 2. It won't contain any major changes so you could use the OSS snapshot repository for now and use the 4.1.0-SNAPSHOT version so start working with the 4.1.0 version and then use the 4.1.0 version when it is released. It should be transparent.

See [OSS snapshot repository](https://oss.sonatype.org/content/repositories/snapshots)

**Comment by benelot** [comment]
Thank you very much! That is a prompt and positive answer :D
