### ISSUE TITLE
officeHome doesn't exist or is not a directory 

### ISSUE THREAD

**Issue by NoviceGabe** [sbraconnier/jodconverter#210]
I want to convert a document (doc) to pdf on android. I have installed open office 4 in "C:\Program Files (x86)\OpenOffice 4". 

Here's my code:

    File inputFile = new File("sample.doc");
    File outputFile = new File("sample.pdf");

    final LocalOfficeManager officeManager = LocalOfficeManager.builder()
       .officeHome("C:\\Program Files (x86)\\OpenOffice 4")
       .install()
       .build();

        try{
            officeManager.start();
            JodConverter
                    .convert(inputFile)
                    .to(outputFile)
                    .execute();

        } catch (OfficeException e) {
            e.printStackTrace();
        } finally {
            OfficeUtils.stopQuietly(officeManager);
        }

When I run the program I receive this error:

java.lang.IllegalStateException: officeHome doesn't exist or is not a directory: C:\Program Files (x86) \OpenOffice 4
 at org.jodconverter.local.office.LocalOfficeUtils.validateOfficeHome(LocalOfficeUtils.java:340)
at org.jodconverter.local.office.LocalOfficeManager$Builder.build(LocalOfficeManager.java:169)

Did I miss something or what? How can I fix this?

**Comment by sbraconnier** [comment]
Hmm!! This sounds like an access problem. Could you take a snapshot of tour installation folder ??? Did you try running your program as "admin" ??

**Comment by NoviceGabe** [comment]
Here it is:
![Capture](https://user-images.githubusercontent.com/36945531/82543075-e22e8f80-9b07-11ea-872b-0f141bba6e2e.PNG)

and yes I run the program as admin.

**Comment by AamirNaseer1** [comment]
I'm using JOD Converter to convert document in my android app but getting this exception and don't know how to set officeHome in android app can any body help me ?
java.lang.IllegalStateException: officeHome not set and could not be auto-detected

**Comment by sbraconnier** [comment]
@AamirNaseer1 LibreOffice is not supported on Android device...

**Comment by sbraconnier** [comment]
@NoviceGabe 
I'm not an expert on android development, but how could you have a C:\Program Files\etc... on an Android device???
