### ISSUE TITLE
ExternalOfficeManager :: makeTempDir not called when connectOnStart = false

### ISSUE THREAD

**Issue by tdjac0bs** [sbraconnier/jodconverter#211]
Hello, there is a problem when you use connectOnStart = false.

It does not create the tempDir.

In file ExternalOfficeManager.java:

![image](https://user-images.githubusercontent.com/2075267/83715604-2f305c80-a604-11ea-89b1-7d78b3a4a348.png)

**Comment by sbraconnier** [comment]
Thanks. This will be fixed in the 4.3.1 version. The ExternalOfficeManager will also support polling.
