### ISSUE TITLE
Issues converting dotx

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#213]
I'am using `DefaultDocumentFormatRegistry` to retrieve the document type of an incoming document which i want to conver. In case this is a `dotx` it wont work, since there is no mapping for it.

https://github.com/EugenMayer/officeconverter/blob/master/src/main/java/de/kontextwork/converter/service/ConverterService.java#L38

Are there any particular reasons for that? Does LibreOffice not support dotx as a source for conversion?

**Comment by sbraconnier** [comment]
Sorry for the delay!! 

Thanks for your findings, I'll add this myself in the 4.3.1 version. I think you have mixed the docx and dotx title :)

**Comment by sbraconnier** [comment]
Fixed by 9c930fcb1289dad123903f1a88c07a00fb2138e1
