### ISSUE TITLE
    java.lang.IllegalStateException: officeHome not set and could not be auto-detected

### ISSUE THREAD

**Issue by AamirNaseer1** [sbraconnier/jodconverter#217]
I'm using JOD Converter to convert document in my android app but getting this exception and don't know how to set officeHome in android app can any body help me ?
java.lang.IllegalStateException: officeHome not set and could not be auto-detected

**Comment by sbraconnier** [comment]
Does LibreOffice can be installed on an android device ???

**Comment by sbraconnier** [comment]
It doesn't seem to be the case:
https://ask.libreoffice.org/en/question/232081/where-can-i-download-libreoffice-for-android/
