### ISSUE TITLE
Advice on how to implement a custom local office task

### ISSUE THREAD

**Issue by benelot** [sbraconnier/jodconverter#22]
Hello,

I want to implement my own custom local office task to be processed on libreoffice using the JODConverter classes. I intend to base my work on yours since the JODConverter has a beautiful implementation of different types of connections as well as process handling etc. Can you give me a recommendation on how to achieve the following:

   CreatingADocumentUsingLOTask cadulot = new CreatingADocumentUsingLOTask(...some params for the task...);
    LocalOfficeManager manager = LocalOfficeManager.install();
    manager.execute(cadulot);
    manager.stop();

Which parts do I have to implement my custom CreatingADocumentUsingLOTask to allow it to be executed? What I want to do in there is to load a libreoffice template, edit some parts, replace some placeholders and finally export the document to a stream. I can do that already using my own classes, however, I now want to transform it into a task I can execute using JODConverter. How can I do this?

Thanks!

**Comment by sbraconnier** [comment]
Hello again,

First, take a look at the wiki about the [Filters](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters) feature to see if you could use custom filters to fit your needs. It seems like what you try to do is exactly what filters have been designed for (Load a document, apply modifications, store it).

You have more filter examples [here](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-local/src/integTest/java/org/jodconverter/filter)

**Comment by benelot** [comment]
Oh, that sounds absolutely amazing. Thanks for the pointer to the filter, I will look if I can build what I want.

**Comment by benelot** [comment]
Thanks for the advice, I could simply copy in my previously written code. The framework makes comnection handling and applying changes so much easier and better structured, thank you!
