### ISSUE TITLE
How to setting set document store properties and learn?

### ISSUE THREAD

**Issue by awerdx520** [sbraconnier/jodconverter#221]
**I am using Google Translate, it may be very confusing**
 
I need to parse and replace the content of the Word document (for example: extract the corresponding text in Word and then perform some processing [_such as: translate into other languages_] and then replace it to the original location), I need to provide the original document and the processed document Web display (the original style needs to be retained as much as possible).
The solution I use is to convert to `XHTML` via `jodconverter` (the basis for the selection is-it is more concise). Then use `jsoup` to process the html and convert it into a Word document.

**problem:**
1. XHTML is exported as an embedded image by default. Due to transmission performance, I need to separate it and specify the path. But I don't know how to set the properties (eg: `FilterOptions: EmbedImages`).May I ask where there are relevant help documents. I found this through [Google](https://cgit.freedesktop.org/libreoffice/core/tree/filter/source/config/fragments/filters/XHTML_Writer_File.xcu?h=libreoffice-4-0-4) found some answer. But I don't understand what it means. May I ask what pre-knowledge is needed.

**Comment by sbraconnier** [comment]
Here's an example that set the `FilterOptions: EmbedImages`

```java
final File input = new File("input.doc");
final File output = new File("output.html");

final DocumentFormat format =
    DocumentFormat.builder()
        .from(DefaultDocumentFormatRegistry.HTML)
        .storeProperty(DocumentFamily.TEXT, "FilterOptions", "EmbedImages")
        .build();
JodConverter.convert(input).to(output).as(format).execute();
```

**Comment by awerdx520** [comment]
I know how to set embedded images when exporting html, but I want to export xhtml without embedding images, xhtml exports embedded images by default

**Comment by awerdx520** [comment]
I have realized export html through jodconverter and developed related functions. But I need a more concise xhtml export, separating xhtml files and pictures. How to set this parameter?
