### ISSUE TITLE
How to change font when converting docx to pdf

### ISSUE THREAD

**Issue by csquare0** [sbraconnier/jodconverter#222]
Unsupported font will generate blank square when converting from doc to PDF. Is it possible to set a default font or change text font in filter to each page?

**Comment by is-simon** [comment]
You could try to set a custom [template profile directory](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) maybe ??

All the "customized" Libre/Open Office settings can be also used while converting with jodconverter by using this configuration option.

**Comment by sbraconnier** [comment]
You could try to set a custom template profile directory maybe ??

All the "customized" Libre/Open Office settings can be also used while converting with jodconverter by using this configuration option.

**Comment by sbraconnier** [comment]
Did you succeed ?

**Comment by dupinderdhiman** [comment]
Hi @sbraconnier [template profile directory ](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) didn't helped 🤐

**Comment by sbraconnier** [comment]
@dupinderdhiman I would need a sample file to reproduce this problem. I need a source file, an expected result file and an actual result file (with a detailed explanation of the problem). Thanks.

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open is needed.
