### ISSUE TITLE
Setting parameters when using REST

### ISSUE THREAD

**Issue by LindezaGrey** [sbraconnier/jodconverter#224]
Hi there,

i would like to use the REST example [from your repo](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest)

Conversion from pptx to pdf works (cUrl and SwaggerUI) but i'm not able to pass parameters like "PageRange" to this call...
Any hints for a good documentation for this scenario, or a cUrl command?

Thanks in advance!

**Comment by zouzhihao-994** [comment]
+1

**Comment by sbraconnier** [comment]
Sorry for the delay!!!

It is already supported... I'll have to improve documentation, but the way it was implemented is (let me know if it doesn't work):

- Load properties must have the prefix l
- Store properties must have the prefix s
- Filter Data properties (which are store properties), must have the prefix sfd

So, suppose you want to pass parameter like PageRange to converter the second page of a document to PDF, your query must look like:

`{{bareUrl}}/lool/convert-to/pdf?sfdPageRange=2`

**Comment by LindezaGrey** [comment]
Hey there, 

no problem regarding the response time! Thanks for your answer, i checked it and it works.
For reference here is a python code-snippet, for my usecase:

```python
    headers = {
        "accept": "application/octet-stream",
    }
    params = {"format": "pdf", "sfdPageRange": "1-3"}
    with open(pptx_path, "rb") as file:
        files = {
            "data": (pptx_path.stem + ";type", file),
        }
        response = requests.post(
            f"http://{converter_url}/lool/convert-to",
            headers=headers,
            params=params,
            files=files,
        )
```

I am not sure if this is an exhaustive list, but i found this on Github in regards to the filter options that should be available: [Filter Options](https://github.com/unoconv/unoconv/blob/5719f58b327f384b13b20eef963590ff50702e9f/doc/filters.adoc)

So from my side you can close the issue,

thanks and best regards

**Comment by sbraconnier** [comment]
Good news!! Thanks for the filter options list. I'll try to find the time to put that in the wiki!
