### ISSUE TITLE
支持onlyoffice 文件转换吗？

### ISSUE THREAD

**Issue by yinxiulong** [sbraconnier/jodconverter#228]
jodconverter 支持 onlyoffice 文档转换吗？

**Comment by sbraconnier** [comment]
Could you please try to google translate that ?? I did, but I'm not sure I understand the question... See the [wiki](https://github.com/sbraconnier/jodconverter/wiki) pages for more information.

**Comment by zezhenyan** [comment]
@sbraconnier  I think he means "Do we support OnlyOffice file converter in jodconverter?"

**Comment by sbraconnier** [comment]
Thanks @zezhenyan. Then the answer to the question is no. OnlyOffice seems to be a Web solution and it is not supported by jodconverter.
