### ISSUE TITLE
Do we need close LocalOfficeManager in my process?

### ISSUE THREAD

**Issue by zezhenyan** [sbraconnier/jodconverter#230]
Hi all
Because I found when I build a new LocalOfficeManager, it will take 3 seconds. So I want to keep this object in my process, will not stop it. Is there any side effect about keeping this object?

**Comment by is-simon** [comment]
It's totally fine to keep your manager open. In fact, it is preferred. You just have to be sure to close it when your application is closed. Jodconverter (local module) works like a database connection pool. You can start multiple office processes to speed up the conversion process, if it's required.

See the [wiki](https://github.com/sbraconnier/jodconverter/wiki) pages for more information.

**Comment by sbraconnier** [comment]
It's totally fine to keep your manager open. In fact, it is preferred. You just have to be sure to close it when your application is closed. Jodconverter (local module) works like a database connection pool. You can start multiple office processes to speed up the conversion process, if it's required.

See the [wiki](https://github.com/sbraconnier/jodconverter/wiki) pages for more information.

**Comment by zezhenyan** [comment]
Thanks so much for your quick reply. That's  a big help.
