### ISSUE TITLE
LibreOffice conversion on .odt file to pdf is timing out on Ubuntu and succeeding on MacOS

### ISSUE THREAD

**Issue by jweilhammer** [sbraconnier/jodconverter#231]
File conversion seems to be flaky only when running through jodconverter on Linux (Ubuntu 18.04.4) through my Java 11 application.  Will sometimes convert perfectly and then when run back to back it will fail and timeout (taking full 20 minutes and then failing).   Overall it is timing out consistently on Ubuntu and randomly (and rarely) succeeding conversion.  When it does succeed conversion, the total conversion time is very fast (less than 5 seconds) and when it fails it will work for 20 minutes and then fail due to timeout. 

When running the command line headless convert command with LibreOffice on the same Linux machine the file never fails, which leads me to believe issue is with jodconverter and not Libre.

Running the file through the same application using jodconverter on MacOS (Catalina) with LibreOffice 7.0.1.2 does not have this issue at all. 

Thinking it might be an issue with just this file, but hoping it isn't more widespread. Looking like page 11 is breaking the conversions, although it is still flaky on pages 8+. The images included in the tables on pages 10+11 seem to be weird (not loading in OpenOffice/Libre, but are shown in the converted pdf)

Testing conversion through jodconveter on specific pages:

(1) - working
(1-2) - working
(1-3) - working
(1-4) - working
(1-5) - working
(1-6) - working
(1-7) - Got one timeout out of around 100, seems to be consistently passing
(1-8) - Flakier, but not completely failing. About 70% success rate
(1-9) - same as 1-8
(1-10) - same as 1-8
(1-11) - Timing out consistently, rare random successes
Original document (1-12) - same as 1-11

Wondering if anyone can replicate this or suggest a solution as I've tried different configurations and versions of all tools and not finding an easy fix for this. 

Tested with jodconverter 4.2.4 and 4.3.0 on Java 11
LibreOffice 7.0 and 6.4
Ubuntu 18.04.4

Attaching the original file, converted pdfs (flaky), and the files with each page taken out. 
[odt_timeout.zip](https://github.com/sbraconnier/jodconverter/files/5302607/odt_timeout.zip)

**Comment by mrderban** [comment]
Hi @jweilhammer, I'm currently encountering a similar issue, were you able to find a solution by any chance ?

**Comment by jweilhammer** [comment]
@mrderban, unfortunately not, this issue has basically been long forgotten

There does seem to be some sort of inconsistency with jod-converter working on MacOS vs Ubuntu in general (not just a timeout), but it's a 0.01% case

I'd recommend maybe a new issue, I'm not sure the root cause is going to be found on this one

**Comment by mrderban** [comment]
@jweilhammer thank you for your response !

**Comment by sbraconnier** [comment]
Sorry I couldn't help. I wonder if the issue still exists with the more recent version of LO. I'll close the issue due to inactivity but feel free to reopen if required.
