### ISSUE TITLE
Error while converting document from ODS to PDF Format 

### ISSUE THREAD

**Issue by malotjitesh** [sbraconnier/jodconverter#236]
package com.doc.conversion;

import java.io.File;
import java.io.FileNotFoundException;
import java.net.ConnectException;

import org.jodconverter.core.document.DefaultDocumentFormatRegistry;
import org.jodconverter.core.document.DocumentFormatRegistry;
import org.jodconverter.core.office.OfficeManager;
import org.jodconverter.core.office.OfficeUtils;
import org.jodconverter.local.JodConverter;
import org.jodconverter.local.office.LocalOfficeManager;

public class ConvertDocument {

	public static void main(String[] args) throws FileNotFoundException, ConnectException {
		// TODO Auto-generated method stub
		OfficeManager officeManager = null;
		try {
			File inputFile = new File("path/odstest.ods");
			File outputFile = new File("path/abc.pdf");
			officeManager = LocalOfficeManager.builder().officeHome("officeHomePath").install().build();
			officeManager.start();
			DocumentFormatRegistry registry = DefaultDocumentFormatRegistry.getInstance();
			// DocumentConverter converter = LocalConverter.make(officeManager);
			// OfficeDocumentConverter converter = new
			// OfficeDocumentConverter(officeManager);
			JodConverter.convert(inputFile).as(registry.getFormatByExtension("ods")).to(outputFile)
					.as(registry.getFormatByExtension("pdf")).execute();
		} catch (Exception e) {
			// System.out.println(e.getMessage());
			e.printStackTrace();
		} finally {
			OfficeUtils.stopQuietly(officeManager);
		}
	}

}

--------------------------------------------------------Error-------------------------------------------------------
Exception in thread "main" java.lang.VerifyError: Stack map does not match the one at exception handler 103
Exception Details:
  Location:
    org/jodconverter/local/task/AbstractLocalOfficeTask.loadDocument(Lorg/jodconverter/local/office/LocalOfficeContext;Ljava/io/File;)Lcom/sun/star/lang/XComponent; @103: astore_3
  Reason:
    Type 'com/sun/star/lang/IllegalArgumentException' (current frame, stack[0]) is not assignable to 'com/sun/star/uno/Exception' (stack map, stack[0])
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'org/jodconverter/local/task/AbstractLocalOfficeTask', 'org/jodconverter/local/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/lang/IllegalArgumentException' }
  Stackmap Frame:
    bci: @103
    flags: { }
    locals: { 'org/jodconverter/local/task/AbstractLocalOfficeTask', 'org/jodconverter/local/office/LocalOfficeContext', 'java/io/File' }
    stack: { 'com/sun/star/uno/Exception' }
  Bytecode:
    0000000: 2bb9 000c 0100 2cb8 000d 120e 032a b600
    0000010: 0fb8 0010 b900 1105 004e 2dbb 0012 59b7
    0000020: 0013 1215 b600 162c b600 17b6 0016 b600
    0000030: 1803 bd00 19b8 001a 572d b04e bb00 1c59
    0000040: bb00 1259 b700 1312 15b6 0016 2cb6 0017
    0000050: b600 1612 1db6 0016 2db4 001e b600 1fb6
    0000060: 0018 2db7 0020 bf4e bb00 1c59 bb00 1259
    0000070: b700 1312 15b6 0016 2cb6 0017 b600 16b6
    0000080: 0018 2db7 0020 bf                      
  Exception Handler Table:
    bci [0, 58] => handler: 59
    bci [0, 58] => handler: 103
    bci [0, 58] => handler: 103
  Stackmap Table:
    same_locals_1_stack_item_frame(@59,Object[#95])
    same_locals_1_stack_item_frame(@103,Object[#96])

	at org.jodconverter.local.LocalConverter$LocalConversionJob.doExecute(LocalConverter.java:156)
	at org.jodconverter.core.job.AbstractConversionJob.execute(AbstractConversionJob.java:60)
	at com.doc.conversion.ConvertDocument.main(ConvertDocument.java:33)

**Comment by sbraconnier** [comment]
I'm unable to reproduce this error. Could you please create a sample project I could work with to work on this problem ?? Also, I need to know the following:

- OS
- LibreOffice/OpenOffice version
- JODConverter version.

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open is needed.
