### ISSUE TITLE
Unable to convert ods file

### ISSUE THREAD

**Issue by tuxmaster5000** [sbraconnier/jodconverter#237]
Hi, using LIbreOffice 7 and XWiki, the conversion fails.
Here is the original bug report with the trace:
https://forum.xwiki.org/t/office-import-fails-with-type-detection-failed/7808

**Comment by sbraconnier** [comment]
Following the link provided, it seems that the bug has been resolved and that it was not a JODconverter problem. Feel free to re-open if you don't agree with that.
