### ISSUE TITLE
regression: document-formats with singular extension field are not supported anymore

### ISSUE THREAD

**Issue by surli** [sbraconnier/jodconverter#248]
Hi, I'm currently working on upgrading XWiki from jodconverter 4.2.4 to jodconverter 4.4.0, and I noticed a regression related to the `document-formats.json` file. We obtain with jodconverter 4.4.0 the following stacktrace:

```
2021-02-04 16:28:04,478 [qtp783286238-15 - http://localhost:8080/xwiki/bin/admin/XWiki/XWikiPreferences?editor=globaladmin&section=XWiki.OfficeImporterAdmin] WARN  o.x.o.i.s.DefaultOfficeSer
ver  - Failed to parse /document-formats.js . The default document format registry will be used instead. 
java.lang.NullPointerException: null
        at java.util.LinkedHashSet.<init>(LinkedHashSet.java:168)
        at org.jodconverter.core.document.DocumentFormat$Builder.from(DocumentFormat.java:276)
        at org.jodconverter.core.document.DocumentFormat.unmodifiableCopy(DocumentFormat.java:76)
        at org.jodconverter.core.document.JsonDocumentFormatRegistry.lambda$readJsonArray$2(JsonDocumentFormatRegistry.java:121)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
        at org.jodconverter.core.document.JsonDocumentFormatRegistry.readJsonArray(JsonDocumentFormatRegistry.java:136)
        at org.jodconverter.core.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:80)
        at org.jodconverter.core.document.JsonDocumentFormatRegistry.create(JsonDocumentFormatRegistry.java:52)
        at org.xwiki.officeimporter.internal.server.DefaultOfficeServer.initialize(DefaultOfficeServer.java:152)
```

So I looked a bit, and right now we are providing the following document-formats.json file in XWiki: https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-office/xwiki-platform-office-importer/src/main/resources/document-formats.js. This NPE apparently occurs because we are still providing an `extension` field instead of an `extensions` (plural) with an array-type field. 
I'd be ok to update this file, the problem is that we might have old instances that are using a custom version of this file, and we need to keep supporting the backward compatibility. I checked back in 4.2.4 and we didn't had this issue even if the support of multiple extensions is much older (since 4.2.1 apparently from what I see in https://github.com/sbraconnier/jodconverter/commit/88e02a98e8b41818b4838d2a3ff9187a3841273d). I haven't been able to track down yet where the regression occurs but I'm still investigating.

**Comment by sbraconnier** [comment]
Stop looking. I know what must be done to fix this. I'll try to create à 4.4.1 version quickly. Do you have a workaround for now so you could continue to migrate and came back to me in case you have another problem to fix ??

XWiki is a great platform that uses JODConverter and I do not want to break things for you. But since I just have my integration tests to work with, I may introduce some undesired effects without knowing (I try hard not to!)

**Comment by surli** [comment]
> Stop looking.

Oops, I finally tracked down https://github.com/sbraconnier/jodconverter/commit/6a46ce3cf5743a6bdd31c6547f16d9da1f681b1b#diff-213236437352946c85a4b4226886abf139d9703360eb1b74468c0e266d9388f6L49 :) 

> Do you have a workaround for now so you could continue to migrate and came back to me in case you have another problem to fix ??

Well I suppose I will update the `document-formats.json` that we provide to use `extensions`: there's no point on keeping the legacy format in there. Now we're supposed to release our next stable version containing the upgrade 22nd of february, and the RC a week before (the 15th). So basically we'd need to have the 4.4.1 released before those dates at best. 

> XWiki is a great platform that uses JODConverter and I do not want to break things for you.

thanks :) 

>  I may introduce some undesired effects without knowing (I try hard not to!)

yeah not easy to avoid breaking things :) just for info, the upgrade to 4.4.0 did break our own backward compatibility because we were exposing some of jodconverter API which have been renamed with the package refactoring. In order to avoid the problem in the future we took the decision to encapsulate jodconverter APIs into our own so it shouldn't be a problem anymore. I guess that's the reason for not releasing it under 4.2.x, still would have been nice to emphasis on it in the release notes. By the way, maybe you already know about it but https://github.com/revapi/revapi is a very nice tool for checking / reporting breaking changes.

**Comment by surli** [comment]
> Well I suppose I will update the document-formats.json that we provide to use extensions: there's no point on keeping the legacy format in there.

So I confirm that we'll update our provided document-formats.json and also document that users should now respect the new format. Still if you can provide a bug fix release to still support the old format it would be great !

**Comment by surli** [comment]
Actually I just got another related error: 
> java.lang.NullPointerException: inputFamily must not be null

**Comment by surli** [comment]
Just found another one more insidious: `storePropertiesByFamily` field name is not taken into account anymore in favor of `storeProperties`. This one is really problematic since you don't get any error log when building jodconverter instance but it makes the conversion failing because of missing information.

**Comment by surli** [comment]
You can check the change I needed with the upgrade to make it work here: https://github.com/xwiki/xwiki-platform/commit/291dbf9a90e8e65a72ff352842410391e9c7a4fc. Besides that our integration tests are passing apparently.

**Comment by sbraconnier** [comment]
> Now we're supposed to release our next stable version containing the upgrade 22nd of february, and the RC a week before (the 15th). So basically we'd need to have the 4.4.1 released before those dates at best.

> So I confirm that we'll update our provided document-formats.json and also document that users should now respect the new format. Still if you can provide a bug fix release to still support the old format it would be great !

Will do!

> Just found another one more insidious: storePropertiesByFamily field name is not taken into account anymore in favor of storeProperties. This one is really problematic since you don't get any error log when building jodconverter instance but it makes the conversion failing because of missing information.

I'll fix that too!

> I guess that's the reason for not releasing it under 4.2.x, still would have been nice to emphasis on it in the release notes.

I totally agree! I should really work on the project documentation. I wish I had a twin to work on the project AND my full time day job :/

> By the way, maybe you already know about it but https://github.com/revapi/revapi is a very nice tool for checking / reporting breaking changes.

Wow thank a lot! I'll take a look for sure!

**Comment by surli** [comment]
>  and also document that users should now respect the new format.

Is there some documentation about the document-format.js file format?  I haven't found it in the wiki.

**Comment by sbraconnier** [comment]
> Is there some documentation about the document-format.js file format? I haven't found it in the wiki.
I'm afraid not. The actual documentation is the one the original author of the jodconverter project gave me when I contacted him to know if he had a copy of the "artofsolving" website. Very kind of him. But the project has evolved and the documentaiton didn't. I should really focus on that but to be honest, this is not my strengh!! I would like to make a website from the wiki and improve it. If you have the task to document the `document-format.js` file, feel free to update the wiki!! I could make you a contributor.

**Comment by sbraconnier** [comment]
I've uploaded a 4.4.1-SNAPSHOT version with the fix. You must use the OSS snapshot repository:
https://oss.sonatype.org/content/repositories/snapshots

Could you please check if everything is all right??

I've fix the `extension` and `storePropertiesByFamily` fields. But I didn't removed the null check on the `inputFamily` field. It sounds like a required property for me.

**Comment by surli** [comment]
> Could you please check if everything is all right??

So AFAICS it's working properly. Would be perfect if you can release it tomorrow. 

> But I didn't removed the null check on the inputFamily field.

OK I'll emphasize on that in our RN. 

> It sounds like a required property for me.

You know what was the fallback value when the property was null before?

**Comment by sbraconnier** [comment]
> You know what was the fallback value when the property was null before?

Well... I release the 4.4.1 version too quickly. It looks like the inputFamily is not that required after all. I'm releasing a 4.4.2 version right away with #249

**Comment by sbraconnier** [comment]
All done. It should be available soon.

**Comment by surli** [comment]
yeah I saw it thanks a lot for fast releases :)
