### ISSUE TITLE
How to modify output Image and remove white border while emf -> png 

### ISSUE THREAD

**Issue by hblwyq** [sbraconnier/jodconverter#250]
Hello, we are currently using JodConverter to convert image.

While converting emf to png, the output image has blank background. It seems like the whole page(document) not only the target image is converted to png. And the size of output file is far more bigger than the source image.  

In LibreOffice GUI, after open the emf image:
     "File -> Export"  triggers the phenomenon mentioned above 
     "select image -> save as -> image export"  can get the correct result .

So the question is : how to use "image export" other than "export" in JodConverter. 
Maybe the filter "draw_png_Export" can be replaced to ??? to finish this work.
"storeProperties": {
        "DRAWING": {
          "FilterName": "draw_png_Export"
        }, 
But I did not find any documents about this 😭😭😭.

Maybe there is  another way to crop the output PNG image: 
First, get the size of the image.
Then, crop the output PNG image with the size of source image.
But I did not find an existed filter can be set to FilterChain In JodConverter which has this function😭😭😭.

Looking forward to your answer, thank you very much. 感激不尽

**Comment by sbraconnier** [comment]
Hello,

You can specify you own filter like this:

```java
final Map<String, Object> storeProperties = new HashMap<>();
storeProperties.put("FilterName", "draw_png_Export");

LocalConverter.builder()
    .officeManager(officeManager)
    .storeProperties(storeProperties)
    .build()
    .convert(sourceFile)
    .to(targetFile)
    .execute()
```

Note that you can also use you own supported  `document-formats.json` file. The default one is [here](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-core/src/main/resources/document-formats.json). And you can replace it like this:

```java
final DocumentFormatRegistry registry = JsonDocumentFormatRegistry.create(FileUtils.readFileToString(new File("path to your file"), StandardCharsets.UTF_8));

LocalConverter.builder()
    .officeManager(officeManager)
    .formatRegistry(registry)
    .build()
    .convert(sourceFile)
    .to(targetFile)
    .execute()
```

**Comment by hblwyq** [comment]
Thanks a lot. I will try to implement my own filter later. 🙏

**Comment by sbraconnier** [comment]
Will close this one due to inactivity. Fell free to re-open if needed.
