### ISSUE TITLE
     Caused by: java.lang.NullPointerException: officeHome must not be null

### ISSUE THREAD

**Issue by dineshchavhan** [sbraconnier/jodconverter#251]

**Comment by dineshchavhan** [comment]
Caused by: java.lang.NullPointerException: officeHome must not be null

**Comment by crazedmeph** [comment]
I think you are going to need to provide a little more information than this.

**Comment by sbraconnier** [comment]
Indeed!! But maybe you don't have a standard Libre/Open Office installation. By default, jodconverter will try to auto-detect the office installation. But you can also use the [officeHome](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_folderofficehome) property.

**Comment by dineshchavhan** [comment]
yes I dont have office install, its big file and my app will be so big
after installation.
is any other way to skip office home installation

**Comment by sbraconnier** [comment]
It is not JODConverter that converts documents, it is Libre/Open Office. JODConverter is just a tool that uses an office installation behind the scene to convert documents. So, no, it is not possible to skip the office installation.

Maybe you could have a dedicated server you could send your conversion tasks to using the [remote](https://github.com/sbraconnier/jodconverter/wiki/LibreOffice-Remote) module, but I can't say without knowing you application.
