### ISSUE TITLE
Preserving blank pages for duplex print

### ISSUE THREAD

**Issue by Michigras** [sbraconnier/jodconverter#253]
Unfortunately, I can't figure it out myself. I need the converter to add blank pages (there are page breaks of the type "oddPage") as it would do by checking "Include automatically inserted blank pages" (or similar, I don't have an English LibreOffice version). This can be found as a checkbox after selecting File > Export As > PDF.
Filters modify the file before saving it, but adding blank pages doesn't really classify as a filter (nor do I know the right settings to apply to the document).

**Comment by sbraconnier** [comment]
Please try this:

```java
File inputFile = new File("document.odt");
File outputFile = new File("document.pdf");

Map<String, Object> filterData = new HashMap<>();
filterData.put("IsSkipEmptyPages", new Boolean(false));
Map<String, Object> customProperties = new HashMap<>();
customProperties.put("FilterData", filterData);

LocalConverter
  .builder()
  .officeManager(manager)
  .storeProperties(customProperties)
  .build()
  .convert(inputFile)
  .to(outputFile)
  .execute();
```

Inpired by [this](https://github.com/sbraconnier/jodconverter/issues/160)

**Comment by Michigras** [comment]
Just a shot note: I'm currently working on something different. I'll definitely come back and report if it worked.

**Comment by Michigras** [comment]
This works just as you described it. Thank you!
