### ISSUE TITLE
Issues converting potx and xltx

### ISSUE THREAD

**Issue by SelmaSa1** [sbraconnier/jodconverter#259]
Hi, I'm trying to convert .potx and .xltx Files, but I keep running into an Error:

```java.lang.IllegalArgumentException: Unable to convert unknown type: application/vnd.openxmlformats-officedocument.presentationml.template```

I figured out, these Filetypes are not supported. In a provious issue, support for dotx was added: #213 

Will support for .potx and .xltx also be added?

**Comment by sbraconnier** [comment]
Fixed by #270
