### ISSUE TITLE
Macros not being run during conversion

### ISSUE THREAD

**Issue by fabiohast** [sbraconnier/jodconverter#26]
Hello,

I'm using JodConverter (v-4.0.0) to convert some documents from docx to pdf in my web application. One of the problems that I have is that I need to update the table of contents in the input documents. To do this I created a macro in LibreOffice to update my TOC everytime a document is opened with LibreOffice. However when I use JodConverter to convert my files, the macros aren't executed and my TOC isn't updated. 

Do you know if JodConverter supports this? Do I need to use some kind of config in my code for the converter to get the macros to run?
![image](https://user-images.githubusercontent.com/31777950/30384702-f3415052-989c-11e7-83d2-dabd7ab08a3c.png)
I saw this in an old forum and tried but it did not work.

Do you have any tips for me?

Thanks in advance!

**Comment by sbraconnier** [comment]
Hi,

When you create a macro, I guess it is stored in the user profile directory. So you have to set the template profile directory of the office manager to this user profile when you start your office manager.

Here's an example using 4.0.0
```java
// Create an office manager using a specific template profile directory
OfficeManager officeManager = new DefaultOfficeManagerBuilder()
    .setTemplateProfileDir(new File("C:\\Users\\MyUser\\AppData\\Roaming\\LibreOffice\\4"))
    .build();
```

Of course it would be smart to copy this directory elsewhere.

If this doesn't work, I'm pretty sure that using a custom [Filter](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters) would do the trick. If you could send me a source file (without any sensitive content please!) with a TOC to update and a target pdf document with what you expect as a result, I could see if I'm able to get this done.

Using JODConverter, you can do pretty much anything that LibreOffice or Apache OpenOffice can do without JODConverter. It is simply a matter of finding how to do it programmatically.

**Comment by sbraconnier** [comment]
I just committed a new [TableOfContentUpdaterFilter](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/filter/text/TableOfContentUpdaterFilter.java) that can be used to update the TOC of a text document. To use it, just do (supposing you have an office manager installed):

```java
File inputFile = new File("document.docx");
File outputFile = new File("document.pdf");

LocalConverter.builder()
  .filterChain(new TableOfContentUpdaterFilter())
  .build()
  .convert(inputFile)
  .to(outputFile)
  .execute();
```
If you are working with the 4.0.0 release, copy the TableOfContentUpdaterFilter source file in you project and use it this way:

```java
OfficeDocumentConverter converter = ...

File inputFile = new File("document.docx");
File outputFile = new File("document.pdf");

FilterChain filterChain =
    new DefaultFilterChain(new TableOfContentUpdaterFilter(), RefreshFilter.INSTANCE);

// Convert
converter.convert(filterChain, inputFile, outputFile);
```

Hope this helps!

**Comment by fabiohast** [comment]
Thanks you, it worked like a charm! This filter functionality is great.
