### ISSUE TITLE
compling with LibreOffice

### ISSUE THREAD

**Issue by medi6** [sbraconnier/jodconverter#262]
hi,

I need to compile JodConverter with LibreOffice libs, because of installing OO jars makes my Guice
down (It's a Play project...), but works perfectly with LO jars.
But I've got some errors in compilation...

Guice down, juh 4.1.2 and jurt 4.1.2 are causing this :
`play.api.UnexpectedException: Unexpected exception[NoClassDefFoundError: com/medlib/metier/admin/MajBDService]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:169) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.6.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.6.jar:na]
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.6.jar:na]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[na:1.8.0_292]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_292]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_292]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_292]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_292]
Caused by: java.lang.NoClassDefFoundError: com/medlib/metier/admin/MajBDService
        at com.medisys.api.conf.BaseModuleGuice.configure(BaseModuleGuice.java:156) ~[bin/:na]
        at com.medisys.api.conf.DevModulesGuice.configure(DevModulesGuice.java:14) ~[bin/:na]
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
        at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177) ~[guice-4.0.jar:na]
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.0.jar:na]
        at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.0.jar:na]
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:96) ~[guice-4.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.0.jar:na]
        at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.0.jar:na]
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:126) ~[play_2.11-2.4.4.jar:2.4.4]
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:93) ~[play_2.11-2.4.4.jar:2.4.4]
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21) ~[play_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:153) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1$$anonfun$2.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.4.jar:2.4.4]
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.4.jar:2.4.4]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:150) ~[play-server_2.11-2.4.4.jar:2.4.4]
        ... 14 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.medlib.metier.admin.MajBDService
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_292]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_292]
        ... 35 common frames omitted`

Compilation error with -PuseLibreOffice :
`/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:27: error: package com.sun.star.beans does not exist
import com.sun.star.beans.XPropertySet;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:28: error: package com.sun.star.bridge does not exist
import com.sun.star.bridge.XBridge;
                          ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:29: error: package com.sun.star.bridge does not exist
import com.sun.star.bridge.XBridgeFactory;
                          ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:30: error: package com.sun.star.comp.helper does not exist
import com.sun.star.comp.helper.Bootstrap;
                               ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:31: error: package com.sun.star.connection does not exist
import com.sun.star.connection.XConnection;
                              ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:32: error: package com.sun.star.connection does not exist
import com.sun.star.connection.XConnector;
                              ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:33: error: package com.sun.star.frame does not exist
import com.sun.star.frame.XComponentLoader;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:34: error: package com.sun.star.frame does not exist
import com.sun.star.frame.XDesktop;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:35: error: package com.sun.star.lang does not exist
import com.sun.star.lang.EventObject;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:36: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:37: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XEventListener;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:38: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XMultiComponentFactory;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:39: error: package com.sun.star.uno does not exist
import com.sun.star.uno.XComponentContext;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:22: error: package com.sun.star.frame does not exist
import com.sun.star.frame.XComponentLoader;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:23: error: package com.sun.star.frame does not exist
import com.sun.star.frame.XDesktop;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:24: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XMultiComponentFactory;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:25: error: package com.sun.star.uno does not exist
import com.sun.star.uno.XComponentContext;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:51: error: cannot find symbol
public class OfficeConnection implements LocalOfficeContext, XEventListener {
                                                             ^
  symbol: class XEventListener
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeUrl.java:25: error: package com.sun.star.lib.uno.helper does not exist
import com.sun.star.lib.uno.helper.UnoUrl;
                                  ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:58: error: cannot find symbol
  private XComponent bridgeComponent;
          ^
  symbol:   class XComponent
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:59: error: cannot find symbol
  private XComponentContext componentContext;
          ^
  symbol:   class XComponentContext
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:60: error: cannot find symbol
  private XMultiComponentFactory serviceManager;
          ^
  symbol:   class XMultiComponentFactory
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:61: error: cannot find symbol
  private XComponentLoader componentLoader;
          ^
  symbol:   class XComponentLoader
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:209: error: cannot find symbol
  public void disposing(final @NonNull EventObject eventObject) {
                                       ^
  symbol:   class EventObject
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:231: error: cannot find symbol
  public @Nullable XComponentContext getComponentContext() {
                   ^
  symbol:   class XComponentContext
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:236: error: cannot find symbol
  public @Nullable XMultiComponentFactory getServiceManager() {
                   ^
  symbol:   class XMultiComponentFactory
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:241: error: cannot find symbol
  public @Nullable XComponentLoader getComponentLoader() {
                   ^
  symbol:   class XComponentLoader
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeConnection.java:246: error: cannot find symbol
  public @Nullable XDesktop getDesktop() {
                   ^
  symbol:   class XDesktop
  location: class OfficeConnection
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:39: error: cannot find symbol
  XComponentLoader getComponentLoader();
  ^
  symbol:   class XComponentLoader
  location: interface LocalOfficeContext
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:47: error: cannot find symbol
  XComponentContext getComponentContext();
  ^
  symbol:   class XComponentContext
  location: interface LocalOfficeContext
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:55: error: cannot find symbol
  XMultiComponentFactory getServiceManager();
  ^
  symbol:   class XMultiComponentFactory
  location: interface LocalOfficeContext
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeContext.java:63: error: cannot find symbol
  XDesktop getDesktop();
  ^
  symbol:   class XDesktop
  location: interface LocalOfficeContext
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeUrl.java:50: error: cannot find symbol
  private final UnoUrl unoUrl;
                ^
  symbol:   class UnoUrl
  location: class OfficeUrl
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeUrl.java:58: error: cannot find symbol
  /* default */ static UnoUrl pipe(final @NonNull String pipeName) {
                       ^
  symbol:   class UnoUrl
  location: class OfficeUrl
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeUrl.java:75: error: cannot find symbol
  /* default */ static UnoUrl socket(final int port) {
                       ^
  symbol:   class UnoUrl
  location: class OfficeUrl
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/OfficeUrl.java:86: error: cannot find symbol
  /* default */ static UnoUrl socket(final String host, final int port) {
                       ^
  symbol:   class UnoUrl
  location: class OfficeUrl
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:32: error: package com.sun.star.beans does not exist
import com.sun.star.beans.XHierarchicalPropertySet;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:33: error: package com.sun.star.beans does not exist
import com.sun.star.beans.XHierarchicalPropertySetInfo;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:34: error: package com.sun.star.frame does not exist
import com.sun.star.frame.XDesktop;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:35: error: package com.sun.star.lang does not exist
import com.sun.star.lang.DisposedException;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:36: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:37: error: package com.sun.star.uno does not exist
import com.sun.star.uno.XComponentContext;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:38: error: package com.sun.star.util does not exist
import com.sun.star.util.XChangesBatch;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeProcessManager.java:740: error: cannot find symbol
  private boolean checkForOpengl(final XComponentContext context) throws OfficeException {
                                       ^
  symbol:   class XComponentContext
  location: class LocalOfficeProcessManager
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:31: error: package com.sun.star.beans does not exist
import com.sun.star.beans.PropertyValue;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:32: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:33: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XServiceInfo;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:244: error: cannot find symbol
      final @NonNull XComponent document) {
                     ^
  symbol:   class XComponent
  location: class LocalOfficeUtils
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:270: error: cannot find symbol
  public static @NonNull DocumentFamily getDocumentFamily(final @NonNull XComponent document)
                                                                         ^
  symbol:   class XComponent
  location: class LocalOfficeUtils
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/LocalOfficeUtils.java:315: error: cannot find symbol
  public static @NonNull PropertyValue[] toUnoProperties(
                         ^
  symbol:   class PropertyValue
  location: class LocalOfficeUtils
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:24: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:25: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XMultiServiceFactory;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:26: error: package com.sun.star.uno does not exist
import com.sun.star.uno.Exception;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:27: error: package com.sun.star.uno does not exist
import com.sun.star.uno.XComponentContext;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:101: error: cannot find symbol
      final @NonNull XComponent component) {
                     ^
  symbol:   class XComponent
  location: class Lo
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:100: error: cannot find symbol
  public static @NonNull XMultiServiceFactory getServiceFactory(
                         ^
  symbol:   class XMultiServiceFactory
  location: class Lo
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:118: error: cannot find symbol
      final @NonNull XComponent component,
                     ^
  symbol:   class XComponent
  location: class Lo
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:141: error: cannot find symbol
      final @NonNull XMultiServiceFactory factory,
                     ^
  symbol:   class XMultiServiceFactory
  location: class Lo
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Lo.java:168: error: cannot find symbol
      final @NonNull XComponentContext context,
                     ^
  symbol:   class XComponentContext
  location: class Lo
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Write.java:22: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Write.java:23: error: package com.sun.star.text does not exist
import com.sun.star.text.XTextDocument;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Write.java:41: error: cannot find symbol
  public static boolean isText(final @NonNull XComponent document) {
                                              ^
  symbol:   class XComponent
  location: class Write
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Write.java:51: error: cannot find symbol
  public static @Nullable XTextDocument getTextDoc(final @Nullable XComponent document) {
                                                                   ^
  symbol:   class XComponent
  location: class Write
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Write.java:51: error: cannot find symbol
  public static @Nullable XTextDocument getTextDoc(final @Nullable XComponent document) {
                          ^
  symbol:   class XTextDocument
  location: class Write
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:22: error: package com.sun.star.beans does not exist
import com.sun.star.beans.PropertyValue;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:23: error: package com.sun.star.beans does not exist
import com.sun.star.beans.UnknownPropertyException;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:24: error: package com.sun.star.beans does not exist
import com.sun.star.beans.XPropertySet;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:25: error: package com.sun.star.lang does not exist
import com.sun.star.lang.WrappedTargetException;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:62: error: cannot find symbol
      final @NonNull XPropertySet props, final @NonNull String propName) {
                     ^
  symbol:   class XPropertySet
  location: class Props
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:78: error: cannot find symbol
  public static @NonNull PropertyValue makeProperty(
                         ^
  symbol:   class PropertyValue
  location: class Props
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:95: error: cannot find symbol
  public static @NonNull PropertyValue[] makeProperties(
                         ^
  symbol:   class PropertyValue
  location: class Props
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:111: error: cannot find symbol
  public static @NonNull PropertyValue[] makeProperties(
                         ^
  symbol:   class PropertyValue
  location: class Props
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Props.java:128: error: cannot find symbol
  public static @NonNull PropertyValue[] makeProperties(
                         ^
  symbol:   class PropertyValue
  location: class Props
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Calc.java:22: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Calc.java:23: error: package com.sun.star.sheet does not exist
import com.sun.star.sheet.XSpreadsheetDocument;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Calc.java:41: error: cannot find symbol
  public static boolean isCalc(final @NonNull XComponent document) {
                                              ^
  symbol:   class XComponent
  location: class Calc
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Calc.java:52: error: cannot find symbol
  public static @Nullable XSpreadsheetDocument getCalcDoc(final @Nullable XComponent document) {
                                                                          ^
  symbol:   class XComponent
  location: class Calc
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Calc.java:52: error: cannot find symbol
  public static @Nullable XSpreadsheetDocument getCalcDoc(final @Nullable XComponent document) {
                          ^
  symbol:   class XSpreadsheetDocument
  location: class Calc
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:26: error: package com.sun.star.beans does not exist
import com.sun.star.beans.XPropertySet;
                         ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:27: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XComponent;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:28: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XMultiServiceFactory;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:29: error: package com.sun.star.lang does not exist
import com.sun.star.lang.XServiceInfo;
                        ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:30: error: package com.sun.star.uno does not exist
import com.sun.star.uno.Exception;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:31: error: package com.sun.star.uno does not exist
import com.sun.star.uno.XComponentContext;
                       ^
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:94: error: cannot find symbol
      final @NonNull XComponent document, final @NonNull String documentType) {
                     ^
  symbol:   class XComponent
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:107: error: cannot find symbol
  public static boolean isOpenOffice(final @NonNull XComponentContext context) {
                                                    ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:120: error: cannot find symbol
  public static boolean isLibreOffice(final @NonNull XComponentContext context) {
                                                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:132: error: cannot find symbol
  public static @Nullable String getOfficeName(final @NonNull XComponentContext context) {
                                                              ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:144: error: cannot find symbol
  public static @Nullable String getOfficeVersionLong(final @NonNull XComponentContext context) {
                                                                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:156: error: cannot find symbol
  public static @Nullable String getOfficeVersionShort(final @NonNull XComponentContext context) {
                                                                      ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:170: error: cannot find symbol
      final @NonNull XComponentContext context, final @NonNull String propName) {
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:192: error: cannot find symbol
      final @NonNull XComponentContext context,
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:211: error: cannot find symbol
      final @NonNull XComponentContext context, final @NonNull String nodePath) {
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:210: error: cannot find symbol
  public static @Nullable XPropertySet getConfigProperties(
                          ^
  symbol:   class XPropertySet
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:223: error: cannot find symbol
      final XComponentContext context, final String serviceSpecifier, final String nodePath) {
            ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:250: error: cannot find symbol
      final @NonNull XComponentContext context, final @NonNull String nodePath) {
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:262: error: cannot find symbol
      final @NonNull XComponentContext context, final @NonNull String nodePath) {
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:287: error: cannot find symbol
      final @NonNull XComponentContext context) {
                     ^
  symbol:   class XComponentContext
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/Info.java:286: error: cannot find symbol
  private static @Nullable XMultiServiceFactory getConfigProvider(
                           ^
  symbol:   class XMultiServiceFactory
  location: class Info
/home/druty/dev/jodconverter/jodconverter/jodconverter-local/src/main/java/org/jodconverter/local/office/utils/WrappedUnoException.java:38: error: package com.sun.star.uno does not exist
      final @NonNull String message, final com.sun.star.uno.Exception cause) {`
      
Thanks for all,

**Comment by sbraconnier** [comment]
Yeah, I just found out recently that libre office has bundled its set of libraries, and the old maven references are still there, but empty (what's the point?)...

Anyway, maybe you could add the jonverter reference with an exclude set to exclude the OO references, and then add this new (single one) libreoffice reference:

https://mvnrepository.com/artifact/org.libreoffice/libreoffice

Hope that helps!

**Comment by medi6** [comment]
Oh yes thanks, 

I've made some bad code to fix this, and it's OK :

Old deps :
`  public static final String loJuh = "org.libreoffice:juh:" + loVersion;
  public static final String loJurt = "org.libreoffice:jurt:" + loVersion;
  public static final String loRidl = "org.libreoffice:ridl:" + loVersion;
  public static final String loUnoil = "org.libreoffice:unoil:" + loVersion;`

new deps :
`  public static final String loJuh = "org.libreoffice:libreoffice:" + loVersion;
  public static final String loJurt = "org.libreoffice:libreoffice:" + loVersion;
  public static final String loRidl = "org.libreoffice:libreoffice:" + loVersion;
  public static final String loUnoil = "org.libreoffice:libreoffice:" + loVersion;`
  
  Thanks !!!!

**Comment by sbraconnier** [comment]
It would be preferable to just add:

`public static final String libreoffice = "org.libreoffice:libreoffice:" + loVersion;`

and change the build.gradle of the jodconverter-local module this way:

```
    if (project.hasProperty("useLibreOffice")) {
        api Deps.libreoffice
    } else {
        api Deps.ooJuh
        api Deps.ooJurt
        api Deps.ooRidl
        api Deps.ooUnoil
    }
```

**Comment by sbraconnier** [comment]
Fixed in the next version.
