### ISSUE TITLE
How to use FilterChain in webapp using OfficeManager???

### ISSUE THREAD

**Issue by molinarp69** [sbraconnier/jodconverter#263]
Hi,

I wrote a webapp following the example shown in the documentation but I would like to convert only the first pages of the source documents, using the PagesSelectorFilter.

I saw that the filterChain method belongs to the LocalConverter.Builder class which is not part of the creation of the LocalConverter. In fact, the LocalConverter is created using the static method LocalConverter.make (officeManager), having built the OfficeManager with the desired parameters.

How can I go about using the filter or do you have any idea how I can solve my functional problem???

Thanks!!!

Paolo

----

Prepare in WebappContext:

_private final OfficeManager officeManager;    
private final DocumentConverter documentConverter;
final LocalOfficeManager.Builder builder = LocalOfficeManager.builder();
// ... here set cgf params....
officeManager = builder.build();
documentConverter = LocalConverter.make(officeManager);_

----

Use in business method:

_final DocumentConverter converter = webappContext.getDocumentConverter();
converter.convert(inputFile).to(outputFile).execute();_

**Comment by sbraconnier** [comment]
You can do:

`documentConverter = LocalConverter.builder().officeManager(officeManager).build();`
