### ISSUE TITLE
The address www.jodconverter.org redirects to malware

### ISSUE THREAD

**Issue by benjarrell** [sbraconnier/jodconverter#266]
The link to www.jodconverter.org should be removed from the project info, it is redirecting to malware domains.

**Comment by sbraconnier** [comment]
Totally... I finally decided to stop paying for the jodconverter.org domain. Last bill was 600$!!! Last year donation was 50$ (thanks btw to the donators). After 3 years like that and more experience, I decided it was time to move to the github domain. But I didn't have the time to do it just yet... Thanks for your comment!

**Comment by sbraconnier** [comment]
I'll let the issue opened so others could be informed of my plan until it's done (maybe someone will help me keep the org domain :)).

**Comment by s-jetter** [comment]
The link to _www.jodconverter.org_ still exists in the Wiki on the LICENSE page.

**Comment by sbraconnier** [comment]
@s-jetter Fixed... thanks!
