### ISSUE TITLE
No response for pdf converter when more requests

### ISSUE THREAD

**Issue by sulthans** [sbraconnier/jodconverter#267]
I am new to jodconverter for openoffice, i am facing issue while converting docx to pdf. 
Response not received for docx to pdf when load is high, when request is 2000 success is 100, faliure is close to 1000 and for remaining no status. Text to pdf got all responses whether it's success or failure.

 I can see logs for both, "Executing default conversion task" and "Reached limit of 120 maximum tasks per process; restarting..." Why i am seeing both here?

**Configuration and Code available for both doc/text to pdf:**

pdfconverter.openOffice.maxTasksPerProcess=140
pdfconverter.openOffice.retryTimeout=1200000
pdfconverter.openOffice.connectionProtocol=SOCKET
pdfconverter.ooInstances.portNumbers=18900,18901,18902
pdfconverter.ooInstances.taskExecutionTimeOut=10000
pdfconverter.ooInstances.taskQueueTimeout=30000
pdfconverter.ooInstances.minportrange=18900
pdfconverter.ooInstances.maxportrange=19000
pdfconverter.ooInstances.instance=2

         
`final Date dateBef = new Date();
            final OfficeDocumentConverter converter = new OfficeDocumentConverter(officeManager);
            final DocumentFormat customFormat = getDocumentFormat();
            converter.convert(inputFile, outputFile, customFormat);`

Log sequence from down to botttom :

   logger: org.jodconverter.office.PooledOfficeManager
   message: Connection lost unexpectedly; attempting restart

logger: org.jodconverter.office.OfficeConnection
   message: Disconnected: 'socket,host=127.0.0.1,port=18901,tcpNoDelay=1'
   thread: MessageDispatcher

  logger: org.jodconverter.DefaultConversionTask
   message: Executing default conversion task...

logger: org.jodconverter.office.OfficeConnection
   message: Connected: 'socket,host=127.0.0.1,port=18901,tcpNoDelay=1'

logger: org.jodconverter.office.OfficeProcess
   message: Started process; pid = 13112

logger: org.jodconverter.office.OfficeProcess
   message: Starting process with acceptString 'socket,host=127.0.0.1,port=18900,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-18900_tcpNoDelay-1'
  
logger: org.jodconverter.office.ConnectRetryable
   message: Office process died with exit code 81; restarting it

**Comment by sbraconnier** [comment]
Hi there,

I have a couple of questions in order to help you...

Whare aree those properties? :

```
pdfconverter.openOffice.maxTasksPerProcess=140
pdfconverter.openOffice.retryTimeout=1200000
pdfconverter.openOffice.connectionProtocol=SOCKET
pdfconverter.ooInstances.portNumbers=18900,18901,18902
pdfconverter.ooInstances.taskExecutionTimeOut=10000
pdfconverter.ooInstances.taskQueueTimeout=30000
pdfconverter.ooInstances.minportrange=18900
pdfconverter.ooInstances.maxportrange=19000
pdfconverter.ooInstances.instance=2
```

They don't come from jodconvetrer, so I wonder how exactly office managers are created. According to your logs, the  `maxTasksPerProcess` of 140 doesn't seem to be applied (you see `Reached limit of 120 maximum tasks per process; restarting...` in your log file)... Please explain or show how exactly office managers are created. What is this: `pdfconverter.ooInstances.minportrange`? and this `pdfconverter.ooInstances.maxportrange`? and this `pdfconverter.ooInstances.instance`? and... etc...

> logger: org.jodconverter.office.ConnectRetryable
> message: Office process died with exit code 81; restarting it

This is a know issue with OOo when the user environment doesn't exist on start. See:
https://code.google.com/archive/p/jodconverter/issues/84

JodConverter will just restart the process, so this error can be ignored.

Finally, I will need a sample project I can work with that reproduces the problem in order to be able to fix the issue. Could you please create a small github project with all the minimal stuff required to reproduce the issue.

**Comment by sulthans** [comment]
Sorry, it's 120 actually I tried to increase it and posted here. Not sure why the port ranges configured.

We are setting all properties values in DefaultOfficeManagerBuilder.

here is the code for creating office manager,

`
@PostConstruct
    public void init() {
    final DefaultOfficeManagerBuilder defaultOfficeManagerConfiguration = new DefaultOfficeManagerBuilder();
        final Path currentRelativePath = Paths.get("");
       
            maxTasksPerProcess = Integer.parseInt(openOfficeMap.get("maxTasksPerProcess"));

            defaultOfficeManagerConfiguration.setMaxTasksPerProcess(maxTasksPerProcess);

   officeManager = defaultOfficeManagerConfiguration.build();
        try {
            officeManager.start();
        } catch (OfficeException e) {
            LOGGER.error("Exception starting officeManager", e);
        }
`

**This is a know issue with OOo when the user environment doesn't exist on start. See:** - if any request during the time cannot be processed? What will happen if Pooled office manager process in progress?

I will create a sample project and share.

**Comment by sbraconnier** [comment]
Did you had time to create a sample project ?

**Comment by sulthans** [comment]
I couldn't create a sample project but i added logs for exception from jod-converter,

**Could not open document.
Could not store document - errorCode: 1287 & 2074
Task failed .
task did not complete within timeout** - is 90% of failure cause from exception log.


Any modification in config could be done to reduce the pdf conversion error ?

Current configuration for openoffice,

**pdfconverter.openOffice.maxTasksPerProcess=120
pdfconverter.ooInstances.taskExecutionTimeOut=10000
pdfconverter.ooInstances.taskQueueTimeout=30000**

**Comment by sulthans** [comment]
@sbraconnier , Any config change will help to resolve it?

**Comment by sbraconnier** [comment]
@sulthans Well, 10000 (10 seconds) for taskExecutionTimeOut seems wuite short.

I would really need a sample project to work on this one.
