### ISSUE TITLE
support keepAliveOnShutdown through CLI

### ISSUE THREAD

**Issue by andreasnef** [sbraconnier/jodconverter#269]
Currently, when using the CLI for conversions, the OO instance is terminated after each command which is not very efficient.

Given that the [existingProcessAction](https://github.com/sbraconnier/jodconverter/wiki/Configuration#capital_abcdexistingprocessaction) and [keepAliveOnShutdown](https://github.com/sbraconnier/jodconverter/wiki/Configuration#white_check_markkeepaliveonshutdown) exist, is there anything that would prevent the cli from supporting the keepAliveOnShutdown flag?

**Comment by sbraconnier** [comment]
Thanks for your suggestion. I don't see why we couldn't do that.

**Comment by sbraconnier** [comment]
Done in the next version.

**Comment by lennartb-** [comment]
Apparently this has already been released, but I can't figure out how to get this to work. It's not mentioned on the [configuration page](https://github.com/jodconverter/jodconverter/wiki/Command-Line-Tool), and simply passing it as an argument doesn't seem to work, as it's treated as an unknown argument. I'm trying to pass it to the `jodconverter-cli.bat` if that matters.
