### ISSUE TITLE
gradle build faild with libreoffice 7.1.5

### ISSUE THREAD

**Issue by zz-hulatang** [sbraconnier/jodconverter#271]
### gradle build faild with libreoffice 7.1.5

the error msg :
`Package com.sun.star.beans does not exist
import com.sun.star.beans.XPropertySet;`

The reason for this error is org.libreoffice: juh-7.1.5.jar, jurt-7.1.5.jar, ridl-7.1.5.jar, unoil-7.1.5.jar, these four jar packages are empty .

I got this from [https://wiki.documentfoundation.org/ReleaseNotes/7.0#Java_support](url) or [https://wiki.documentfoundation.org/ReleaseNotes/7.0/zh-cn#Java_.E6.94.AF.E6.8C.81](url)

![image](https://user-images.githubusercontent.com/14270371/136537789-ca08f3de-5036-4217-ac7a-938758ca8459.png)

So the solution to this problem：

- Deps.java add `public static final String libreoffice = "org.libreoffice:libreoffice:" + loVersion;`
- jodconverter-local build.gradle add `api Deps.libreoffice` under the `if (project.hasProperty("useLibreOffice")) {`

**Comment by sbraconnier** [comment]
Fixed in the next version
