### ISSUE TITLE
JodConverter + LibreOffice Performance issue

### ISSUE THREAD

**Issue by mrderban** [sbraconnier/jodconverter#277]
Hi everyone,

I'm currently encountering a performance issue regarding file conversion (e.g xls -> xlsx...) using jodconverter and libreOffice on a localhost conversion setup.

Basically the process takes an awful lot of time to complete (about 2 mins for a single standard file, xls, xlsx, doc, docx ... no matter the format).
By running a profiler i was able to figure out that the execution is hanging in the run method of the StreamPumper class.
The default host value is used (127.0.0.1) to initiate the socket.

Do you guys have any ideas on what could be going on / what diagnostics i should run next ?

Thanks a bunch !

My localhost environment:

**- Windows Server 2012 R2
- LibreOffice  7.1.0.3 (x64)
- AdoptOpenJDK  1.8.0_282-b08 x64
- JodConverter 4.2.2**

**Comment by sbraconnier** [comment]
Sorry for the late answer. Do you still have this issue?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
