### ISSUE TITLE
ExternalOfficeManager does not work

### ISSUE THREAD

**Issue by wq163** [sbraconnier/jodconverter#278]
![image](https://user-images.githubusercontent.com/1230366/146386094-85846772-a71f-4cd9-be8f-4775b2802b3b.png)

![image](https://user-images.githubusercontent.com/1230366/146384869-1079b956-3579-4ecd-83d8-3978c95a8b07.png)

But,when i replace `192.168.1.4` to `127.0.0.1` ,it works. 
192.168.1.4 is remote host, running with `soffice --accept="socket,host=0.0.0.0,port=8100,tcpNoDelay=1;urp;StarOffice.ServiceManager" --headless  --invisible --nocrashreport --nodefault --nofirststartwizard --nolockcheck --nologo --norestore`

**Comment by chladic** [comment]
@wq163 Did you manage to solve this somehow ?

**Comment by sbraconnier** [comment]
Will be fixed in the next version, which will be released later this week.
