### ISSUE TITLE
excel -> pdf 

### ISSUE THREAD

**Issue by chenlei0615** [sbraconnier/jodconverter#279]
When there are multiple sheets in Excel, how can I display the sheet name in Excel on PDF

**Comment by sbraconnier** [comment]
You may want to consider taking a look at the [Filters](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters) wiki page to create a custom filter for you needs. 

You have some implementation examples [here](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-local/src/main/java/org/jodconverter/local/filter).

Unfortunately, I'm not an expert when it comes to the UNO API per say, so it would require a lot of time for me to find the solution for you. You may want to take a look at the examples provided by LibreOffice:
https://api.libreoffice.org/examples/examples.html#Java_examples

There is plenty of examples online. If you ever create a filter for your needs, please consider sharing it with us :)
