### ISSUE TITLE
docx ->pdf

### ISSUE THREAD

**Issue by chenlei0615** [sbraconnier/jodconverter#280]
My word document has 9 pages and 10 pages after being converted into PDF. What should I do

**Comment by sbraconnier** [comment]
Can you provide an example  (sample) document ?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
