### ISSUE TITLE
pptx->pdf org.jodconverter.local.office.VerboseProcess : malloc(): invalid size (unsorted)

### ISSUE THREAD

**Issue by rrchx** [sbraconnier/jodconverter#281]
OS：Centos8.0
PPT file contains a large number of high color bit pictures, about 20 pieces。
When used 【LocalConverter.convert(inputFile).to(outputFile).execute()】，throw exception like this “org.jodconverter.local.office.VerboseProcess : malloc(): invalid size (unsorted)”。
PPT file szie is 3.5M.

**Comment by sbraconnier** [comment]
Well. It seems to be related to LibreOffice/OpenOffice. Can you convert the document without JodConverter?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
