### ISSUE TITLE
Convert docx pptx To jpg

### ISSUE THREAD

**Issue by Sunset-Avenue** [sbraconnier/jodconverter#283]
Hello, thank you very much for your work. I encountered some problems when I tried to convert docx and ppt documents into jpg images. The converted image is only the first page of the document. How can I specify a folder to output all converted pictures to this folder? By asynchronously loading the converted pictures, the online preview of the document can have a better user experience. Look forward to your reply.

```
DocumentFormat jpg = DocumentFormat.builder()
                .name("Joint Photographic Experts Group").extension("jpg").mediaType("image/jpeg")
                .storeProperty(DocumentFamily.TEXT, "FilterName", "writer_jpg_Export")
                .storeProperty(DocumentFamily.PRESENTATION, "FilterName", "impress_jpg_Export")
                .build();

File officeHome = new File("D:\\office-plugin\\windows-office");
  OfficeManager officeManager = LocalOfficeManager
          .builder()
          .officeHome(officeHome)
          .portNumbers(2001)
          .install()
          .build();
  officeManager.start();

  Map<String, Object> loadProperties = new HashMap<>();
  loadProperties.put("Hidden", true);
  loadProperties.put("ReadOnly", true);
  loadProperties.put("UpdateDocMode", UpdateDocMode.QUIET_UPDATE);
  loadProperties.put("CharacterSet", StandardCharsets.UTF_8.name());
  DocumentConverter converter = LocalConverter
          .builder()
          .officeManager(officeManager)
          .loadProperties(loadProperties)
          .formatRegistry(new OfficePluginExtendFormatRegistry())
          .build();

  File inputFile = new File("D:\\file\\test.docx");
  File outputFile = new File("D:\\server\\src\\main\\file\\test.jpg");
  try {
      // converter.convert(inputFile, outputFile);
      converter.convert(inputFile).to(outputFile).execute();
  } catch (OfficeException exception) {
      exception.printStackTrace();
  }
  officeManager.stop();
```

**Comment by sbraconnier** [comment]
Sorry for this late anwser...

Well, I just tried what you are trying to do without JODConverter (with LibreOffice only using the File/Export menu) and the result if the same (only the first page is exported).

JODConverter can only do what is doable using only LibreOffice (or OpenOffice).

I found an old question that is similar to yours for which I provided an example showing how you could do that, but it's not super clean :)

https://github.com/sbraconnier/jodconverter/issues/109#issuecomment-437961441
