### ISSUE TITLE
Error appears randomly when converting docx to xhtml.

### ISSUE THREAD

**Issue by eddyonboard** [sbraconnier/jodconverter#285]
I'm trying to convert docx, xlsx files to xhtml. 
In most cases, the conversion is correct, but sometimes the jodconverter gives an error.

Command called from php through `exec` and looks like this:
`timeout 300 path/to/jodconverter-cli -p 8100 "/path/to/input/file/example.docx" "/path/to/output/file/example.xhtml" 2>&1`

It looks like the extensions of incoming and outgoing files don't matter.
I get an error randomly:

![ec8901766a28bbbc505c4c6462bc55a8](https://user-images.githubusercontent.com/21238475/155128335-bc34388c-73d2-41db-b89e-1cff4a70ade2.png)

Has anyone experienced such a problem?
I can share more details if anyone is willing and able to help.

**Comment by sbraconnier** [comment]
Sorry for the late anwser. Do you still have this problem?

What is the LO/OO version you are using?

Do you have a sample document I could work with to reproduce the issue.

Thanks.

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
