### ISSUE TITLE
Font style error after xhtml to doc

### ISSUE THREAD

**Issue by dihuantian** [sbraconnier/jodconverter#288]
After I convert the doc document to xhtml, and then convert the xhtml font to doc, the font style can be re-styled the same as the original. I'm using LibreOffice and only the "<font>" tag can reproduce the style.

Only in xhtml there is such a tag "<font face='cursive'>" , the corresponding font style can be generated when converting to doc.

**Comment by sbraconnier** [comment]
Sorry for the late anwser. Do you still have this problem?

What is the LO/OO version you are using?

Do you have a sample document I could work with to reproduce the issue.

Thanks.

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
