### ISSUE TITLE
remote manager support for openoffice

### ISSUE THREAD

**Issue by busishe** [sbraconnier/jodconverter#289]
i have read the wiki,but didnt find a guide how to connect to remote openoffice service .
Does this version only support local access? (4.4.2)

**Comment by sbraconnier** [comment]
Sorry for the long delay. Could you please explain what you are trying to do ?? There is 2 ways jodconverter can be use remotely (well, there will be 2 ways in the next version). Please explain what you are trying to do and I'll tell you if jodconverter supports it.

**Comment by sbraconnier** [comment]
See [here](https://github.com/sbraconnier/jodconverter/wiki/Migration-Guide-4.4.5)

**Comment by busishe** [comment]
thx！
