### ISSUE TITLE
Improve documentation for LibreOffice Portable Support

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#29]
The documentation (Wiki) should offer a complete guide on how to use JODConverter along with LibreOffice Portable.

See #28 as a starting point.

**Comment by benelot** [comment]
Some important notes on how to use Libreoffice Portable with JODConverter:
-The main problem occurring is that your Libreoffice settings contain machine/OS specific settings. Therefore it is usually the case that if you distribute Libreoffice Portable with your software together with your preferred settings, that the settings work on one machine, but cause Libreoffice to crash on another machine. To solve this problem, use the safe mode of Libreoffice to factory reset the settings, then close it and make a copy of the settings. Then restart Libreoffice normally with the GUI, select your preferred settings, then close Libreoffice again. The settings will end up in registrymodifications.xcu. Unfortunately, Libreoffice adds a lot of extra settings to the rest of the settings in the folder, therefore you just copy the registrymodifications.xcu to your factory resetted settings copy you made before changing the settings. The registrymodifications.xcu will contain some extra settings you did not select (as a good dev, you might want to clean them out until they are only the ones you selected explictly for better maintenance). However, the extra settings are not machine dependent and thus cause no crash.

**Comment by benelot** [comment]
-Libreoffice Portable can be used like an installed Libreoffice. Just set the libreoffice home of JODConverter to LibreofficePortable/App/libreoffice to make it use the soffice.exe and such, it is not required to make JODConverter use the LibreofficePortable*.exe. The latter will even cause cleanup-problems, because JODConverter terminates the binary but Libreoffice Portable does not clean up properly (We tried to make this work for weeks:)).

**Comment by benelot** [comment]
-It is important that you do not have a Libreoffice installed on your machine aside from the Libreoffice Portable you are using. This will make your settings work flawlessly with Libreoffice Portable (everything will work great all the time), but as you transfer to another machine with Libreoffice installed, things will not work anymore. So your developer machine should have no Libreoffice installed, just as your testing computer should not have one installed. This saves you a lot of time debugging spurious problems.

**Comment by sbraconnier** [comment]
Wow. Thanks a lot for your help. I'll move these notes to the main Wiki of JODConverter!

**Comment by benelot** [comment]
I realized during work that we had gone through a lot of tinkering and testing to get this to work. Now that it works, it feels to seamless and easy, but luckily I remembered the hard times we had gone through to get were we are now. That is why I thought I should take the time to write it down here to avoid this work to be repeated for us and other people trying to do the same.

**Comment by sbraconnier** [comment]
All the documentation has been copied into the wiki.
