### ISSUE TITLE
org.jodconverter.core.office.OfficeException: Office process died with exit code 137

### ISSUE THREAD

**Issue by pczebra** [sbraconnier/jodconverter#298]
I'm trying to convert word to pdf on linux with libreoffice7.1, but it has following errors.

OFFICE HOME: /opt/libreoffice7.1
 Starting process with --accept 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1'
 Started process; pid: 218332
 Office process died with exit code 81

Could not restart process after connection lost.
org.jodconverter.core.office.OfficeException: Office process died with exit code 137
Caused by: org.jodconverter.local.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1'; java.net.ConnectException: 拒绝连接 (Connection refused)

How can i solve this problem? Thx

**Comment by sbraconnier** [comment]
Sorry for the late anwser. Are you still having this problem ? It seems to be related to insufficient memory on linux. Are you running LO on a virtual machine or something like that?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
