### ISSUE TITLE
Encoding support

### ISSUE THREAD

**Issue by evserykh** [sbraconnier/jodconverter#30]
@sbraconnier are you going to support your branch? 
Do you know does OO/jodconverter support converting with setting output file's encoding?

**Comment by sbraconnier** [comment]
@evserykh Sure I am. I'm about to release the next version. of JODConverter. It should be out within a week.

Not sure I understand your question. But everything you can do using OO only (without JODConverter) is doable with JODConverter. We just have to figure out how to do it programmatically.

What are you tryinh to do exactly ? (what is you input and output format?).

**Comment by evserykh** [comment]
Sounds great, it would be amazing 👍

Let me explain what I mean. For example I have a csv file in cp1251 encoding and I want to convert it to a xls file. Using OO I have to open the csv file and select file's encoding to have it properly showed. Do you know is it possible to set input file's encoding for converting requests to jodconverter?

**Comment by sbraconnier** [comment]
OK got it.

First, take a look at [this wiki page](https://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options) to understand what I'm about to explain.

The default filter options applied when a csv file is imported is `44,34,0`, which means comma as field separator, " as text delimiter and system encoding as file encoding.

What you want, according to [this table](https://wiki.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options#Filter_Options_for_Lotus.2C_dBase_and_DIF_Filters), is `44,34,34`.

You can change these default options by forcing a custom format as source format:

Using the latest master:
```java
File inputFile = new File("document.csv");
File outputFile = new File("document.xls");

DocumentFormat csv = DocumentFormat.copy(DefaultDocumentFormatRegistry.CSV);
csv.getLoadProperties().put("FilterOptions", "44,34,34");

JodConverter.convert(inputFile).as(csv).to(outputFile).execute();
```
Using the 4.0.0 version:
```java
OfficeDocumentConverter converter = ...

File inputFile = new File("document.csv");
File outputFile = new File("document.xls");

final DocumentFormatRegistry registry = DefaultDocumentFormatRegistry.create();
DocumentFormat inputFormat = registry.getFormatByExtension("csv");
DocumentFormat outputFormat = registry.getFormatByExtension("xls");

inputFormat.getLoadProperties().put("FilterOptions", "44,34,34");
converter.convert(inputFile, outputFile, inputFormat, outputFormat);
```

Note that I didn't test this but it should work as expected...

**Comment by evserykh** [comment]
@sbraconnier thanks a lot. I got what you meant, but I use jodconverter web app. I asked whether can I modify my requests to jodconverter web app to set input file's encoding.

**Comment by sbraconnier** [comment]
Hmm...

Do you mean you use the [jodconverter-sample-webapp](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-webapp) sample ?

If yes, my answer remains the same. The sample webapp is... well, just a sample. It is not too hard to send request parameters through a web request. You could add a drop down list of available encoding and send the selected option to the server using a request parameter (see [query string](https://www.wikiwand.com/en/Query_string)). Server side, you would retrieve the request parameter using [ServletRequest#getParameter](http://docs.oracle.com/javaee/7/api/javax/servlet/ServletRequest.html#getParameter-java.lang.String-) and then use the retrieved encoding as shown in my previous answer.
