### ISSUE TITLE
How to open a password protected file?

### ISSUE THREAD

**Issue by oliviercailloux** [sbraconnier/jodconverter#301]
Hi,

I can’t find out how to open a password protected file. I found some examples on the web using DocumentFormat#setProperties, or similar methods, but they seem to have been removed from the more recent API; and I am not sure that this is the official approach as I can’t find anything related to this use case in the Javadoc.

Thanks for any help!

**Comment by sbraconnier** [comment]
Hi there. Sorry for the late answer.

I'm not sure what you mean ? Are you talking about opening a PDF file? Can you please provide a source document I could work with which would be password-protected?

**Comment by oliviercailloux** [comment]
I meant, a password-protected ODT. My documents are private but any [password-protected document](https://rshankar.com/how-to-password-protect-a-open-office-document/) could serve as an example.

**Comment by oliviercailloux** [comment]
For completeness, here is the code that I use to convert an ODT file to txt.
```java
public void toTxt(InputStream in, OutputStream out) throws OfficeException, IOException {
  OfficeManager manager = LocalOfficeManager.builder().maxTasksPerProcess(0).startFailFast(true).build();
  manager.start();
  LocalConverter converter = LocalConverter.builder().officeManager(manager).build();
  ConversionJobWithOptionalSourceFormatUnspecified task = converter.convert(in);
  ConversionJobWithRequiredTargetFormatUnspecified jobOut = task.to(out);
  ConversionJob job = jobOut.as(DefaultDocumentFormatRegistry.TXT);
  job.execute();
}
```
It works fine except for password-protected documents.

**Comment by sbraconnier** [comment]
Oh I see...

Could you try this:

```java
public void toTxt(InputStream in, OutputStream out) throws OfficeException, IOException {
  OfficeManager manager = LocalOfficeManager.builder().maxTasksPerProcess(0).startFailFast(true).build();
  manager.start();
  LocalConverter converter = LocalConverter.builder().officeManager(manager).build();
  ConversionJobWithOptionalSourceFormatUnspecified task = converter.convert(in);
  ConversionJobWithSourceSpecified jobIn = task.as(DocumentFormat.builder().from(DefaultDocumentFormatRegistry.ODT).loadProperty("Password", "test").build());
  ConversionJobWithRequiredTargetFormatUnspecified jobOut = jobIn.to(out);
  ConversionJob job = jobOut.as(DefaultDocumentFormatRegistry.TXT);
  job.execute();
}
```

If it works, then you may want to add an argument to your function in order to identify the document format of the input stream and do this only for odt documents.

**Comment by oliviercailloux** [comment]
Thanks! I cannot try it easily now because I don’t have these documents handy at the moment, but this certainly seem to fill my need.

Please consider documenting this somewhere. I remember having searched a lot in the Javadoc but couldn’t find out how to supply the password.

**Comment by sbraconnier** [comment]
I'll create a FAQ entry. This is not something specific to JODConverter (behavior may change according to the LO/OO version being used under the hood), and there are others properties that can be set:
https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1document_1_1MediaDescriptor.html

Another way you could do it without knowing the input format:

```java
public void toTxt(InputStream in, OutputStream out) throws OfficeException, IOException {
  OfficeManager manager = LocalOfficeManager.builder().maxTasksPerProcess(0).startFailFast(true).build();
  manager.start();
  Map<String, Object> loadProperties = new HashMap<>(LocalConverter.DEFAULT_LOAD_PROPERTIES);
  loadProperties.put("Password", "myPassword");
  LocalConverter converter = LocalConverter.builder().officeManager(manager).loadProperties(loadProperties).build();
  ConversionJobWithOptionalSourceFormatUnspecified task = converter.convert(in);
  ConversionJobWithRequiredTargetFormatUnspecified jobOut = task.to(out);
  ConversionJob job = jobOut.as(DefaultDocumentFormatRegistry.TXT);
  job.execute();
}
```
