### ISSUE TITLE
java.lang.NullPointerException: Could not open document: tempfile_0

### ISSUE THREAD

**Issue by sukang00** [sbraconnier/jodconverter#302]
![image](https://user-images.githubusercontent.com/21122462/183552120-de7afc4c-8037-455b-bc71-284f2614a984.png)
How to solve？

**Comment by sbraconnier** [comment]
It seems like tempfile_0 does not exist. Do you still have this problem?

**Comment by sbraconnier** [comment]
I'll close this one for now due to inactivity. Feel free to reopen it if required. If you reopen it, please provide a sample project and document I could work with to reproduce the issue. Thanks.
