### ISSUE TITLE
Supporting math

### ISSUE THREAD

**Issue by Opussci** [sbraconnier/jodconverter#304]
For the record, it would be quite useful for our purposes (education) if Jodconverter could convert HTML with equations (MathML or LaTeX) to docx with editable equations.
Would this be possible?

**Comment by csdbianhua** [comment]
This should be the feature of OpenOffice/LibreOffice instead of JodConverter. I think JodConverter is mainly to manage these *office processes.

**Comment by sbraconnier** [comment]
@csdbianhua is right. What JODConverter can do is limited by what LibreOffice/OpenOffice can do.

If you can do something without JodConverter, then you can also do it with JodConverter, but it may be quite a challenge if it requires a lot of operations to transform the source document.

See [Using Filters](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters)
