### ISSUE TITLE
Is jodconverter-online published?

### ISSUE THREAD

**Issue by antonleliuk** [sbraconnier/jodconverter#31]
I can't find jodconverter-online in maven repository

**Comment by sbraconnier** [comment]
jodconverter-online was introduced in the 4.1.0 version, which will be released in a day or so. So it should be available in maven repository very soon. 

Note that jodconverter-online is still experimental. Any comment or suggestion would be appreciated.

**Comment by sbraconnier** [comment]
jodconverter-online is now available in [maven repository](https://mvnrepository.com/artifact/org.jodconverter/jodconverter-online)
