### ISSUE TITLE
IndexOutOfBoundsException: Index: 1, Size: 1  when Run multiple tasks in concurrent.

### ISSUE THREAD

**Issue by fengzao** [sbraconnier/jodconverter#310]
https://github.com/sbraconnier/jodconverter/blob/45b96788779baac9b1d952859c2ab0d58425e603/jodconverter-local/src/main/java/org/jodconverter/local/task/LocalConversionTask.java#L86 

***BUG ? : ***  when `filterChain == null` use  `RefreshFilter.CHAIN`  cause multiple tasks share one statusful filter.   is need change to. 

``` java

this.filterChain =
        Optional.ofNullable(filterChain).map(FilterChain::copy).orElse(RefreshFilter.CHAIN.copy())


```

**Comment by sbraconnier** [comment]
Hmm.. I'll take a look! Thanks to have reported this.
