### ISSUE TITLE
how can I use jodconverter-remote connect openOffice? old version 2.2.1 can do it  #260

### ISSUE THREAD

**Issue by llm163520** [sbraconnier/jodconverter#312]
###  try (InputStream in = resourceLoader.getResource("classpath:document-formats.json").getInputStream()) {
            try{
                final DocumentFormatRegistry registry = JsonDocumentFormatRegistry.create(in);
                DefaultDocumentFormatRegistryInstanceHolder.setInstance(registry);
                OfficeManager manager = ExternalOfficeManager.builder().install()
                    .portNumbers(8100)
                    .hostName("192.168.0.1")
                    .taskExecutionTimeout(5 * 60 * 1000L)
                    .taskQueueTimeout(1000 * 1000 * 60 * 24L)
                    .build();
                manager.start();
                LocalConverter localConverter = LocalConverter.builder()
                    .officeManager(manager)
                    .formatRegistry(registry)
                    .build();
                InputStream bais = new FileInputStream("d:\\test.xlsx");
                DocumentFormat inputFormat = registry.getFormatByExtension("xlsx");
                DocumentFormat outFormat = registry.getFormatByExtension("pdf");
                localConverter.convert(bais).as(inputFormat).to(new FileOutputStream("d:\\a.pdf")).as(outFormat).execute();
            }catch (Exception ex){
                ex.printStackTrace();
            }
        }
JAVA VERSION: JDK17 
W10
![image](https://user-images.githubusercontent.com/22343834/199273395-8b53e22f-a689-445e-a934-67f53293a8c6.png)

**Comment by sbraconnier** [comment]
This will be fixed in the next version.
