### ISSUE TITLE
How to switch off logging completely

### ISSUE THREAD

**Issue by sboden** [sbraconnier/jodconverter#316]
I would like to switch off logging completely, but I don't find how to do it.

What I already tried is this:

logging.level.*=OFF

and making a logback.xml file with only <configuration></configuration> in there. 
But both don't seem to work.

Regards,
Sven

**Comment by sbraconnier** [comment]
I guess you are using the spring-boot module?

Try 

`logging.level.root=OFF`

**Comment by sbraconnier** [comment]
Closing since not jodconverter related.
