### ISSUE TITLE
Updating from 4.0.0-RELEASE to 4.1.0 where are this classes?

### ISSUE THREAD

**Issue by javydreamercsw** [sbraconnier/jodconverter#32]
Unable to find this classes:

> org.jodconverter.OfficeDocumentConverter;
> org.jodconverter.office.DefaultOfficeManagerBuilder;

They are no longer there so I assume the approach was changed. I was unable to find documentation about it. You probably need to consider Wiki pages to upgrade from one version to another when things like this happen.

**Comment by sbraconnier** [comment]
I totally agree. This is why I didn't post anything yet about the released version :). I still have to publish the release notes and the migration guide.

Now for your problem, the new version has a new "jodconverter-online" module, so I had to create a new "jodconverter-local" module.

User upgrading from 4.0.0 to 4.1.0 should now use the jodconverter-local artifact from maven. Both the local and the online module depend on the core module.

**Comment by javydreamercsw** [comment]
I see. I just saw the new version available on Maven.

**Comment by benelot** [comment]
Maybe announce the update on Maven on the github page and announce that there will be a migration guide at some point and that contributions to it are welcome. Then open up a wiki page and start with the style of the migration guide you would want to have. Then people migrating by themselves can help to document it.

**Comment by sbraconnier** [comment]
Yes it would have been great. I was supposed to release the version and the day after to publish the migration guide (and release notes). But I didn't had enough time to do so. I published the 4.1.0 version before creating the migration guide in order to encourage new JODConverter users to use the 4.1.0 version (the wiki pages use the new 4.1.0 way to convert documents).

For the next release I will have a better "todos" list before releasing ;)

**Comment by sbraconnier** [comment]
Release notes and migration guide done. See:

* [Release Notes 4.1.0](https://github.com/sbraconnier/jodconverter/wiki/Release-Notes-4.1.0)
* [Migration Guide 4.1.0](https://github.com/sbraconnier/jodconverter/wiki/Migration-Guide-4.1.0)

**Comment by benelot** [comment]
Thanks for the great effort you put into this, very inspirational.
