### ISSUE TITLE
Add SSL support for JODConvetrer Online module

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#35]
The module jodconverter-online 4.1.0 does not support SSL.

The module should allow an advanced SSL configuration, including SSL client authentication, support for self-signed certificate, hostname verification strategy, etc...

**Comment by sbraconnier** [comment]
[Done](https://github.com/sbraconnier/jodconverter/wiki/LibreOffice-Online#ssl-support)

**Comment by AniFengx** [comment]
Hey ,it seems like the Sslconfig hasn't been added to 4.1.0 (maven).So if i want to use it for code docker image ,i need to download your source code and gradlew it recently?

**Comment by sbraconnier** [comment]
Yes, just [clone the project](https://help.github.com/articles/cloning-a-repository/) using the command:

```Shell
git clone https://github.com/sbraconnier/jodconverter.git
```

Then you can [build](https://github.com/sbraconnier/jodconverter#building-the-project) the project.

I will release a new version (4.1.1) in a week or so that will include SSL support.

**Comment by sbraconnier** [comment]
Sorry for the delay, but the 4.1.1 version is finally out with SSL support !
