### ISSUE TITLE
Unable to compile code

### ISSUE THREAD

**Issue by javydreamercsw** [sbraconnier/jodconverter#4]
Tried to build and got the following error. Was unable to resolve one of the dependencies.

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'jodconverter'.
> > Could not resolve all dependencies for configuration ':classpath'.
>    > Could not resolve com.netflix.nebula:nebula-project-plugin:3.3.0.
>      Required by:
>          project :
>       > Could not resolve com.netflix.nebula:nebula-project-plugin:3.3.0.
>          > Could not get resource 'https://repo1.maven.org/maven2/com/netflix/ne
> bula/nebula-project-plugin/3.3.0/nebula-project-plugin-3.3.0.pom'.
>             > Could not GET 'https://repo1.maven.org/maven2/com/netflix/nebula/n
> ebula-project-plugin/3.3.0/nebula-project-plugin-3.3.0.pom'.
>                > Connection reset
>       > Could not resolve com.netflix.nebula:nebula-project-plugin:3.3.0.
>          > Could not get resource 'https://plugins.gradle.org/m2/com/netflix/neb
> ula/nebula-project-plugin/3.3.0/nebula-project-plugin-3.3.0.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/com/netflix/nebula/ne
> bula-project-plugin/3.3.0/nebula-project-plugin-3.3.0.pom'.
>                > Connection reset
>    > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:3.1.0.
>      Required by:
>          project :
>       > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:3.1.0.
>          > Could not get resource 'https://repo1.maven.org/maven2/com/diffplug/s
> potless/spotless-plugin-gradle/3.1.0/spotless-plugin-gradle-3.1.0.pom'.
>             > Could not GET 'https://repo1.maven.org/maven2/com/diffplug/spotles
> s/spotless-plugin-gradle/3.1.0/spotless-plugin-gradle-3.1.0.pom'.
>                > Connection reset
>       > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:3.1.0.
>          > Could not get resource 'https://plugins.gradle.org/m2/com/diffplug/sp
> otless/spotless-plugin-gradle/3.1.0/spotless-plugin-gradle-3.1.0.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/com/diffplug/spotless
> /spotless-plugin-gradle/3.1.0/spotless-plugin-gradle-3.1.0.pom'.
>                > Connection reset
>    > Could not resolve io.spring.gradle:dependency-management-plugin:1.0.1.RELEA
> SE.
>      Required by:
>          project :
>       > Could not resolve io.spring.gradle:dependency-management-plugin:1.0.1.RE
> LEASE.
>          > Could not get resource 'https://repo1.maven.org/maven2/io/spring/grad
> le/dependency-management-plugin/1.0.1.RELEASE/dependency-management-plugin-1.0.1
> .RELEASE.pom'.
>             > Could not GET 'https://repo1.maven.org/maven2/io/spring/gradle/dep
> endency-management-plugin/1.0.1.RELEASE/dependency-management-plugin-1.0.1.RELEA
> SE.pom'.
>                > Connection reset
>       > Could not resolve io.spring.gradle:dependency-management-plugin:1.0.1.RE
> LEASE.
>          > Could not get resource 'https://plugins.gradle.org/m2/io/spring/gradl
> e/dependency-management-plugin/1.0.1.RELEASE/dependency-management-plugin-1.0.1.
> RELEASE.pom'.
>             > Could not GET 'https://plugins.gradle.org/m2/io/spring/gradle/depe
> ndency-management-plugin/1.0.1.RELEASE/dependency-management-plugin-1.0.1.RELEAS
> E.pom'.
>                > Connection reset
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug
> option to get more log output.
> 
> BUILD FAILED

**Comment by sbraconnier** [comment]
The build was indeed broken, but not because of the missing dependencies from the stack trace you posted here. I have fixed the broken build, but I doubt it will resolve your issue. Could you please retry with my latest commit and if the problem is still there, could you please tell me what is the exact command you used to build the project. Thanks!

**Comment by javydreamercsw** [comment]
Trying to build after pulling changes.

The command I use is: 

> gradle build

I will let you know if it works or not.

**Comment by sbraconnier** [comment]
When using gradle, you use the (gradle) distribution installed on your OS (according to the configured PATH). Try this instead:

gradlew build

which will use the gradle wrapper that comes with the project.

**Comment by javydreamercsw** [comment]
Still got same issue. Might be something locally at work.

**Comment by sbraconnier** [comment]
This seems to be similar to your problem. I would try this answer if I were you:

[http://stackoverflow.com/a/25243438](url)

**Comment by javydreamercsw** [comment]
Tried at home and got past that but still was unable to build after checking out latest:

```
:jodconverter-cli:spotlessJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jodconverter-cli:spotlessJava'.
> The following files had format violations:
      jodconverter-cli/src/integTest/java/org/artofsolving/jodconverter/cli/ConvertTest.java
          @@ -1,69 +1,69 @@
          -/*\r\n
          - * Copyright 2004 - 2012 Mirko Nasato and contributors\r\n
          - *           2016 - 2017 Simon Braconnier and contributors\r\n
          - *\r\n
          - * This file is part of JODConverter - Java OpenDocument Converter.\r\n
          - *\r\n
          - * JODConverter is an Open Source software: you can redistribute it and/or\r\n
          - * modify it under the terms of either (at your option) of the following\r\n
          - * licenses:\r\n
          - *\r\n
          - * 1. The GNU Lesser General Public License v3 (or later)\r\n
          - *    http://www.gnu.org/licenses/lgpl-3.0.txt\r\n
          - * 2. The Apache License, Version 2.0\r\n
          - *    http://www.apache.org/licenses/LICENSE-2.0.txt\r\n
          - */\r\n
          -\r\n
          -package org.artofsolving.jodconverter.cli;\r\n
          -\r\n
          -import static org.junit.Assert.assertTrue;\r\n
          -\r\n
          -import java.io.File;\r\n
          -\r\n
          -import org.junit.Test;\r\n
          -\r\n
          -public class ConvertTest {\r\n
          -\r\n
          -  private static final String CONFIG_DIR = "src/integTest/resources/config/";\r\n
          -  private static final String SOURCE_FILE = "src/test/resources/documents/test.doc";\r\n
          -  private static final String OUTPUT_DIR = "test-output/" + ConvertTest.class.getSimpleName();\r\n
          -\r\n
          -  @Test\r\n
          -  public void convert() throws Exception {\r\n
          -\r\n
          -    final File inputFile = new File(SOURCE_FILE);\r\n
          -    final File outputFile = new File(OUTPUT_DIR, "convert.pdf");\r\n
          -\r\n
          -    Convert.main(new String[] {"-k", inputFile.getPath(), outputFile.getPath()});\r\n
          -\r\n
          -    assertTrue(outputFile.isFile() && outputFile.length() > 0);\r\n
          -  }\r\n
          -\r\n
          -  @Test\r\n
          -  public void convertWithMultipleFilters() throws Exception {\r\n
          -\r\n
          -    final File filterChainFile = new File(CONFIG_DIR + "filterchain_multiple.xml");\r\n
          -    final File inputFile = new File(SOURCE_FILE);\r\n
          -    final File outputFile = new File(OUTPUT_DIR, "convertconvertWithSingleFilters.pdf");\r\n
          -\r\n
      ... (90 more lines that didn't fit)
  Violations also present in:
      jodconverter-cli/src/main/java/org/artofsolving/jodconverter/cli/Convert.java
      jodconverter-cli/src/main/java/org/artofsolving/jodconverter/cli/CliConverter.java
      jodconverter-cli/src/main/java/org/artofsolving/jodconverter/cli/FilterChainBeanFactory.java
  Run 'gradlew spotlessApply' to fix these violations.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by sbraconnier** [comment]
Hi,

Sorry for that, it's a known issue. I suppose you are building on a linux
distribution or maybe MAC ? I introduced a plugin (spotless) in order to
manage formatting and the header licensing in each source file. I work on
Windows so I suppose that this is the reason why a build on linux fails
(not the same end of line). For now, just do:

gradlew spotlessApply

and the plugin will apply the changes required to build the project.
An annoying step but I'll fix this before publishing the artifacts to
maven...

Regards,

Simon Braconnier
simonbraconnier@gmail.com

**Comment by javydreamercsw** [comment]
I'll give it a try and yes I tried on Ubuntu.

**Comment by javydreamercsw** [comment]
Yes, that did the trick. On Gradle you should be able to detect the OS and run that command if needed.

**Comment by sbraconnier** [comment]
I've added a .gitattributes file at the root project level that should be
enough to solve this problem. I successfully built the project on Ubuntu
(after a fresh git clone) without any problem.

Thanks !

Simon Braconnier
simonbraconnier@gmail.com
