### ISSUE TITLE
custome html format

### ISSUE THREAD

**Issue by AniFengx** [sbraconnier/jodconverter#41]
Can i control the jodconverter convert some file to .html that the format is what i want.
Such as charset=gb2312 i need utf-8.
Sorry foy my bad English

**Comment by sbraconnier** [comment]
Could you please check if it's possible to do so using LibreOffice or Apache OpenOffice without JOConverter ? If the anwser is yes, then there is a way to do it with JODConverter.

Could you also check if #16 is somehow what you are trying to do??

**Comment by AniFengx** [comment]
Hey , i have found the option to set the charset for html in libreoffice gui.
But do you have any method to add the property to your jodconverter?
And i try to ues the JsonDocumentFormatRegistry to add a DocumentFormat  by copying your HTML format and adding loadproperties in it.It doesn't work.
such as :
`String a = "[{\"name\": \"HTML\",\"extension\": \"ht\",\"mediaType\": \"text/html\", \"inputFamily\": \"TEXT\", \"loadProperties\": {\"CharacterSet\": \"utf-8\" },\"storeProperties\": { \"SPREADSHEET\": { \"FilterName\": \"HTML (StarCalc)\"  },  \"PRESENTATION\": {    \"FilterName\": \"impress_html_Export\"     },    \"TEXT\": {        \"FilterName\": \"HTML (StarWriter)\"	      }		    }		  }]";
)`
`JsonDocumentFormatRegistry customRegistry = JsonDocumentFormatRegistry.create(a);`
`LocalConverter.builder().formatRegistry(customRegistry)`

**Comment by sbraconnier** [comment]
Can you please tell me where is this option in the LibreOffice GUI ? I didn't find it. 

Also, the custom registry you built will only be able to load and save file from/to html. And the charset you uses will only be applied when loading an html document. 

Can you please tell me what if the format of the source document you try to convert to HTML ?

**Comment by AniFengx** [comment]
This is the Page about the option .[https://help.libreoffice.org/Common/HTML_compatibility](url)
: Choose Tools - Options' - Load/Save' - HTML Compatibility.
.doc or .docx is the format of the source document which i try to convert.
I mainly convert MS Office to .html for previewing in my program.

**Comment by AniFengx** [comment]
And another quertion about MS Office to .html.
When i use jodconverter to convert a .doc to .html , it will create  a .html file and some .png because the word has some images. But those images will be compiled into base64 in html file if i use the libreoffice gui.
Do you have idea about to control jodconverter to use base64 not some images.

**Comment by sbraconnier** [comment]
You have to set the [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) to the path of the user directory you configured if you want these settings to be applied while using JODConverter.

Here on my Windows, after settings LibreOffice to suit my needs (using the GUI), I copied the directory `C:\Users\myUser\AppData\Roaming\LibreOffice\4` into `C:\JodConverter\templateProfile` (to act as a template profile directory that won't change) and set the templateProfileDir to this copy:

```java
LocalOfficeManager.builder()
    .templateProfileDir("C:\\JodConverter\\LO\\templateProfile")
    .install()
    .build();
```

I search a lot for your second question and found that it is possible to embed the images using an option with the HTML format filter. Here's a working example:

```java
final File input = new File("input.doc");
final File output = new File("output.html");

final DocumentFormat format = DocumentFormat.copy(DefaultDocumentFormatRegistry.HTML);
format.getStoreProperties(DocumentFamily.TEXT).put("FilterOptions", "EmbedImages");
JodConverter.convert(input).to(output).as(format).execute();
```

**Comment by sbraconnier** [comment]
Note that with my latest commit, the DocumentFormat must be created this way:

```java
final File input = new File("input.doc");
final File output = new File("output.html");

final DocumentFormat format =
    DocumentFormat.builder()
        .from(DefaultDocumentFormatRegistry.HTML)
        .storeProperty(DocumentFamily.TEXT, "FilterOptions", "EmbedImages")
        .build();
JodConverter.convert(input).to(output).as(format).execute();
```

**Comment by AniFengx** [comment]
Do you try it in jodconverter Online module ?
i use it such as : 
```
final DocumentFormat format =
			 DocumentFormat.builder()
			      .from(DefaultDocumentFormatRegistry.HTML)
			      .storeProperty(DocumentFamily.TEXT, "FilterOptions", "EmbedImages")
			       .build();
File tempFile1 = new File("d:/root/fileupload/DevCard/" +"a.doc");
try {
			OnlineConverter.make(officeManager)
			.convert(tempFile1)
			.as(DefaultDocumentFormatRegistry.DOC)
			.to(tempFile)
			.as(format)
			.execute();
		} 
```

**Comment by sbraconnier** [comment]
LibreOffice /Collabora Online only supports conversion "as is". You cannot customize it using filters or custom load/store properties (as far as I know). Maybe they will in the future but for now, the JODConverer Online module only uses the "extension" part of the DocumentFormat in order to build the required URL to execute the conversion.

**Comment by AniFengx** [comment]
OK,i will consider using a springboot-jodconverter with  libreoffice(local) for compromise plan

**Comment by sbraconnier** [comment]
Note that I've uploaded a new [sample rest api](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) that can be used with the jodconverter-online module as client.

Using this sample as server, [this](https://github.com/sbraconnier/jodconverter/issues/41#issuecomment-359999597) would work.

This is just a sample though...

**Comment by AniFengx** [comment]
@sbraconnier  Thank you so much for doing this.I truely need it .

**Comment by cuipengfei** [comment]
> You have to set the [templateProfileDir](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) to the path of the user directory you configured if you want these settings to be applied while using JODConverter.
> 
> Here on my Windows, after settings LibreOffice to suit my needs (using the GUI), I copied the directory `C:\Users\myUser\AppData\Roaming\LibreOffice\4` into `C:\JodConverter\templateProfile` (to act as a template profile directory that won't change) and set the templateProfileDir to this copy:
> 
> ```java
> LocalOfficeManager.builder()
>     .templateProfileDir("C:\\JodConverter\\LO\\templateProfile")
>     .install()
>     .build();
> ```
> 
> I search a lot for your second question and found that it is possible to embed the images using an option with the HTML format filter. Here's a working example:
> 
> ```java
> final File input = new File("input.doc");
> final File output = new File("output.html");
> 
> final DocumentFormat format = DocumentFormat.copy(DefaultDocumentFormatRegistry.HTML);
> format.getStoreProperties(DocumentFamily.TEXT).put("FilterOptions", "EmbedImages");
> JodConverter.convert(input).to(output).as(format).execute();
> ```

Just tried ```templateProfileDir``` and it worked well.
Is it recommended for production? Are there recommendations of either the ```AppData\Roaming\LibreOffice\4``` folder should be somehow cleaned/debloated before copying into prod?
