### ISSUE TITLE
Merge multiple fodt files and convert to PDF 

### ISSUE THREAD

**Issue by ikr0m** [sbraconnier/jodconverter#42]
I'm using old version of jodconverter 2.2.1. I don't know if it's possible to merge multiple fodt files and then convert to pdf file. Now I can convert 1 fodt file to pdf. 
I find this fork, I want to use it if it supports converting multiple files to 1 pdf file (merge then convert). 
For example: I've a.fodt, b.fodt, c.fodt, extra.fodt files. I want this a.fodt + extra.fodt => result.pdf, b.fodt + extra.fodt => result2.pdf, ...

**Comment by ikr0m** [comment]
I'm using java 8, playframework, scala, sbt.

**Comment by sbraconnier** [comment]
Out of the box it is not possible, but the missing parts could be added with little effort. I find the idea quite interesting so I would check how to do this (within a week) and come back to you with my results.

The missing parts are that fodt is not supported by default (but can be added easily, I'll open an issue to support it by default) and the other part would be to create a [Filter](https://github.com/sbraconnier/jodconverter/wiki/Using-Filters) that would merge a document to the original document being converted. Such a filter could then be added to the filter chain for each document to merge.

**Comment by sbraconnier** [comment]
Could you please try the latest version of the master branch? You will have to use the new DocumentInserterFilter in order to merge documents. Using the same example you provided:

```java

final DocumentInserterFilter inserterFilter = new DocumentInserterFilter(new File("extra.fodt"));

// Merge a.fodt with extra.fodt to produce result.pdf
LocalConverter
  .builder()
  .filterChain(inserterFilter)
  .build()
  .convert(new File("a.fodt"))
  .to(new File("result.pdf"))
  .execute();

// Merge b.fodt with extra.fodt to produce result2.pdf
LocalConverter
  .builder()
  .filterChain(inserterFilter)
  .build()
  .convert(new File("b.fodt"))
  .to(new File("result2.pdf"))
  .execute();
```

Note that you can merge multiple documents. The following example would merge a.fodt, b.fodt, c.fodt and extra.fodt to produce result.pdf:

```java

final DocumentInserterFilter bFilter = new DocumentInserterFilter(new File("b.fodt"));
final DocumentInserterFilter cFilter = new DocumentInserterFilter(new File("c.fodt"));
final DocumentInserterFilter extraFilter = new DocumentInserterFilter(new File("extra.fodt"));

// Merge a.fodt with extra.fodt to produce result.pdf
LocalConverter
  .builder()
  .filterChain(bFilter , cFilter, extraFilter)
  .build()
  .convert(new File("a.fodt"))
  .to(new File("result.pdf"))
  .execute();
```

**Comment by ikr0m** [comment]
Thank you for positive response and effort! I'll try to use it soon.

**Comment by ikr0m** [comment]
Tried to concatenate  2 fodt files and generate pdf file:

```
val fodt1 = Paths.get("/path/to/file1.fodt").toFile
val fodt2 = Paths.get("/path/to/file2.fodt").toFile
val pdfMerged = Paths.get("/path/to/merged_3.pdf").toFile

val inserterFilter = new DocumentInserterFilter(fodt1)

LocalConverter
    .builder()
    .filterChain(inserterFilter)
    .build()
    .convert(fodt2)
    .to(pdfMerged)
    .execute()
```

But `merged_3.pdf` file contains only `file1.fodt` file content. It's ignoring fodt2.

**Comment by sbraconnier** [comment]
Which version of LibreOffice is it ? Is it possible for you to provide me with files (removing all sensitive data) I could use to reproduce your problem. On my end, everything works just fine.

Can you try the 4.1.1-SNAPSHOT version available in the OSS snapshots repository:
https://oss.sonatype.org/content/repositories/snapshots/

**Comment by ikr0m** [comment]
libreoffice version is `LibreOffice 5.1.6.2 10m0(Build:2)`
This is the code:
```
  val officeManager = LocalOfficeManager.builder().install().build()
  officeManager.start()
  val fodt1 = Paths.get("/home/user/tmp/files/test1.fodt").toFile
  val fodt2 = Paths.get("/home/user/tmp/files/test2.fodt").toFile
  val pdfMerged = Paths.get("/home/user/tmp/files/test_result.pdf").toFile
  val inserterFilter = new DocumentInserterFilter(fodt1)
  LocalConverter
      .builder()
      .filterChain(inserterFilter)
      .build()
      .convert(fodt2)
      .to(pdfMerged)
      .execute()
```
Attaching 3 files. Input (test1.fodt, test2.fodt) and output (test_result.pdf). Archived fodt files because github didn't allow to attach them.
[test_result.pdf](https://github.com/sbraconnier/jodconverter/files/1688730/test_result.pdf)
[test_fodt_files.tar.gz](https://github.com/sbraconnier/jodconverter/files/1688734/test_fodt_files.tar.gz)

**Comment by sbraconnier** [comment]
That one is not easy... It seems to be related to "fodt" format. If you convert the fodt to odt first, it works:

```scala
  val officeManager = LocalOfficeManager.builder().install().build()
  officeManager.start()
  val fodt1 = Paths.get("/home/user/tmp/files/test1.fodt").toFile
  val odt1 = Paths.get("/home/user/tmp/files/test1.odt").toFile
  val fodt2 = Paths.get("/home/user/tmp/files/test2.fodt").toFile
  val odt2 = Paths.get("/home/user/tmp/files/test2.odt").toFile
  val pdfMerged = Paths.get("/home/user/tmp/files/test_result.pdf").toFile

  LocalConverter.make().convert(fodt1).to(odt1).execute()
  LocalConverter.make().convert(fodt2).to(odt2).execute()

  val inserterFilter = new DocumentInserterFilter(odt1)

  LocalConverter
      .builder()
      .filterChain(inserterFilter)
      .build()
      .convert(odt2)
      .to(pdfMerged)
      .execute()
```

I'll try to find out why, but I'm not that confident that I'll find a better option...

**Comment by ikr0m** [comment]
Thanks! That is useful too.
