### ISSUE TITLE
Online conversion never fill OutputStream nor deletes the temp file when converting to OutputStream

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#43]
See #40

The OnlineConversionTask do not call the targetFile.onComplete, and it should.

**Comment by AniFengx** [comment]
Hey ， I try it for .doc to .html.
And i can get the .html file ,but the html doesn't has content .It just have head.
This is the html : 
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">`
`<html>`
`<head>`
`<meta http-equiv="content-type" content="text/html; charset=utf-8"/>`
`	<title></title>`
`	<meta name="generator" content="Collabora Office 5.3.10.36 (Linux)"/>`
`	<meta name="created" content="00:00:00"/>`
`	<meta name="changed" content="00:00:00"/>`
`	<style type="text/css">`
`		@page { size: 8.27in 11.69in; margin: 0.79in }`
`		p { margin-bottom: 0.1in; line-height: 120%; background: transparent }`
`		pre { background: transparent }`
`		pre.western { font-family: "Liberation Mono", monospace; font-size: 10pt }`
`		pre.cjk { font-family: "Noto Sans SC Regular", monospace; font-size: 10pt }`
`		pre.ctl { font-family: "Liberation Mono", monospace; font-size: 10pt }`
`	</style>`
`</head>`
`<body lang="en-US" link="#000080" vlink="#800000" dir="ltr">`
`<pre class="western"></pre>`
`</body>`
`</html>`

**Comment by sbraconnier** [comment]
In fact you have the whole html since the closing `</html>` tag is there. But your content is empty. Could you please provide a document (remove first all sensitive data) with which I could reproduce the problem. Here with my samples, everything works just fine.

**Comment by AniFengx** [comment]
[网络请求地址规范.docx](https://github.com/sbraconnier/jodconverter/files/1656045/default.docx)
it's the word file.

**Comment by AniFengx** [comment]
And the Onilne Office what i am useing is CODE(docker) and LibreOffice Onilne(docker). Both of these haven't  content .

**Comment by sbraconnier** [comment]
Hi there,

Sorry, I was unable to reproduce your issue. It works just fine on my end. Here's my result:

[result.html.zip](https://github.com/sbraconnier/jodconverter/files/1657565/result.html.zip)

**Comment by AniFengx** [comment]
Hey ,maybe i find the bug in jodconverter.
Do you try use a FileInputStream as input of a convertion.
When i use a new File("path") .i can get a total html and it has content.
But html doesn't has content if i use stream.
Do you have any idea about it ?

**Comment by sbraconnier** [comment]
There was a bug indeed! It is fix now. Thanks.
