### ISSUE TITLE
Don't start or kill libreoffice related processes automatically.

### ISSUE THREAD

**Issue by ikr0m** [sbraconnier/jodconverter#49]
I couldn't find necessary functionality from spec, and here is an idea:
We need config param to control creating libreoffice processes. Now if libreoffice process is not running jodconverter tries to start it automatically. I think it should **not** start/restart office process and should depend on some config parameter. 
It can be `autoStartOfficeProcess` param and by default it might be `true`. If user sets `false` to this param, jodconverter shouldn't start/restart office process and should throw error about not running process. User takes responsibility for running processes. 
Note: old jodconverter 2.2.1 by default didn't start office process. This feature (starting process automatically) is good and should be controlled by user.

**Comment by sbraconnier** [comment]
If you want to just connect to a running office process (not started by jodconverter), try to build an OfficeManager using the ExternalOfficeManagerBuilder, which is not documented unfortunately. I think this manager if the old one that you used with jodconverter 2.2.1.

**Comment by sbraconnier** [comment]
No feedback, closing this one. Fell free to reopen it.

**Comment by ikr0m** [comment]
I have been using jodconverter 2.2.1. But it doesn't support fodt, docx formats and I wanted to use your jodconverter. Then I realized that I could achieve other not supported formats with DocumentFormat class in old jodconverter. So I'm continuing using old jodconverter with following code changes:
```
var connection: SocketOpenOfficeConnection = null
try {
  connection = new SocketOpenOfficeConnection(8100)
  connection.connect()

  val defaultFormatRegistry = new DefaultDocumentFormatRegistry()
  val fodtDocFormat = new DocumentFormat("OpenDocument Text Flat XML", DocumentFamily.TEXT, "application/vnd.oasis.opendocument.text-flat-xml", "fodt")
  fodtDocFormat.setExportFilter(DocumentFamily.TEXT, "OpenDocument Text Flat XML")
  defaultFormatRegistry.addDocumentFormat(fodtDocFormat)

  val docxDocFormat = new DocumentFormat("Microsoft Word 2007-2013 XML", DocumentFamily.TEXT, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "docx")
  docxDocFormat.setExportFilter(DocumentFamily.TEXT, "MS Word 2007 XML")
  defaultFormatRegistry.addDocumentFormat(docxDocFormat)

  val converter = new OpenOfficeDocumentConverter(connection, defaultFormatRegistry)
  converter.convert(docxFile, fodtFile)
} catch {
  case e: Throwable =>
    logger.error("", e)
} finally {
  if (connection != null) {
    connection.disconnect()
  }
}
```
