### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by ddrozdov** [sbraconnier/jodconverter#5]
Please.

**Comment by javydreamercsw** [comment]
Yes please. I'm using 3.0 beta.

**Comment by sbraconnier** [comment]
Working on it! I have to go through the required procedure in order to be able to publish to the Maven Central. Stay tuned :).

**Comment by sbraconnier** [comment]
The JIRA ticket is opened and I bought the jodconverter.org domain, so the groupid will be org.jodconverter. The package names will probably be changed to reflect that.

Coming soon...

**Comment by javydreamercsw** [comment]
Nice. Looking forward to swap my dependencies.

**Comment by sbraconnier** [comment]
It's done!

Look for the groupid org.jodconverter

**Comment by javydreamercsw** [comment]
Maybe adding a section in the README on this will be helpful.

**Comment by javydreamercsw** [comment]
@sbraconnier Building with your version right now!

**Comment by sbraconnier** [comment]
Glad to hear that! I hope your computer didn't explode ;)

**Comment by javydreamercsw** [comment]
It didn't and everything seems to be working fine.

https://github.com/javydreamercsw/validation-manager
