### ISSUE TITLE
Support for the latest LibreOffice

### ISSUE THREAD

**Issue by hv0912** [sbraconnier/jodconverter#51]
The LibreOffice 6 has been released. The default installation path is changed from "C:\Program Files\LibreOffice 5" to "C:\Program Files\LibreOffice".

**Comment by sbraconnier** [comment]
Seriously ? Oups! I guess another version of JODConverter will be released very soon ! Thanks for the tips. Do you know if the linux/mac installation path has also changed ?

**Comment by hv0912** [comment]
Sorry, I did not test on other operating systems, but I found an explanation of the change in the official release notes.

https://wiki.documentfoundation.org/ReleaseNotes/6.0#Platform_Compatibility.

It is understood that this change occurs only in Windows.

**Comment by sbraconnier** [comment]
Thanks a lot ! It is fixed now. The version 4.1.2 will be released very soon.
