### ISSUE TITLE
Use TableOfContentUpdaterFilter in Spring Boot

### ISSUE THREAD

**Issue by codecitizen** [sbraconnier/jodconverter#55]
Hi,

I'm having troubles that DOCX ToC are updated when generating PDFs in my Spring Boot Service. So I stumbled across [this closed issue](https://github.com/sbraconnier/jodconverter/issues/26), where `TableOfContentUpdaterFilter` was introduced. But I'm not sure how to configure it when using the Spring Boot Starter. The autowired `DocumentConverter` can only be influenced by the properties, but I don't see a property for filters. Do I need to dump the spring libraries and use jodconverter directly, or am I missing something here? 

Thanks in advance for your answers.

**Comment by codecitizen** [comment]
Update: Posted into Gitter, but put here for documentation:
```
@sbraconnier Hey, I raised this issue today sbraconnier/jodconverter#55 but after looking into the source of the sprint boot starter, I'm fairly certain one needs to change it so it supports TableOfContentUpdaterFilter. So, if I'm not wrong, I would we willing to fork it, add a property called smth like updateTOC and raise a pull request. Would this be OK with you? Or would it break some architecture/design guidelines rules and I should approach it differently?
```

**Comment by sbraconnier** [comment]
Hello there,

You have some options here.

If you always want to include the TableOfContentUpdaterFilter while converting, you could just override the default DocumentConverter created been by adding something like this somewhere in a configuration class:

```java
@Bean
public DocumentConverter documentConverter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new TableOfContentUpdaterFilter())
      .build();
}
```

If you want to use a converter with this particular filter on specific condition, you can create a new converter for each conversion:

```java
@Autowired private OfficeManager officeManager;

private void someMethod() {

  LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new TableOfContentUpdaterFilter())
      .build()
      .convert(...)
}
```

or you could also create a new been with a different name you would inject using a Resource annotation when you need that particular bean:

```java
@Bean
public DocumentConverter documentConverterWithTocFilter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new TableOfContentUpdaterFilter())
      .build();
}
```

```java

@Resource(name = "documentConverter")
private DocumentConverter converter;

@Resource(name = "documentConverterWithTocFilter")
private DocumentConverter converterWithTocFilter;

private void convert() {

  converter.convert(...)
}

private void convertUpdatingToc() {

  converterWithTocFilter.convert(...)
}

```

**Comment by codecitizen** [comment]
Hey, so I implemented the first version, and it works fine on my dev machine (OSX with Open Office) but when I deploy it as a Docker Container with ubuntu:16.04 and LibreOffice (current Version) the ToC is not updated. Any known issue in this setup?

**Comment by sbraconnier** [comment]
which version of libre office are you using ?

**Comment by sbraconnier** [comment]
Nevermind, could you please confirm that the TableOfContentUpdaterFilter is called. Sadly there is no logging in this class (I'll fix that), but you could provide a trace like this:

```java
static class MyFilter extends TableOfContentUpdaterFilter {

  private static final Logger LOGGER = LoggerFactory.getLogger(MyFilter.class);

  @Override
  public void doFilter(OfficeContext context, XComponent document, FilterChain chain)
      throws Exception {

    LOGGER.info("Applying the TableOfContentUpdaterFilter");

    super.doFilter(context, document, chain);
  }
}

@Bean
public DocumentConverter documentConverter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new MyFilter())
      .build();
}
```

**Comment by codecitizen** [comment]
I see the log Message and Libre Office Version is LibreOffice 6.0.1.1 00m0(Build:1)

**Comment by sbraconnier** [comment]
Well, that is strange. I made a couple of tests since yesterday and the filter seems to work just fine with this version of LibreOffice, although I didn't test the exact same setup as you did.

Can you please test the following converters (using the same MyFilter from my previous post). And if you can set the logging level to debug, your log file will contain more information :

```java
@Bean
public DocumentConverter documentConverter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new RefreshFilter(), new MyFilter())
      .build();
}
```

```java
@Bean
public DocumentConverter documentConverter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new RefreshFilter(), new MyFilter(), new RefreshFilter())
      .build();
}
```

```java
@Bean
public DocumentConverter documentConverter(
        final OfficeManager officeManager) {

  return LocalConverter.builder()
      .officeManager(officeManager)
      .filterChain(new MyFilter(), new RefreshFilter())
      .build();
}
```

**Comment by codecitizen** [comment]
```
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:58.915 DEBUG 5 --- [nio-8080-exec-1] o.j.o.AbstractOfficeManagerPoolEntry     : Waiting for task to complete...
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:58.916  INFO 5 --- [agerPoolEntry-1] o.jodconverter.task.LocalConversionTask  : Executing local conversion task...
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.151 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Applying the RefreshFilter
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.154 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Refreshing...
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.158  INFO 5 --- [agerPoolEntry-1] o.j.f.text.TableOfContentUpdaterFilter   : Applying the TableOfContentUpdaterFilter
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.171 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Applying the RefreshFilter
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.172 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Refreshing...
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.173 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Applying the RefreshFilter
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.173 DEBUG 5 --- [agerPoolEntry-1] org.jodconverter.filter.RefreshFilter    : Refreshing...
pdfconverter.1.va0yevvstpwy@docker-master    | 2018-02-20 14:04:59.226 DEBUG 5 --- [nio-8080-exec-1] o.j.o.AbstractOfficeManagerPoolEntry     : Task executed successfully
```

**Comment by sbraconnier** [comment]
I was hoping that applying a filter before the TOC update as it is done in the [nuxeo](https://github.com/nuxeo/jodconverter/blob/3.0-NX/jodconverter-core/src/main/java/org/artofsolving/jodconverter/StandardConversionTask.java#L132) would help. Too bad.

Is it possible for you to test an earlier version (5.x) of LibreOffice with Ubuntu. I just want to rule out the possibility of a LibreOffice version problem. If you confirm that the problem is the same with the 5.x version, I will have to use a linux machine to investigate further (I'm currently on Windows). Also, could you upload here a document (removing all sensitive data first) with which I could reproduce your exact same problem.

**Comment by codecitizen** [comment]
Okay, will do that this afternoon, thanks for the help!

**Comment by sbraconnier** [comment]
Since this issue is inactive for more than a month now, I'm closing it. Feel free to reopen.
