### ISSUE TITLE
Help needed: "An office manager is required in order to build a converter"

### ISSUE THREAD

**Issue by T4iFooN** [sbraconnier/jodconverter#58]
Hi there!
I hope you can help me with this as I found no more example codes. 
If this is the wrong place to ask this kind of question, then I'm sorry.

I used the code snippets from https://github.com/sbraconnier/jodconverter/wiki/Java-Library and /Configuration#file_folderofficehome to get a very simple function to convert a DOC to PDF:

```java
OfficeManager officeManager = LocalOfficeManager.builder().officeHome(officePath).build();
try {
	officeManager.start();
	long start = System.currentTimeMillis();
	JodConverter.convert(new File(src)).to(new File(dest)).execute();
	Logger.writeToLog("Generated pdf in " + (System.currentTimeMillis() - start) + " ms");
} catch (Exception ex) {
	Logger.writeToLog(ex);
} finally {
	OfficeUtils.stopQuietly(officeManager);
}

```
There's a very high change I got something wrong here, but I have absolutely no clue as Eclipse compiles with no errors.

I'm using the CORE and the LOCAL jars (both downloaded from MvmRepo) and resolved all the dependencies.

The code above is the complete function to get called with 3 params: source file, destination file and officePath. I can't use LocalOfficeManager.install() because I don't have a default install of LibreOffice.

I'm on MacOS and use /Volumes/Applications/LibreOffice.app/Contents as officePath variable here.

Any help or hint is appreciated!

Thank You!

Best
Daniel

**Comment by T4iFooN** [comment]
Oh, the import I used for this are 
`import org.jodconverter.JodConverter;
import org.jodconverter.office.*;`

**Comment by sbraconnier** [comment]
Hi,

The `install()` function of an OfficeManager only means that it will be the default manager chosen if no manager is specified when converting a document. If you use the JodConverter.convert shortcut, it will use this default manager. Since you didn't call the `install()`, no office manager is found. Change your code this:

```java
OfficeManager officeManager = LocalOfficeManager.builder().officeHome(officePath).build();
try {
	officeManager.start();
	long start = System.currentTimeMillis();
	LocalConverter.make(officeManager).convert(new File(src)).to(new File(dest)).execute();
	Logger.writeToLog("Generated pdf in " + (System.currentTimeMillis() - start) + " ms");
} catch (Exception ex) {
	Logger.writeToLog(ex);
} finally {
	OfficeUtils.stopQuietly(officeManager);
}

```

**Comment by T4iFooN** [comment]
Thank you very much, this did the trick!
