### ISSUE TITLE
No-args constructor for DocumentFormat does not exist

### ISSUE THREAD

**Issue by recurve** [sbraconnier/jodconverter#59]
Hi,

I'm attempting to upgrade from the abandoned version of JODConverter to your new improved one. Package names ("artofsolving") and API has changed slightly but appears to be very similar. I thought I hooked everything up properly but now when I try to convert an image to PDF I get the following error.

RuntimeException: No-args constructor for class org.jodconverter.document.DocumentFormat does not exist. Register an InstanceCreator with Gson for this type to fix this problem.

Any ideas?

Thanks,

**Comment by recurve** [comment]
I got passed this issue by deleting “gson-1.4.jar” and replacing with: “gson-2.8.2.jar” in my project.

That said, I'm now getting a different error:

Error: The source format is missing or not supported
at org.jodconverter.job.AbstractConversionJobWithSourceFormatUnspecified.toInternal(AbstractConversionJobWithSourceFormatUnspecified.java:109)

**Comment by recurve** [comment]
Wow!

I was uploading a JPG file to be converted to PDF. That's where it said "The source format is missing or not supported"

When I upload a DOCX file... it happily converts to PDF.

Hmm...

This used to work with the old forgotten JODConverter... any reason why it was removed here?

**Comment by recurve** [comment]
Looking at: DefaultDocumentFormatRegistry.java
It has no JPG defined!!!!!
It has PNG but no JPG.... must be an oversight.

**Comment by recurve** [comment]
I created a pull request for: JPG, TIFF, and GIF

**Comment by sbraconnier** [comment]
Thank you so much for this pull request. I'll take a look as soon as possible tomorrow but I don't see any reason to reject this. Good catch! The supported formats are those supported by the original project  (the one I forked). I didn't remove any supported format. I'm not sure why it worked before and not with this version. Thanks again.

**Comment by sbraconnier** [comment]
JODConverter now supports JPG, TIFF and GIF formats, thanks again.
