### ISSUE TITLE
Document export / conversion image properties

### ISSUE THREAD

**Issue by SpaceGerbil** [sbraconnier/jodconverter#61]
I am looking for a bit of guidance here, as I have been searching for a few days now and just can't seem to find the correct settings I am after. When using LibreOffice you can export a office document (.docx) as a .png image. When doing this operation through LibreOffice itself, you have the options to specify the final image Height/Width/DPI.  I want to be able to configure the same information when using the LocalConverter. I am assuming I need to set the storeProperties map on either the converter of the target DocumentFormat, but I can't seem to find what the name/value pair for the map needs to be.

Can anyone point me in the right direction for configuring these options?

**Comment by SpaceGerbil** [comment]
Looks like I found the correct combination:

PropertyValue pngFilterData[] = new PropertyValue[2];
			pngFilterData[0] = new PropertyValue();
			pngFilterData[0].Name = "PixelWidth";
			pngFilterData[0].Value = 2550;
			pngFilterData[1] = new PropertyValue();
			pngFilterData[1].Name = "PixelHeight";
			pngFilterData[1].Value = 3300;
			
			Map<String, Object> writerProperties = new HashMap<String, Object>();
			writerProperties.put("FilterName", "writer_png_Export");
			writerProperties.put("Overwrite", "true");
			writerProperties.put("FilterData", pngFilterData);

			LocalConverter.builder()
					.storeProperties(writerProperties)
					.officeManager(localOfficeManager)
					.filterChain(selectorFilter)
					.build()
					.convert(fis)
					.as(DefaultDocumentFormatRegistry.getFormatByMediaType(contentType))
					.to(exportFile)
					.as(targetFormat)
					.execute();

**Comment by sbraconnier** [comment]
Glad to hear your problem is solved!

You could have shorten this slightly but the result is the same:

```java
final Map<String, Object> filterData = new HashMap<>();
filterData.put("PixelWidth", 2550);
filterData.put("PixelHeight", 3300);

Map<String, Object> customProperties = new HashMap<>();
customProperties.put("Overwrite", true);
customProperties.put("FilterData", filterData);

LocalConverter.builder()
    .storeProperties(customProperties)
    .officeManager(localOfficeManager)
    .filterChain(selectorFilter)
    .build()
    .convert(fis)
    .as(DefaultDocumentFormatRegistry.getFormatByMediaType(contentType))
    .to(exportFile)
    .as(targetFormat)
    .execute();
```

**Comment by hblwyq** [comment]
I was wondering if someone know the filter data of "save transparency" while exporting images to PNG .
In other words, how to config the "save transparency" toolbar ; what is the property name of these configs.
I am looking for a bit of guidance here too, as I have been searching for a few days too. So hard.
And I was wondering how to get the answer too. Appreciate a lot.

**Comment by hblwyq** [comment]
> I was wondering if someone know the filter data of "save transparency" while exporting images to PNG .
> In other words, how to config the "save transparency" toolbar ; what is the property name of these configs.
> I am looking for a bit of guidance here too, as I have been searching for a few days too. So hard.
> And I was wondering how to get the answer too. Appreciate a lot.

Quesion solved.  Use :
 filterData.put("Translucent", 1);
to save transparency.

But then I was wondering how to use "Image Export" other than "Export" in File Tag?
 Is some kind of LoadProperties or Filter can be used?
