### ISSUE TITLE
Service call /service as in old jodconverter

### ISSUE THREAD

**Issue by Alwaysin** [sbraconnier/jodconverter#62]
Is it possible to call the webservice remotely as was possible with the old jodconverter?

I noticed there is this mapping missing:

  <servlet-mapping>
    <servlet-name>DocumentConverterServiceServlet</servlet-name>
    <url-pattern>/service</url-pattern>
  </servlet-mapping>

And obviously the code I want to run is calling this URL http://localhost/service.

For reference the feature was:

````
/**
 * This servlet offers a document converter service suitable for remote invocation
 * by HTTP clients written in any language.
 * <p>
 * To be valid a request to service must:
 * <ul>
 *   <li>use the POST method and send the input document data as the request body</li>
 *   <li>specify the correct <b>Content-Type</b> of the input document</li>
 *   <li>specify an <b>Accept</b> header with the mime-type of the desired output</li>
 * </ul>
 * <p>
 * As a very simple example, a request to convert a text document into PDF would
 * look something like
 * <pre>
 * POST /jooconverter/service HTTP/1.1
 * Host: x.y.z
 * Content-Type: text/plain
 * Accept: application/pdf
 * 
 * Hello world!
 * </pre>
 */

**Comment by sbraconnier** [comment]
Not sure I understand your question. The sample web application is just a sample and I didn't change it so much compared to the original project. Take a look at the project I forked, there is no DocumentConverterServiceServlet either.

But if you want a REST like web service, you may take a look at this sample instead, which uses Spring Boot:
[JODConverter - Sample - Rest API](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest)

**Comment by Alwaysin** [comment]
Yes indeed I was looking for the DocumentConverterServiceServlet. I'll take a look at this sample!
