### ISSUE TITLE
no way to specify filter parameters with CLI version

### ISSUE THREAD

**Issue by janssen** [sbraconnier/jodconverter#63]
unoconv has the -e switch, so you can for instance say

```
$ unoconv -f pdf -eUseTaggedPDF=true -ofoo.pdf foo.docx
```

It would be handy to have the same feature in JODConverter.

**Comment by sbraconnier** [comment]
> It would be handy to have the same feature in JODConverter.

I totally agree! Let me take a look at unoconv and this will be implemented 👍

**Comment by sbraconnier** [comment]
Here's a snapshot of the implementation.

- use -l prefix for load filter properties
- use -s prefix for store filter properties
- use -sFD prefix for FilterData store filter properties.

Reusing your unoconv example, it would be:

`jodconverter-cli -sFDUseTaggedPDF=true foo.docx foo.pdf`

[jodconverter-cli-4.2.1-SNAPSHOT.zip](https://github.com/sbraconnier/jodconverter/files/1920192/jodconverter-cli-4.2.1-SNAPSHOT.zip)

**Comment by janssen** [comment]
Sounds good!  Though I don't understand the difference between "store filter" and "FilterData".  Is that a jodconverter thing?

**Comment by sbraconnier** [comment]
Ya... well,

It's just that "FilterData" is a map of properties stored as a single store filter property. It will contain the [PDF Export filter data](https://wiki.openoffice.org/wiki/API/Tutorials/PDF_export). Internally, JODConverter will create a map of properties starting with -sFD and will then add this map to the store filter properties, as required by the LibreOffice/OpenOffice API. Here's a conversion example without the CLI module that illustrates what I try to explain:

```java
File inputFile = new File("document.rtf");
File outputFile = new File("document.pdf");

Map<String, Object> filterData = new HashMap<>();
filterData.put("PageRange", "2-4"); // This is a FilterData property
filterData.put("UseTaggedPDF", true); // This is a FilterData property
Map<String, Object> storeProperties= new HashMap<>();
storeProperties.put("FilterData", filterData);
storeProperties.put("Overwrite", true); // This is NOT a FilterData property

LocalConverter
  .builder()
  .storeProperties(storeProperties)
  .build()
  .convert(inputFile)
  .to(outputFile)
  .execute();
```

Hope it's clearer now :)

**Comment by janssen** [comment]
OK, sounds good.  Let me try out that zip file, and report back.

**Comment by janssen** [comment]
No luck so far...
```
wjanssen@archie:/tmp/jodconverter-cli-4.2.1-SNAPSHOT$ ./bin/jodconverter-cli -spdf -sFDUseTaggedPDF=true ~/Downloads/syllabus.docx /tmp/foo.pdf
Starting office
Converting '/home/wjanssen/Downloads/syllabus.docx' to '/tmp/foo.pdf'
Stopping office
wjanssen@archie:/tmp/jodconverter-cli-4.2.1-SNAPSHOT$ pdfinfo /tmp/foo.pdf
Title:          Mock Syllabus
Author:         Terrill Thompson
Creator:        Writer
Producer:       LibreOffice 5.1
CreationDate:   Tue Apr 17 09:35:22 2018
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      612 x 792 pts (letter)
Page rot:       0
File size:      62192 bytes
Optimized:      no
PDF version:    1.4
wjanssen@archie:/tmp/jodconverter-cli-4.2.1-SNAPSHOT$ 
```

**Comment by janssen** [comment]
My fault!  That extra -spdf threw it off.  Removing that seems to make things work.  However, I did notice one odd thing: specifying the output format with -fpdf threw off the output target location -- it tried to write ~/Downloads/syllabus.pdf instead of the specified /tmp/foo.pdf.
