### ISSUE TITLE
why it must need a extension in the source file?

### ISSUE THREAD

**Issue by aruis** [sbraconnier/jodconverter#66]
if I give a source file named 'abc.doc', the converter is very good.
But, if source file named 'abc', it will  go wrong.
And,the  converter also can run when I remove the  extension check. So ,I think you can remove the source file extension check in the code. here is a [PR](https://github.com/sbraconnier/jodconverter/pull/65)

**Comment by sbraconnier** [comment]
Thanks for the PR! I'll check it out and come back to you!

**Comment by sbraconnier** [comment]
Merged. Thanks for your help!
