### ISSUE TITLE
javadocs?

### ISSUE THREAD

**Issue by janssen** [sbraconnier/jodconverter#69]
Would be handy.

**Comment by sbraconnier** [comment]
The javadoc is available here [javadoc.io](https://javadoc.io).

Search for JODConverter.

**Comment by sbraconnier** [comment]
The link is there:

![javadoc](https://user-images.githubusercontent.com/15372565/39829428-6b24a22c-538c-11e8-9c38-15b831d0611f.PNG)

It's quite annoying that the links are broken. I'll see what I can do, thanks for reporting that.
