### ISSUE TITLE
Import documentation from former JODConverter site.

### ISSUE THREAD

**Issue by sbraconnier** [sbraconnier/jodconverter#7]
The original author of JODConverter generously and positively answered to my request, which was about the content of the now unresponsive former JODConverter web site. My goal is to import (and update) the documentation here on GitHub.

**Comment by javydreamercsw** [comment]
That would be awesome! Would that make yours the official replacement?

I believe yours is the most active.

**Comment by sbraconnier** [comment]
Not for me to decide! I suppose that people will be more interested by a well documented fork that is published to maven central. We'll see :)

**Comment by sbraconnier** [comment]
Documentation will always be a work in progress, but all that could be imported from the old site has been imported (and modified if required).
