### ISSUE TITLE
Patching library to be able reuse already running libreoffice instances >> killExistingProcess(false)

### ISSUE THREAD

**Issue by tran4o** [sbraconnier/jodconverter#72]
In the current version it is not possible to reuse running instances with same port etc, 
the simple patch would be :

OfficeProcess.java

replace 
 	if (existingPid != PID_NOT_FOUND && existingPid != PID_UNKNOWN) {
with
	 if (existingPid != PID_NOT_FOUND && existingPid != PID_UNKNOWN && config.isKillExistingProcess()) {

**Comment by tran4o** [comment]
We have situation with multiple server instances (different processes) running on single node (virtual machine) sharing the office connection pool (ip range). So after stop / start / restart of some server instance , the office process stays alive and is reused from different servers / different session.  Anyway it is quite difficult to ensure office termination of office processes after server stop (perhaps forced stop, the worst case not the 'normal') , so for our scenarios everything is fine without killing instances on start.The server starts faster and does not implies extra office processes per server instance.

**Comment by sbraconnier** [comment]
It will be possible to do that in the next release. See [existingProcessAction](https://github.com/sbraconnier/jodconverter/wiki/Configuration#capital_abcdexistingprocessaction) and [keepAliveOnShutdown](https://github.com/sbraconnier/jodconverter/wiki/Configuration#white_check_markkeepaliveonshutdown)
