### ISSUE TITLE
Using powershell (deprecated windows server 2012) for windows process manager

### ISSUE THREAD

**Issue by tran4o** [sbraconnier/jodconverter#73]
Checking running processes in windows should be done direct without regexp matching with : 

public class WindowsProcessManager extends AbstractProcessManager {

  @Override
	public long findPid(ProcessQuery query) throws IOException {
	  
	  String flt = "commandline LIKE '%"+query.getArgument()+"%' AND NOT (commandline LIKE '%cmd.exe%\\\\c%powershell%')";
	  String[] procList = new String[] {
			  "cmd","/c","powershell \"Get-WmiObject Win32_Process -Filter \\\""+flt+"\\\" | Select-Object ProcessId \""	
	  };
	  final List<String> lines = execute(procList);
	  for (String s : lines) {
		  s=s.trim();
		  try {
			  long pid = Long.parseLong(s);
			  return pid;
		  } catch (NumberFormatException e) {		  }
	  }
	  return PID_NOT_FOUND;
	}

..

**Comment by sbraconnier** [comment]
Thanks for the suggestion. Did you have any problem with the current `wmic `command ?

**Comment by tran4o** [comment]
yes , this we use custom process manager to avoid patching the library. After investigation it seems that the problem is the querying of the program arguments of all processes. Under some circumstances the only provided access is to query process ids for specific arguments. It is faster and safer. Similar solution can be achieved with wmic.
