### ISSUE TITLE
validateOfficeTemplateProfileDirectory seems to check wrong thing

### ISSUE THREAD

**Issue by janssen** [sbraconnier/jodconverter#76]
I'm trying to set a custom template directory, and failing.  The code in validateOfficeTemplateProfileDirectory seems to require a subdirectory called "user".  But clearly, as per https://wiki.documentfoundation.org/UserProfile#Default_locations, the directory ending with "user" *is* the user profile directory, it's not *contained within* the user profile directory.  This function should be checking for the presence of "autocorr", "autotext", etc. as detailed under https://wiki.documentfoundation.org/UserProfile#User_profile_content.

    // Template profile directory is not required.
    if (templateProfileDir == null || new File(templateProfileDir, "user").isDirectory()) {
      return;
    }

**Comment by janssen** [comment]
OK, semantics.  You think the directory that holds the "user" subdirectory is the profile directory, I think the "user" subdirectory *is* the profile directory (based on reading the text from https://wiki.documentfoundation.org/UserProfile).  Confusing, probably should document this in LocalOfficeManager.Builder.templateProfileDir().

**Comment by janssen** [comment]
This is an actual problem.  I'd like to get around the double startup of soffice.bin by pointing jodconverter to an existing profile directory.  The user account running jodconverter might never have run soffice, so there would be no $HOME/.config/libreoffice/4/user.  Ideally, I'd just use the pre-installed template version of the profile directory at /usr/lib/libreoffice/share/.  But there's no extraneous "user" subdirectory there, so I can't.  Fixing this misapprehension about what the profile directory is would fix that.

**Comment by sbraconnier** [comment]
The Javadoc could be improved for sure. There is more on the  [wiki page](https://github.com/sbraconnier/jodconverter/wiki/Configuration#file_foldertemplateprofiledir) about the templateProfileDir.

I understand your point about the `share` directory, but the fact is that this directory is way bigger than a regular profile directory. Don't forget that this "templateProfileDir" is COPIED into a temporary directory for the office instance that is about to be started (which is required in order to be able to start multiple office instances). Here on my Windows, pointing on the "share" directory will copy 150+ MB. A regular profile directory is around 1.5 MB. I don't think you will benefit from copying 150MB on each startup of soffice.bin instead of a double startup :).

The way I usually use the templateProfileDir is explained [here](https://github.com/sbraconnier/jodconverter/issues/41#issuecomment-359625798). I create a copy of a profile directory elsewhere (outside the user account).

**Comment by janssen** [comment]
Hit this again.  I'm running tests with jodconverter on a Gitlab CI setup which uses a Docker image with LibreOffice installed (the mbsi/s2i-java-libreoffice Docker from DockerHub).  But my tests fail with this:

```
$ bash extract.sh -console -debug test1.doc
templatePath is /opt/app-root/src/.config/libreoffice/4/user
Temporary profile directory is /tmp/LibreOfficeUserTemplate2531831472878994228
java.io.FileNotFoundException: Source '/opt/app-root/src/.config/libreoffice/4/user' does not exist
```

Because LibreOffice has never been run on that virtual machine.  We need some way of running this on a machine where LibreOffice has never been manually run.  Or perhaps there's some way to run LibreOffice in a script which wouldn't do anything but would initialize that directory?

**Comment by janssen** [comment]
> I understand your point about the share directory, but the fact is that this directory is way bigger than a regular profile directory. Don't forget that this "templateProfileDir" is COPIED into a temporary directory for the office instance that is about to be started (which is required in order to be able to start multiple office instances). Here on my Windows, pointing on the "share" directory will copy 150+ MB. A regular profile directory is around 1.5 MB. I don't think you will benefit from copying 150MB on each startup of soffice.bin instead of a double startup :).

But it would be OK for a fallback, wouldn't it?  Use the user config if it exists; otherwise, copy the share directory.  That would allow JODConverter to actually not fail in situations in which it currently fails.

**Comment by sbraconnier** [comment]
I assume that your script `extract.sh` is aware of the '`/opt/app-root/src/.config/libreoffice/4/user`' directory ? Or if it is hard coded into the program being called ? If it's in the script, maybe you could check first if the directory exists, and if not, just don't set the `templateProfileDir` ?

**Comment by sbraconnier** [comment]
> But it would be OK for a fallback, wouldn't it? Use the user config if it exists; otherwise, copy the share directory. That would allow JODConverter to actually not fail in situations in which it currently fails.

This is an interesting idea, it would not be that hard to implement. Let me check this and come back to you.

**Comment by sbraconnier** [comment]
Closing. See #81

**Comment by janssen** [comment]
> I assume that your script extract.sh is aware of the '/opt/app-root/src/.config/libreoffice/4/user' directory ? Or if it is hard coded into the program being called ? If it's in the script, maybe you could check first if the directory exists, and if not, just don't set the templateProfileDir ?

Tried this; works OK, too.  Still get the double startup, but only once.
