### ISSUE TITLE
Not able to detect running instances

### ISSUE THREAD

**Issue by mattkallo** [sbraconnier/jodconverter#84]
Hi,   We are getting the below exception irrespective of how we start the soffice processes. Tried different options, but still getting the same issue. Could you please give an idea on how to resolve this? 

1) Let JODConverter start the process. 
In this case. Its not able to find the PID and throws the below exception. I thought the issue was with checking the PID too soon after starting the process. So, tried the 2nd option.

2) Started soffice process as a service 
Tried starting soffice on required ports (2002, 2003) as a service. But still its not able to see the process. It throws the below exception itself.

We haven't made any changes to the library. Should we add a sleep after starting the process with process manager before checking for PID? Is that the solution or there is something else we need to do/handle?

Appreciate your inputs....

OS - UBUNTU 16.04
Spring - 5.0.4

Caused by: org.jodconverter.office.OfficeException: A process with acceptString 'socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager' started but its pid could not be found
        at org.jodconverter.office.OfficeProcess.start(OfficeProcess.java:354)
        at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:100)
        at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
        at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260)
        at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255)
        ... 4 common frames omitted

**Comment by sbraconnier** [comment]
Hmm, that's odd... Could you please set your logging level to TRACE and print back here the output logs ? Thanks!

**Comment by mattkallo** [comment]
Thanks for checking. I couldn't reproduce the issue after setting to trace. Will post the log once I get it. 

Now its able to start the process. However, I see another exception given below. Is that normal? It starts successfully at the end though.

The exception "process hasn't exited" repeats around 30 times between 2 ports, then it starts successfully. 

INFO  org.jodconverter.office.OfficeProcessManager -Submitting task 'Start' and waiting...
2018-07-30 07:46:26.993 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Command Output:
25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25956; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25963; Command line: [soffice.bin] <defunct>
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.005 [OfficeProcessThread-1]
INFO  org.jodconverter.office.OfficeProcess -Starting process with acceptString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
2018-07-30 07:46:27.006 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Command Output:
25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
25963 [soffice.bin] <defunct>
25996 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25956; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25963; Command line: [soffice.bin] <defunct>
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25996 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25996; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
DEBUG org.jodconverter.process.AbstractProcessManager -Command line matches! Returning pid: 25996
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
INFO  org.jodconverter.office.OfficeProcess -Started process; pid = 25996
2018-07-30 07:46:27.021 [OfficeProcessThread-1]
DEBUG org.jodconverter.office.OfficeConnection -Connecting with connectString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
2018-07-30 07:46:27.022 [OfficeProcessThread-1]
TRACE org.jodconverter.office.OfficeProcess -IllegalThreadStateException catch in getExitCode
java.lang.IllegalThreadStateException: process hasn't exited
at java.lang.UNIXProcess.exitValue(UNIXProcess.java:423)
at org.jodconverter.office.OfficeProcess.getExitCode(OfficeProcess.java:176)
at org.jodconverter.office.ConnectRetryable.attempt(ConnectRetryable.java:72)
at org.jodconverter.office.AbstractRetryable.execute(AbstractRetryable.java:57)
at org.jodconverter.office.ConnectRetryable.execute(ConnectRetryable.java:26)
at org.jodconverter.office.OfficeProcessManager.doStartProcessAndConnect(OfficeProcessManager.java:104)
at org.jodconverter.office.OfficeProcessManager.access$100(OfficeProcessManager.java:40)
at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:260)
at org.jodconverter.office.OfficeProcessManager$4.call(OfficeProcessManager.java:255)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2018-07-30 07:46:27.272 [OfficeProcessThread-1]
DEBUG org.jodconverter.office.OfficeConnection -Connecting with connectString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
2018-07-30 07:46:27.272 [OfficeProcessThread-1]
WARN  org.jodconverter.office.ConnectRetryable -Office process died with exit code 81; restarting it
2018-07-30 07:46:27.272 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Command Output:
25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25956; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25963; Command line: [soffice.bin] <defunct>
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.288 [OfficeProcessThread-1]
INFO  org.jodconverter.office.OfficeProcess -Starting process with acceptString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
2018-07-30 07:46:27.289 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Finding PID using
Command to get current running processes: [/bin/bash, -c, /bin/ps -e -o pid,args | /bin/grep soffice | /bin/grep -v grep]
Regex used to match current running process lines: ^\s*(?<Pid>\d+)\s+(?<CommanLine>.*)$
Regex used to match running office process we are looking for: \Qsoffice\E.*\Qsocket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager\E
2018-07-30 07:46:27.304 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Command Output:
25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
25963 [soffice.bin] <defunct>
26016 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25956 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25956; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2002_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 25963 [soffice.bin] <defunct>
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 25963; Command line: [soffice.bin] <defunct>
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Checking if process line matches the process line regex
Process line: 26016 /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
TRACE org.jodconverter.process.AbstractProcessManager -Line matches!
pid: 26016; Command line: /usr/lib/libreoffice/program/soffice.bin -accept=socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager -env:UserInstallation=file:///home/user/apps/apache-tomcat-8.0.27/temp/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1 -invisible -norestore -nofirststartwizard -nologo -nodefault -nolockcheck -headless -nocrashreport
Checking if this command line matches the office command line regex
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
DEBUG org.jodconverter.process.AbstractProcessManager -Command line matches! Returning pid: 26016
2018-07-30 07:46:27.305 [OfficeProcessThread-1]
INFO  org.jodconverter.office.OfficeProcess -Started process; pid = 26016
2018-07-30 07:46:27.555 [OfficeProcessThread-1]
DEBUG org.jodconverter.office.OfficeConnection -Connecting with connectString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
2018-07-30 07:46:27.563 [OfficeProcessThread-1]
INFO  org.jodconverter.office.OfficeConnection -Connected: 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
2018-07-30 07:46:27.563 [localhost-startStop-1]
DEBUG org.jodconverter.office.OfficeProcessManager -Task 'Start' executed successfully
2018-07-30 07:46:27.564 [localhost-startStop-1]

**Comment by sbraconnier** [comment]
Yes this is normal. The way JODConverter checks if a process is running is by using the [Process.exitValue](https://docs.oracle.com/javase/8/docs/api/java/lang/Process.html#exitValue--). This exception is thrown when the process is running (not terminated). 

JODConverter has to check the state of a process to be able to properly manage a pool of processes. Thus, this exception is thrown many times. This is why the exception appears in the logs only when the level is set to TRACE.
