### ISSUE TITLE
Offtopic? LibreOffice CPU usage experiences.

### ISSUE THREAD

**Issue by EugenMayer** [sbraconnier/jodconverter#89]
We have been running into CPU high utilisation issues with LO 6.x (latest). Tracking down the issue it seems to be a glib issue https://gitlab.gnome.org/GNOME/glib/issues/1128

Even though the current patch is not yet part of any released version (2.58 does still not include it) people report that starting with 2.54 it works fairly well ( e.g. in arch ).

Of course, all this is done with the combination of JODconverter - i am not sure if that is offtopic, but i guess about anybody using JODconverter will be in need of running an libreoffice somehow, so it might be at least "value-able" information / knowledge exchange. 

@sbraconnier feel free to just close this uncommented if this is offtopic from your POV - no offense taken

**Comment by sbraconnier** [comment]
Thanks for sharing your findings! I'll close this issue since I can't do anything about it but it will stay in the issues history.
