### ISSUE TITLE
Is it possible to stop reinitializing Office Process Manager during Spring Live Reload

### ISSUE THREAD

**Issue by imtiazShakil** [sbraconnier/jodconverter#96]
Hi,
I'm using jodconverter in my Spring Application.

Every time Spring reloads the application OfficeProcessManager submits "Start" Task and waits. This slows down Spring live reload performance.

Is there any solution to this problem? 
Thanks

**Comment by sbraconnier** [comment]
Sorry for the delay. Not sure if I can do anything about it. I'm not familiar with Spring Live Reload. I'll take a look at this.

**Comment by imtiazShakil** [comment]
Hi,

1. Create a simple Spring Boot Application.
2. Autowire `DocumentConverter` service in your application.
3. Build and run your application
4. Now change any part of your code & save.
5. Spring Live reload will automatically reload the whole application (with only updated classes and others by Spring classloader)


Upon Live reload you'll notice two things,
First of all `OfficeProcessManager` tries to stop the connection:
Generated Console Output:

```
o.j.o.AbstractOfficeManagerPool          : Stopping the office manager pool...
o.j.o.OfficeProcessManager               : Submitting task 'Stop' and waiting...
o.j.o.OfficeConnection                   : Disconnected: 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
o.j.o.OfficeProcessManager               : process exited with code 0
o.j.o.AbstractOfficeManagerPool          : Office manager stopped
```

Second, during reload the console output looks like this:

```
o.j.o.OfficeProcessManager               : Submitting task 'Start' and waiting...
o.j.o.OfficeProcess                      : Starting process with acceptString 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1;urp;StarOffice.ServiceManager' and profileDir '/var/folders/9l/6bzh2pk51fl02d6x9nzqs2ph0000gn/T/.jodconverter_socket_host-127.0.0.1_port-2003_tcpNoDelay-1'
o.j.o.OfficeProcess                      : Started process; pid = 1450
o.j.o.OfficeConnection                   : Connected: 'socket,host=127.0.0.1,port=2003,tcpNoDelay=1'
```

Stopping and Starting Office Task each time there is a change in the application slows down the development phase. Is there any way, this can be avoided?

Best Regards.

**Comment by sbraconnier** [comment]
I already tried some ideas but none did the trick. #72 could be the solution. But it won't be easy to implement (if possible). Meanwhile, maybe you could use the [jodconverter-sample-rest](https://github.com/sbraconnier/jodconverter/tree/master/jodconverter-samples/jodconverter-sample-rest) sample as a dedicated server for conversions and just enable the online module in the application.properties file.

The section though is not well documented yet. See [this resource](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-spring-boot-starter/src/integTest/resources/config/application-online.properties) for a list of spring-boot online properties.

**Comment by sbraconnier** [comment]
It will be possible to do that in the next release. See [existingProcessAction](https://github.com/sbraconnier/jodconverter/wiki/Configuration#capital_abcdexistingprocessaction) and [keepAliveOnShutdown](https://github.com/sbraconnier/jodconverter/wiki/Configuration#white_check_markkeepaliveonshutdown)

Note that connecting to an office process is what takes the most time. Not sure if those new options will help that much but they won't hurt!!
