### ISSUE TITLE
Incorrect usage of Validate.notNull method

### ISSUE THREAD

**Issue by alexey-atiskov** [sbraconnier/jodconverter#97]
In class [https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/task/LocalConversionTask.java](https://github.com/sbraconnier/jodconverter/blob/master/jodconverter-local/src/main/java/org/jodconverter/task/LocalConversionTask.java) there is method storeDocument with lines

`
final Map<String, Object> storeProps = getStoreProperties(document);
Validate.notNull(storeProps, "Unsupported conversion");
`

but method getStoreProperties always return Map object (empty or not)

Either replace validation with !storeProps.isEmpty() or remove validation at all (I don't know which is better)

**Comment by sbraconnier** [comment]
Thanks for reporting this!

**Comment by alexey-atiskov** [comment]
Thanks for correct fix =)
